function manifest = capture_stage2a_frozen_hashes(cfg, boundary, label)
    arguments
        cfg struct
        boundary (1, 1) string {mustBeMember(boundary, ["stage1", "stage2b"])}
        label (1, 1) string {mustBeMember(label, ["before", "after"])}
    end
    if boundary == "stage1"
        roots = ["config/published_generator_config.m", ...
            "config/stage_1_gate1_config.m", "src/published_generator", ...
            "analysis/published_generator", "figures/published_generator", ...
            "results/stage_1", "plots/stage_1", "run_stage_1.m", ...
            "workflows/stage_1/construction/run_stage_1_gate1_rejection_sampling.m"];
    else
        roots = ["config/stage_2b_kao_config.m", ...
            "config/stage_2b_cerebellum_config.m", "src/stage_2b_kao", ...
            "src/stage_2b_cerebellum", "analysis/stage_2b_shared", ...
            "figures/stage_2b_shared", "results/stage_2b_kao", ...
            "results/stage_2b_cerebellum", "plots/stage_2b_kao", ...
            "plots/stage_2b_cerebellum", "run_stage_2b_kao.m", ...
            "run_stage_2b_cerebellum.m"];
    end
    manifest = hash_tree(cfg.projectRoot, roots);
    if ~isfolder(cfg.workAuditRoot)
        mkdir(cfg.workAuditRoot);
    end
    filename = sprintf('%s_frozen_hashes_%s.csv', boundary, label);
    writetable(manifest, fullfile(cfg.workAuditRoot, filename));
end
