function report = finalize_stage2a_gate2_failure(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    cfg = stage_2a_config(projectRoot);
    networkAudit = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2a_network_audit.csv'));
    targetAudit = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2a_target_audit.csv'));
    assert(height(networkAudit) == 10 && sum(networkAudit.Pass) == 6);
    assert(height(targetAudit) == 80 && sum(targetAudit.Pass) == 76);
    stage1Before = readtable(fullfile(cfg.workAuditRoot, ...
        'stage1_frozen_hashes_before.csv'));
    stage1After = readtable(fullfile(cfg.workAuditRoot, ...
        'stage1_frozen_hashes_after.csv'));
    stage2bBefore = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2b_frozen_hashes_before.csv'));
    stage2bAfter = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2b_frozen_hashes_after.csv'));
    assert(isequal(stage1Before, stage1After));
    assert(isequal(stage2bBefore, stage2bAfter));

    legacyManifestPath = fullfile(cfg.resultsRoot, ...
        'stage2a_artifact_manifest.csv');
    legacyManifest = readtable(legacyManifestPath, ...
        'VariableNamingRule', 'preserve');
    assert(height(legacyManifest) == 16);
    legacyMatched = verify_manifest(projectRoot, legacyManifest);
    assert(legacyMatched == height(legacyManifest));
    ensembleFiles = dir(fullfile(cfg.workEnsembleRoot, ...
        'network_*_stage2a.mat'));
    assert(numel(ensembleFiles) == 10);
    assert(~isfolder(cfg.workPlotsRoot) || isempty(dir(fullfile( ...
        cfg.workPlotsRoot, '**', '*.png'))));

    codeFiles = [string(fullfile(projectRoot, 'run_stage_2a.m')); ...
        string(fullfile(projectRoot, 'config', 'stage_2a_config.m')); ...
        string(fullfile(projectRoot, 'src', 'stage_2a', ...
            'compute_tonic_input.m')); ...
        string(fullfile(projectRoot, 'src', 'stage_2a', ...
            'simulate_naive_preparation.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'analyze_stage2a.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'bootstrap_network_median.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'capture_stage2a_frozen_hashes.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'run_stage2a_smoke_tests.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'summarize_stage2a_ensemble.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'validate_stage2a_ensemble_components.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'finalize_stage2a_gate2.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'revalidate_stage2a_ensemble.m')); ...
        string(fullfile(projectRoot, 'analysis', 'stage_2a', ...
            'finalize_stage2a_gate2_failure.m')); ...
        string(fullfile(projectRoot, 'figures', 'stage_2a', ...
            'create_stage2a_figures.m'))];
    analyzerMessages = 0;
    for index = 1:numel(codeFiles)
        analyzerMessages = analyzerMessages ...
            + numel(checkcode(codeFiles(index), '-id'));
    end
    assert(analyzerMessages == 0);

    failed = networkAudit(~networkAudit.Pass, :);
    failureCriteria = strings(height(failed), 1);
    for row = 1:height(failed)
        criteria = strings(0, 1);
        if failed.MaximumLongStateErrorFraction(row) ...
                > cfg.acceptance.maximumLongStateErrorFraction
            criteria(end + 1) = "5-s state-error fraction > 0.01"; %#ok<AGROW>
        end
        if failed.MaximumLongEndpointErrorM(row) ...
                > cfg.acceptance.maximumLongEndpointErrorM
            criteria(end + 1) = "5-s endpoint error > 0.001 m"; %#ok<AGROW>
        end
        failureCriteria(row) = strjoin(criteria, '; ');
    end
    failureTable = table(failed.Network, failed.RecurrentSeed, ...
        failed.CalibrationSeed, failureCriteria, ...
        'VariableNames', {'Network','RecurrentSeed','CalibrationSeed', ...
        'FailedCriteria'});
    writetable(failureTable, fullfile(cfg.workAuditRoot, ...
        'stage2a_failure_reasons.csv'));
    manifestRoots = ["config/stage_2a_config.m", "src/stage_2a", ...
        "analysis/stage_2a", "figures/stage_2a", "run_stage_2a.m", ...
        "results/stage_2a_gate2_work"];
    diagnosticManifest = hash_tree(projectRoot, manifestRoots);
    manifestPath = fullfile(cfg.workAuditRoot, ...
        'gate2_failure_diagnostic_manifest.csv');
    writetable(diagnosticManifest, manifestPath);
    assert(verify_manifest(projectRoot, diagnosticManifest) ...
        == height(diagnosticManifest));

    report = struct('status', ...
        'GATE 2 STOPPED — STAGE 2A VALIDATION FAILURE', ...
        'networkRows', height(networkAudit), ...
        'networkPasses', sum(networkAudit.Pass), ...
        'targetRows', height(targetAudit), ...
        'targetPasses', sum(targetAudit.Pass), ...
        'failedNetworks', failed.Network.', ...
        'stage1HashRowsMatched', height(stage1After), ...
        'stage2bHashRowsMatched', height(stage2bAfter), ...
        'legacyStage2aManifestMatched', legacyMatched, ...
        'diagnosticManifestEntries', height(diagnosticManifest), ...
        'codeAnalyzerMessages', analyzerMessages, ...
        'canonicalCleanupPerformed', false, ...
        'canonicalFiguresGenerated', false, ...
        'stage2bExecuted', false);
    write_json(fullfile(cfg.workAuditRoot, ...
        'gate2_failure_verification.json'), report);
end

function matched = verify_manifest(projectRoot, manifest)
    names = manifest.Properties.VariableNames;
    pathName = names{strcmpi(names, 'relative_path') ...
        | strcmpi(names, 'RelativePath')};
    bytesName = names{strcmpi(names, 'bytes') | strcmpi(names, 'Bytes')};
    hashName = names{strcmpi(names, 'sha256') | strcmpi(names, 'Sha256')};
    matched = 0;
    for row = 1:height(manifest)
        path = fullfile(projectRoot, manifest.(pathName){row});
        if ~isfile(path)
            continue
        end
        metadata = dir(path);
        expectedBytes = double(manifest.(bytesName)(row));
        expectedHash = string(manifest.(hashName){row});
        if metadata.bytes == expectedBytes ...
                && strcmpi(sha256_file(path), expectedHash)
            matched = matched + 1;
        end
    end
end

function write_json(path, value)
    fid = fopen(path, 'w');
    assert(fid ~= -1, 'Could not open %s for writing.', path);
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(value, PrettyPrint=true));
end
