function report = finalize_stage2a_gate2(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    addpath(fullfile(projectRoot, 'analysis', 'stage_2a'));
    cfg = stage_2a_config(projectRoot);
    networkAudit = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2a_network_audit.csv'));
    targetAudit = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2a_target_audit.csv'));
    assert(height(networkAudit) == cfg.acceptance.requiredNetworkCount ...
        && all(networkAudit.Pass));
    assert(height(targetAudit) == cfg.acceptance.requiredTargetRows ...
        && all(targetAudit.Pass));
    stage1Before = readtable(fullfile(cfg.workAuditRoot, ...
        'stage1_frozen_hashes_before.csv'), TextType='string');
    stage1After = readtable(fullfile(cfg.workAuditRoot, ...
        'stage1_frozen_hashes_after.csv'), TextType='string');
    stage2bBefore = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2b_frozen_hashes_before.csv'), TextType='string');
    stage2bAfter = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2b_frozen_hashes_after.csv'), TextType='string');
    assert(isequal(stage1Before, stage1After), ...
        'Frozen Stage-1 hashes changed during Stage 2A.');
    assert(isequal(stage2bBefore, stage2bAfter), ...
        'Frozen Stage-2B hashes changed during Stage 2A.');
    validate_figure_pairs(cfg.workPlotsPngRoot, cfg.workPlotsFigRoot, 5);
    stagedAuditRoot = fullfile(cfg.workResultsRoot, 'audit');
    assert(~isfolder(stagedAuditRoot));
    movefile(cfg.workAuditRoot, stagedAuditRoot);

    temporaryOldResults = fullfile(projectRoot, 'results', ...
        'stage_2a_pre_gate2_single_network_20260831');
    temporaryOldPlots = fullfile(projectRoot, 'plots', ...
        'stage_2a_pre_gate2_single_network_20260831');
    assert(~isfolder(temporaryOldResults) && ~isfolder(temporaryOldPlots));
    assert(isfolder(cfg.resultsRoot) && isfolder(cfg.plotsRoot));
    movefile(cfg.resultsRoot, temporaryOldResults);
    movefile(cfg.plotsRoot, temporaryOldPlots);
    mkdir(cfg.resultsRoot);
    movefile(cfg.workResultsRoot, fullfile(cfg.resultsRoot, 'current'));
    movefile(cfg.workPlotsRoot, cfg.plotsRoot);
    historyRoot = fullfile(cfg.resultsRoot, 'audit_history', ...
        'pre_gate2_single_network');
    mkdir(historyRoot);
    movefile(temporaryOldResults, fullfile(historyRoot, 'results'));
    movefile(temporaryOldPlots, fullfile(historyRoot, 'plots'));
    stoppedHistory = fullfile(cfg.workRoot, 'audit_history', ...
        'gate2_initial_stop');
    if isfolder(stoppedHistory)
        movefile(stoppedHistory, fullfile(cfg.resultsRoot, ...
            'audit_history', 'gate2_initial_stop'));
    end
    if isfolder(cfg.workRoot)
        rmdir(cfg.workRoot, 's');
    end

    currentRoot = fullfile(cfg.resultsRoot, 'current');
    currentAuditRoot = fullfile(currentRoot, 'audit');
    pngRoot = fullfile(cfg.plotsRoot, 'png');
    figRoot = fullfile(cfg.plotsRoot, 'fig');
    validate_figure_pairs(pngRoot, figRoot, 5);
    codeRoots = ["config/stage_2a_config.m", "src/stage_2a", ...
        "analysis/stage_2a", "figures/stage_2a", "run_stage_2a.m", ...
        "workflows/diagnostics/stage_2a/run_stage_2a_gate2_diagnostic.m", ...
        "README.md", "MODEL_SPEC.md", "AGENTS.md"];
    codeManifest = hash_tree(projectRoot, codeRoots);
    writetable(codeManifest, fullfile(currentAuditRoot, ...
        'stage2a_active_code_manifest.csv'));
    historyManifest = hash_tree(projectRoot, ...
        "results/stage_2a/audit_history");
    historyManifest(endsWith(historyManifest.relative_path, ...
        'history_manifest.csv'), :) = [];
    writetable(historyManifest, fullfile(cfg.resultsRoot, ...
        'audit_history', 'history_manifest.csv'));
    artifactRoots = ["results/stage_2a/current", ...
        "plots/stage_2a/png", "plots/stage_2a/fig"];
    artifactManifest = hash_tree(projectRoot, artifactRoots);
    excluded = endsWith(artifactManifest.relative_path, ...
        'stage2a_current_artifact_manifest.csv') ...
        | endsWith(artifactManifest.relative_path, ...
        'stage2a_manifest_verification.json');
    artifactManifest(excluded, :) = [];
    writetable(artifactManifest, fullfile(currentAuditRoot, ...
        'stage2a_current_artifact_manifest.csv'));
    assert(verify_manifest(projectRoot, artifactManifest), ...
        'Stage-2A artifact manifest failed immediate verification.');
    runSummary = jsondecode(fileread(fullfile(currentRoot, ...
        'stage2a_summary.json')));
    report = struct('status', runSummary.status, ...
        'networkCount', height(networkAudit), ...
        'targetRows', height(targetAudit), ...
        'allNetworksPassed', all(networkAudit.Pass), ...
        'allTargetRowsPassed', all(targetAudit.Pass), ...
        'maximumFixedPointResidual', ...
            max(networkAudit.MaximumFixedPointResidual), ...
        'maximumLongStateErrorFraction', ...
            max(networkAudit.MaximumLongStateErrorFraction), ...
        'maximumLongProspectiveErrorFraction', ...
            max(networkAudit.MaximumLongProspectiveErrorFraction), ...
        'maximumLongEndpointErrorM', ...
            max(networkAudit.MaximumLongEndpointErrorM), ...
        'maximumLongHandNRMSE', max(networkAudit.MaximumLongHandNRMSE), ...
        'maximumLongTorqueNRMSE', max(networkAudit.MaximumLongTorqueNRMSE), ...
        'conditionalAcceptance', true, ...
        'historicalStateThresholdDescriptive', true, ...
        'historicalStateMissRows', sum(~targetAudit.HistoricalFullStatePass), ...
        'historicalEndpoint1mmMissRows', ...
            sum(~targetAudit.HistoricalEndpoint1mmPass), ...
        'revisedEndpointThresholdM', 0.002, ...
        'figurePairCount', 5, 'allFiguresReopened', true, ...
        'stage1FileCount', height(stage1After), ...
        'stage1ArtifactsUnchanged', true, ...
        'stage2bFileCount', height(stage2bAfter), ...
        'stage2bArtifactsUnchanged', true, ...
        'artifactCount', height(artifactManifest), ...
        'historyArtifactCount', height(historyManifest), ...
        'activeCodeFileCount', height(codeManifest), ...
        'representativeNetwork', cfg.ensemble.representativeIndex, ...
        'bootstrapSamples', cfg.ensemble.bootstrapSamples, ...
        'bootstrapSeed', cfg.ensemble.bootstrapSeed, ...
        'stage2bExecuted', false);
    write_json(fullfile(currentAuditRoot, ...
        'stage2a_final_acceptance_report.json'), report);
    verification = struct('verified', true, ...
        'artifactCount', height(artifactManifest), ...
        'historyArtifactCount', height(historyManifest), ...
        'activeCodeFileCount', height(codeManifest));
    write_json(fullfile(currentAuditRoot, ...
        'stage2a_manifest_verification.json'), verification);
end

function validate_figure_pairs(pngRoot, figRoot, expectedCount)
    pngFiles = dir(fullfile(pngRoot, '*.png'));
    figFiles = dir(fullfile(figRoot, '*.fig'));
    pngNames = sort(erase(string({pngFiles.name}), '.png'));
    figNames = sort(erase(string({figFiles.name}), '.fig'));
    assert(numel(pngNames) == expectedCount && isequal(pngNames, figNames));
    for index = 1:numel(figFiles)
        handle = openfig(fullfile(figFiles(index).folder, ...
            figFiles(index).name), 'invisible');
        assert(isgraphics(handle));
        close(handle);
    end
end

function matched = verify_manifest(projectRoot, manifest)
    matched = true;
    for row = 1:height(manifest)
        path = fullfile(projectRoot, manifest.relative_path(row));
        if ~isfile(path) || dir(path).bytes ~= manifest.bytes(row) ...
                || sha256_file(path) ~= manifest.sha256(row)
            matched = false;
            return
        end
    end
end

function write_json(path, value)
    fid = fopen(path, 'w');
    assert(fid ~= -1);
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(value, PrettyPrint=true));
end
