function report = revalidate_stage2a_ensemble(projectRoot, useWorkTree)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    if nargin < 2
        useWorkTree = false;
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    cfg = stage_2a_config(projectRoot);
    if useWorkTree
        currentRoot = cfg.workResultsRoot;
        auditRoot = cfg.workAuditRoot;
        pngRoot = cfg.workPlotsPngRoot;
        figRoot = cfg.workPlotsFigRoot;
    else
        currentRoot = fullfile(cfg.resultsRoot, 'current');
        auditRoot = fullfile(currentRoot, 'audit');
        pngRoot = cfg.plotsPngRoot;
        figRoot = cfg.plotsFigRoot;
    end
    original = readtable(fullfile(auditRoot, ...
        'stage2a_network_audit.csv'), TextType='string');
    revalidated = table();
    maximumDifference = 0;
    for network = 1:cfg.ensemble.count
        saved = load(fullfile(currentRoot, 'ensemble', ...
            sprintf('network_%02d_stage2a.mat', network)), 'networkResult');
        value = saved.networkResult;
        stage1Path = fullfile(cfg.ensemble.stage1Root, ...
            sprintf('network_%02d.mat', network));
        actualHash = sha256_file(stage1Path);
        assert(actualHash == string(value.stage1FileSha256));
        metrics = value.movementMetrics;
        longRows = metrics.PreparationDurationS ...
            == cfg.preparation.maximumDurationS;
        maximumFixedPointResidual = max(vecnorm( ...
            value.fixedPointResidual, 2, 1));
        maximumLongStateErrorFraction = max( ...
            value.normalizedStateError(end, :));
        maximumLongProspectiveErrorFraction = max( ...
            value.normalizedProspectiveError(end, :));
        maximumLongEndpointErrorM = max(metrics.EndpointErrorM(longRows));
        maximumLongHandNRMSE = max(metrics.HandTrajectoryNRMSE(longRows));
        maximumLongTorqueNRMSE = max(metrics.TorqueNRMSE(longRows));
        pass = maximumFixedPointResidual ...
            <= cfg.acceptance.fixedPointResidualTolerance ...
            && maximumLongProspectiveErrorFraction ...
            <= cfg.acceptance.maximumLongProspectiveErrorFraction ...
            && maximumLongEndpointErrorM ...
            <= cfg.conditional.maximumEndpointErrorM ...
            && maximumLongHandNRMSE ...
            <= cfg.acceptance.maximumLongHandNrmse ...
            && maximumLongTorqueNRMSE ...
            <= cfg.acceptance.maximumLongTorqueNrmse ...
            && value.smoke.goContinuityMaximum ...
            <= cfg.acceptance.goContinuityTolerance ...
            && value.smoke.nonfiniteCount == 0;
        row = table(network, maximumFixedPointResidual, ...
            maximumLongStateErrorFraction, ...
            maximumLongProspectiveErrorFraction, maximumLongEndpointErrorM, ...
            maximumLongHandNRMSE, maximumLongTorqueNRMSE, pass, ...
            'VariableNames', {'Network','MaximumFixedPointResidual', ...
            'MaximumLongStateErrorFraction', ...
            'MaximumLongProspectiveErrorFraction', ...
            'MaximumLongEndpointErrorM','MaximumLongHandNRMSE', ...
            'MaximumLongTorqueNRMSE','Pass'});
        revalidated = [revalidated; row]; %#ok<AGROW>
        names = row.Properties.VariableNames(2:7);
        for field = 1:numel(names)
            originalValue = double(original.(names{field})(network));
            maximumDifference = max(maximumDifference, ...
                abs(row.(names{field}) - originalValue));
        end
    end
    diagnostic = jsondecode(fileread(fullfile(auditRoot, ...
        'stage2a_conditional_diagnostic_report.json')));
    assert(diagnostic.conditionalAccepted);
    assert(all(revalidated.Pass) && maximumDifference <= 1e-12);
    writetable(revalidated, fullfile(auditRoot, ...
        'stage2a_network_revalidation.csv'));
    pngFiles = dir(fullfile(pngRoot, '*.png'));
    figFiles = dir(fullfile(figRoot, '*.fig'));
    pngNames = sort(erase(string({pngFiles.name}), '.png'));
    figNames = sort(erase(string({figFiles.name}), '.fig'));
    figureBasenamesMatch = numel(pngNames) == 5 ...
        && numel(figNames) == 5 && isequal(pngNames, figNames);
    assert(figureBasenamesMatch);
    for index = 1:numel(figFiles)
        handle = openfig(fullfile(figFiles(index).folder, ...
            figFiles(index).name), 'invisible');
        assert(isgraphics(handle));
        close(handle);
    end
    report = struct('passed', true, ...
        'networkCount', height(revalidated), ...
        'maximumAuditDifference', maximumDifference, ...
        'figurePairCount', numel(figFiles), ...
        'figureBasenamesMatch', figureBasenamesMatch, ...
        'allFiguresReopened', true, ...
        'conditionalDiagnosticPassed', diagnostic.conditionalAccepted, ...
        'stateErrorThresholdIsDescriptive', true, ...
        'revisedEndpointThresholdM', cfg.conditional.maximumEndpointErrorM);
    write_json(fullfile(auditRoot, ...
        'stage2a_ensemble_revalidation.json'), report);
end

function write_json(path, value)
    fid = fopen(path, 'w');
    assert(fid ~= -1);
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(value, PrettyPrint=true));
end
