function report = revise_stage2a_figure_uncertainty(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    addpath(fullfile(projectRoot, 'analysis', 'stage_2a'));
    addpath(fullfile(projectRoot, 'figures'));
    addpath(fullfile(projectRoot, 'figures', 'stage_2a'));
    cfg = stage_2a_config(projectRoot);
    currentRoot = fullfile(cfg.resultsRoot, 'current');
    auditRoot = fullfile(currentRoot, 'audit');
    completePath = fullfile(currentRoot, 'stage2a_complete_results.mat');
    saved = load(completePath, 'ensemble', 'representative', 'summary');
    assert(saved.summary.conditionalAcceptance ...
        && saved.summary.networkCount == cfg.ensemble.count);
    assert(saved.representative.index == cfg.ensemble.representativeIndex);

    stage1Roots = ["config/published_generator_config.m", ...
        "config/stage_1_gate1_config.m", "src/published_generator", ...
        "analysis/published_generator", "figures/published_generator", ...
        "results/stage_1", "plots/stage_1", "run_stage_1.m", ...
        "workflows/stage_1/construction/run_stage_1_gate1_rejection_sampling.m"];
    stage2bRoots = ["config/stage_2b_kao_config.m", ...
        "config/stage_2b_cerebellum_config.m", "src/stage_2b_kao", ...
        "src/stage_2b_cerebellum", "analysis/stage_2b_shared", ...
        "figures/stage_2b_shared", "results/stage_2b_kao", ...
        "results/stage_2b_cerebellum", "plots/stage_2b_kao", ...
        "plots/stage_2b_cerebellum", "run_stage_2b_kao.m", ...
        "run_stage_2b_cerebellum.m"];
    scienceRoots = ["results/stage_2a/current/stage2a_complete_results.mat", ...
        "results/stage_2a/current/stage2a_summary.json", ...
        "results/stage_2a/current/ensemble", ...
        "results/stage_2a/current/ensemble_movement_summary.csv", ...
        "results/stage_2a/current/ensemble_network_distributions.csv", ...
        "results/stage_2a/current/ensemble_preparation_timecourse_summary.csv", ...
        "results/stage_2a/current/movement_metrics_by_preparation_duration.csv", ...
        "results/stage_2a/current/prospective_error_reduction_times.csv", ...
        "results/stage_2a/current/diagnostics"];
    stage1Before = hash_tree(projectRoot, stage1Roots);
    stage2bBefore = hash_tree(projectRoot, stage2bRoots);
    scienceBefore = hash_tree(projectRoot, scienceRoots);
    writetable(stage1Before, fullfile(auditRoot, ...
        'stage1_figure_revision_hashes_before.csv'));
    writetable(stage2bBefore, fullfile(auditRoot, ...
        'stage2b_figure_revision_hashes_before.csv'));
    writetable(scienceBefore, fullfile(auditRoot, ...
        'stage2a_science_hashes_before_figure_revision.csv'));

    panelAudit = build_panel_audit();
    writetable(panelAudit, fullfile(auditRoot, ...
        'stage2a_figure_panel_audit.csv'));
    numericalAudit = verify_saved_ensemble_summaries(cfg, saved.ensemble);
    writetable(numericalAudit, fullfile(auditRoot, ...
        'stage2a_figure_uncertainty_numerical_audit.csv'));
    assert(max(numericalAudit.MedianAbsoluteDifference) <= 1e-15);
    assert(max(numericalAudit.BootstrapSEAbsoluteDifference) <= 1e-15);

    affectedFigures = [1, 3, 5];
    create_stage2a_figures(cfg, saved.representative, saved.ensemble, ...
        affectedFigures);
    basenames = ["01_tonic_input_and_fixed_point"; ...
        "02_cortical_preparation_and_movement"; ...
        "03_prospective_error_during_preparation"; ...
        "04_reaches_vs_preparation_duration"; ...
        "05_movement_error_vs_preparation_duration"];
    inventory = [fullfile(cfg.plotsFigRoot, basenames + ".fig"), ...
        fullfile(cfg.plotsPngRoot, basenames + ".png")];
    inventoryTable = table(inventory(:, 1), inventory(:, 2), ...
        'VariableNames', {'FIG','PNG'});
    writetable(inventoryTable, fullfile(currentRoot, 'plot_inventory.csv'));
    figureVerification = verify_figure_pairs(cfg.plotsPngRoot, ...
        cfg.plotsFigRoot, 5);

    stage1After = hash_tree(projectRoot, stage1Roots);
    stage2bAfter = hash_tree(projectRoot, stage2bRoots);
    scienceAfter = hash_tree(projectRoot, scienceRoots);
    writetable(stage1After, fullfile(auditRoot, ...
        'stage1_figure_revision_hashes_after.csv'));
    writetable(stage2bAfter, fullfile(auditRoot, ...
        'stage2b_figure_revision_hashes_after.csv'));
    writetable(scienceAfter, fullfile(auditRoot, ...
        'stage2a_science_hashes_after_figure_revision.csv'));
    assert(isequal(stage1Before, stage1After));
    assert(isequal(stage2bBefore, stage2bAfter));
    assert(isequal(scienceBefore, scienceAfter));

    report = struct('status', ...
        'STAGE 2A FIGURE-UNCERTAINTY REVISION COMPLETE', ...
        'scienceOrQcChanged', false, 'stage2bExecuted', false, ...
        'networkCount', cfg.ensemble.count, ...
        'bootstrapSamples', cfg.ensemble.bootstrapSamples, ...
        'bootstrapUnit', 'network', ...
        'bootstrapStatistic', ...
            'SD of bootstrap medians (bootstrap SE of median)', ...
        'panelAuditRows', height(panelAudit), ...
        'ensembleQuantitativePanelCount', ...
            sum(panelAudit.Classification == "ensemble quantitative"), ...
        'representativePanelCount', ...
            sum(panelAudit.Classification == "representative/illustrative"), ...
        'numericalAuditRows', height(numericalAudit), ...
        'regeneratedFigureNumbers', affectedFigures, ...
        'maximumMedianAbsoluteDifference', ...
            max(numericalAudit.MedianAbsoluteDifference), ...
        'maximumBootstrapSEAbsoluteDifference', ...
            max(numericalAudit.BootstrapSEAbsoluteDifference), ...
        'figurePairCount', figureVerification.pairCount, ...
        'allFiguresReopened', figureVerification.allFiguresReopened, ...
        'stage1FileCount', height(stage1After), ...
        'stage1ArtifactsUnchanged', true, ...
        'stage2bFileCount', height(stage2bAfter), ...
        'stage2bArtifactsUnchanged', true, ...
        'stage2aScienceFileCount', height(scienceAfter), ...
        'stage2aScienceArtifactsUnchanged', true);
    write_json(fullfile(auditRoot, ...
        'stage2a_figure_uncertainty_revision_report.json'), report);

    codeRoots = ["config/stage_2a_config.m", "src/stage_2a", ...
        "analysis/stage_2a", "figures/stage_2a", "run_stage_2a.m", ...
        "workflows/diagnostics/stage_2a/run_stage_2a_gate2_diagnostic.m", ...
        "workflows/diagnostics/stage_2a/run_stage_2a_figure_revision.m", ...
        "README.md", ...
        "MODEL_SPEC.md", "AGENTS.md"];
    codeManifest = hash_tree(projectRoot, codeRoots);
    writetable(codeManifest, fullfile(auditRoot, ...
        'stage2a_active_code_manifest.csv'));
    artifactRoots = ["results/stage_2a/current", ...
        "plots/stage_2a/png", "plots/stage_2a/fig"];
    artifactManifest = hash_tree(projectRoot, artifactRoots);
    excluded = endsWith(artifactManifest.relative_path, ...
        'stage2a_current_artifact_manifest.csv') ...
        | endsWith(artifactManifest.relative_path, ...
        'stage2a_manifest_verification.json');
    artifactManifest(excluded, :) = [];
    writetable(artifactManifest, fullfile(auditRoot, ...
        'stage2a_current_artifact_manifest.csv'));
    assert(verify_manifest(projectRoot, artifactManifest));
    verification = struct('verified', true, ...
        'artifactCount', height(artifactManifest), ...
        'activeCodeFileCount', height(codeManifest), ...
        'figurePairCount', figureVerification.pairCount, ...
        'allFiguresReopened', figureVerification.allFiguresReopened, ...
        'numericalAuditMaximumDifference', max([ ...
            numericalAudit.MedianAbsoluteDifference; ...
            numericalAudit.BootstrapSEAbsoluteDifference]));
    write_json(fullfile(auditRoot, ...
        'stage2a_manifest_verification.json'), verification);
end

function panelAudit = build_panel_audit()
    figure2Panels = ["A"; "B"; "C"; "D"; "E"; "F"];
    figure3Panels = ["A"; "B"];
    figure4Panels = ["A"; "B"; "C"; "D"; "E"; "F"; "G"; "H"];
    figure5Panels = ["A"; "B"; "C"; "D"];
    figureNumber = [1; 1; repmat(2, 6, 1); repmat(3, 2, 1); ...
        repmat(4, 8, 1); repmat(5, 4, 1)];
    panel = ["A"; "B"; figure2Panels; figure3Panels; ...
        figure4Panels; figure5Panels];
    classification = ["representative/illustrative"; ...
        "ensemble quantitative"; ...
        repmat("representative/illustrative", 6, 1); ...
        repmat("ensemble quantitative", 2, 1); ...
        repmat("representative/illustrative", 8, 1); ...
        repmat("ensemble quantitative", 4, 1)];
    uncertaintyDisplay = strings(numel(figureNumber), 1);
    uncertaintyDisplay(classification == "representative/illustrative") = ...
        "Not applicable; explicitly labelled representative network 1";
    uncertaintyDisplay(classification == "ensemble quantitative") = ...
        "Median across 10 networks ± 1 bootstrap SE";
    uncertaintyDisplay(figureNumber == 3) = ...
        "Continuous curve: shaded ±1 bootstrap-SE band";
    uncertaintyDisplay(figureNumber == 5) = ...
        "Discrete summary: ±1 bootstrap-SE error bars";
    targetAggregation = repmat("median across 8 targets within network", ...
        numel(figureNumber), 1);
    targetAggregation(classification == "representative/illustrative") = ...
        "network-1 target trajectories/examples";
    description = ["Network-1 tonic-input norms"; ...
        "Fixed-point residuals across networks"; ...
        "Network-1 cortical trajectory tile " + figure2Panels; ...
        "Full-state error time course"; "Prospective-error time course"; ...
        "Network-1 reach tile " + figure4Panels; ...
        "Endpoint error by duration"; "Hand NRMSE by duration"; ...
        "Torque NRMSE by duration"; "Network-level correlation summary"];
    panelAudit = table(figureNumber, panel, description, classification, ...
        targetAggregation, uncertaintyDisplay, 'VariableNames', ...
        {'Figure','Panel','Description','Classification', ...
        'WithinNetworkTargetAggregation','DisplayedUncertainty'});
end

function audit = verify_saved_ensemble_summaries(cfg, ensemble)
    audit = table();
    audit = append_time_metric(audit, 3, "A", "StateErrorFraction", ...
        ensemble.stateByNetwork, ensemble.timecourse.PreparationDurationS, ...
        ensemble.timecourse.StateErrorFractionMedian, ...
        ensemble.timecourse.StateErrorFractionBootstrapSE, ...
        cfg.ensemble.bootstrapSeed, cfg.ensemble.bootstrapSamples);
    audit = append_time_metric(audit, 3, "B", ...
        "ProspectiveErrorFraction", ensemble.prospectiveByNetwork, ...
        ensemble.timecourse.PreparationDurationS, ...
        ensemble.timecourse.ProspectiveErrorFractionMedian, ...
        ensemble.timecourse.ProspectiveErrorFractionBootstrapSE, ...
        cfg.ensemble.bootstrapSeed + 1, cfg.ensemble.bootstrapSamples);
    movement = {ensemble.endpointByNetwork, ensemble.handByNetwork, ...
        ensemble.torqueByNetwork};
    names = ["EndpointErrorM", "HandTrajectoryNRMSE", "TorqueNRMSE"];
    panels = ["A", "B", "C"];
    for metric = 1:numel(movement)
        name = names(metric);
        audit = append_time_metric(audit, 5, panels(metric), name, ...
            movement{metric}, ensemble.movementSummary.PreparationDurationS, ...
            ensemble.movementSummary.([char(name) 'Median']), ...
            ensemble.movementSummary.([char(name) 'BootstrapSE']), ...
            cfg.ensemble.bootstrapSeed + 9 + metric, ...
            cfg.ensemble.bootstrapSamples);
    end
    audit = append_scalar_metric(audit, 1, "B", ...
        "MaximumFixedPointResidual", ...
        ensemble.networkAudit.MaximumFixedPointResidual, ...
        ensemble.networkDistributions, cfg.ensemble.bootstrapSeed + 100, ...
        cfg.ensemble.bootstrapSamples);
    audit = append_scalar_metric(audit, 5, "D", ...
        "ProspectiveMovementLogCorrelation", ...
        ensemble.networkAudit.ProspectiveMovementLogCorrelation, ...
        ensemble.networkDistributions, cfg.ensemble.bootstrapSeed + 106, ...
        cfg.ensemble.bootstrapSamples);
end

function audit = append_time_metric(audit, figureNumber, panel, metric, ...
        byNetwork, durations, savedMedian, savedSE, seed, nSamples)
    statistics = bootstrap_network_median(byNetwork.', nSamples, seed);
    count = numel(durations);
    rows = table(repmat(figureNumber, count, 1), repmat(panel, count, 1), ...
        repmat(metric, count, 1), durations, savedMedian, ...
        statistics.median.', savedSE, statistics.standardError.', ...
        abs(savedMedian - statistics.median.'), ...
        abs(savedSE - statistics.standardError.'), ...
        repmat(10, count, 1), repmat(nSamples, count, 1), ...
        'VariableNames', {'Figure','Panel','Metric','PreparationDurationS', ...
        'SavedMedian','RecomputedMedian','SavedBootstrapSE', ...
        'RecomputedBootstrapSE','MedianAbsoluteDifference', ...
        'BootstrapSEAbsoluteDifference','NetworkCount','BootstrapSamples'});
    audit = [audit; rows];
end

function audit = append_scalar_metric(audit, figureNumber, panel, metric, ...
        values, distributionTable, seed, nSamples)
    statistics = bootstrap_network_median(values, nSamples, seed);
    rowIndex = string(distributionTable.Metric) == metric;
    assert(sum(rowIndex) == 1);
    savedMedian = distributionTable.NetworkMedian(rowIndex);
    savedSE = distributionTable.BootstrapSE(rowIndex);
    rows = table(figureNumber, panel, metric, nan, savedMedian, ...
        statistics.median, savedSE, statistics.standardError, ...
        abs(savedMedian - statistics.median), ...
        abs(savedSE - statistics.standardError), 10, nSamples, ...
        'VariableNames', {'Figure','Panel','Metric','PreparationDurationS', ...
        'SavedMedian','RecomputedMedian','SavedBootstrapSE', ...
        'RecomputedBootstrapSE','MedianAbsoluteDifference', ...
        'BootstrapSEAbsoluteDifference','NetworkCount','BootstrapSamples'});
    audit = [audit; rows];
end

function verification = verify_figure_pairs(pngRoot, figRoot, expectedCount)
    pngFiles = dir(fullfile(pngRoot, '*.png'));
    figFiles = dir(fullfile(figRoot, '*.fig'));
    pngNames = sort(erase(string({pngFiles.name}), '.png'));
    figNames = sort(erase(string({figFiles.name}), '.fig'));
    assert(numel(pngNames) == expectedCount && isequal(pngNames, figNames));
    allReopened = true;
    for index = 1:numel(figFiles)
        handle = openfig(fullfile(figFiles(index).folder, ...
            figFiles(index).name), 'invisible');
        allReopened = allReopened && isgraphics(handle);
        close(handle);
    end
    assert(allReopened);
    verification = struct('pairCount', expectedCount, ...
        'allFiguresReopened', allReopened);
end

function matched = verify_manifest(projectRoot, manifest)
    matched = true;
    for row = 1:height(manifest)
        path = fullfile(projectRoot, manifest.relative_path(row));
        if ~isfile(path) || dir(path).bytes ~= manifest.bytes(row) ...
                || sha256_file(path) ~= manifest.sha256(row)
            matched = false;
            return
        end
    end
end

function write_json(path, value)
    fid = fopen(path, 'w');
    assert(fid ~= -1);
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(value, PrettyPrint=true));
end
