function report = run_stage2a_conditional_diagnostic(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src', 'stage_2a'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    cfg = stage_2a_config(projectRoot);
    preserve_initial_stop(cfg);
    stage1Before = capture_stage2a_frozen_hashes(cfg, "stage1", "before");
    stage2bBefore = capture_stage2a_frozen_hashes(cfg, "stage2b", "before");
    historicalNetworkAudit = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2a_network_audit.csv'));
    historicalTargetAudit = readtable(fullfile(cfg.workAuditRoot, ...
        'stage2a_target_audit.csv'));
    assert(height(historicalNetworkAudit) == 10);
    assert(height(historicalTargetAudit) == 80);
    observedFailedRows = [historicalTargetAudit.Network(~historicalTargetAudit.Pass), ...
        historicalTargetAudit.Target(~historicalTargetAudit.Pass)];
    assert(isequal(observedFailedRows, cfg.conditional.failedRows));

    stability = table();
    potency = table();
    extendedSummary = table();
    extendedTimecourse = table();
    diagnosticRoot = fullfile(cfg.workResultsRoot, 'diagnostics');
    if ~isfolder(diagnosticRoot)
        mkdir(diagnosticRoot);
    end
    startTime = tic;
    for network = 1:cfg.ensemble.count
        networkPath = fullfile(cfg.ensemble.stage1Root, ...
            sprintf('network_%02d.mat', network));
        saved = load(networkPath, 'model', 'networkRow');
        model = saved.model;
        assert(sha256_file(networkPath) ...
            == string(historicalNetworkAudit.Stage1FileSha256(network)));
        [tonicInput, fixedPointResidual] = compute_tonic_input(model);
        preparation = simulate_naive_preparation(model, tonicInput, ...
            cfg.preparation.maximumDurationS);
        q = (model.Qnative + model.Qnative.') / 2;
        [qVectors, qValues] = eig(q, 'vector');
        [qValues, order] = sort(real(qValues), 'descend');
        qVectors = real(qVectors(:, order));
        qTolerance = 1e-10 * max(max(abs(qValues)), 1);
        assert(min(qValues) >= -qTolerance);
        qValues = max(qValues, 0);
        cumulative = cumsum(qValues) / sum(qValues);
        k95 = find(cumulative >= cfg.conditional.potencyFraction, ...
            1, 'first');
        qCapture = cumulative(k95);
        for target = 1:model.nMovements
            xstar = model.xstar(:, target);
            active = double(xstar > 0);
            jacobian = (-eye(model.n) + model.W .* active.') / model.tau;
            eigenvalues = eig(jacobian);
            spectralAbscissa = max(real(eigenvalues));
            residualNorm = norm(fixedPointResidual(:, target));
            stabilityRow = table(network, target, sum(active), ...
                spectralAbscissa, -spectralAbscissa, residualNorm, ...
                spectralAbscissa < 0 && residualNorm ...
                    <= cfg.acceptance.fixedPointResidualTolerance, ...
                'VariableNames', {'Network','Target','ActiveUnits', ...
                'MaximumRealEigenvaluePerS','StabilityMarginPerS', ...
                'FixedPointResidualNorm','Pass'});
            stability = [stability; stabilityRow]; %#ok<AGROW>

            delta = preparation.finalState(:, target) - xstar;
            initialDelta = model.spontaneous - xstar;
            coefficients = qVectors.' * delta;
            squaredContributions = coefficients .^ 2;
            totalSquared = sum(squaredContributions);
            highSquared = sum(squaredContributions(1:k95));
            lowSquared = sum(squaredContributions((k95 + 1):end));
            qContributions = qValues .* squaredContributions;
            totalQ = sum(qContributions);
            highQ = sum(qContributions(1:k95));
            lowQ = sum(qContributions((k95 + 1):end));
            stateFraction = norm(delta) / max(norm(initialDelta), eps);
            initialQ = initialDelta.' * q * initialDelta;
            prospectiveFraction = totalQ / max(initialQ, eps);
            potencyRow = table(network, target, k95, qCapture, ...
                stateFraction, norm(delta), highSquared / totalSquared, ...
                lowSquared / totalSquared, prospectiveFraction, totalQ, ...
                highQ / totalQ, lowQ / totalQ, ...
                abs((highSquared + lowSquared) / totalSquared - 1), ...
                abs((highQ + lowQ) / totalQ - 1), ...
                'VariableNames', {'Network','Target','K95', ...
                'QPotencyCapture','StateErrorFraction','ResidualNorm', ...
                'HighPotencyEuclideanFraction', ...
                'LowPotencyEuclideanFraction', ...
                'ProspectiveErrorFraction','ProspectiveError', ...
                'HighPotencyProspectiveFraction', ...
                'LowPotencyProspectiveFraction', ...
                'EuclideanDecompositionResidual', ...
                'ProspectiveDecompositionResidual'});
            potency = [potency; potencyRow]; %#ok<AGROW>
        end
        failedTarget = cfg.conditional.failedRows( ...
            cfg.conditional.failedRows(:, 1) == network, 2);
        if ~isempty(failedTarget)
            extended = simulate_naive_preparation(model, ...
                tonicInput(:, failedTarget), ...
                cfg.conditional.extendedDurationS);
            delta = squeeze(extended.states(:, :, 1)) ...
                - model.xstar(:, failedTarget).';
            distance = vecnorm(delta, 2, 2);
            initialDistance = distance(1);
            stateFraction = distance / max(initialDistance, eps);
            qError = sum((delta * q) .* delta, 2);
            qFraction = qError / max(qError(1), eps);
            index5 = round(5 / model.samplingDt) + 1;
            index20 = round(cfg.conditional.primaryDiagnosticDurationS ...
                / model.samplingDt) + 1;
            index40 = numel(extended.timesS);
            tailMask = extended.timesS >= cfg.conditional.tailWindowS(1) ...
                & extended.timesS <= cfg.conditional.tailWindowS(2);
            safeDistance = max(distance(tailMask), ...
                eps(max(initialDistance, 1)));
            fit = polyfit(extended.timesS(tailMask), log(safeDistance), 1);
            nonfiniteCount = sum(~isfinite(distance)) ...
                + sum(~isfinite(qError));
            twentyToFiveRatio = stateFraction(index20) ...
                / max(stateFraction(index5), eps);
            continued = nonfiniteCount == 0 ...
                && stateFraction(index20) ...
                    <= cfg.conditional.maximumNormalizedStateAt20S ...
                && twentyToFiveRatio ...
                    <= cfg.conditional.maximumTwentyToFiveStateRatio ...
                && fit(1) < 0 ...
                && stateFraction(index40) < stateFraction(index20);
            summaryRow = table(network, failedTarget, ...
                stateFraction(index5), stateFraction(index20), ...
                stateFraction(index40), twentyToFiveRatio, ...
                qFraction(index5), qFraction(index20), qFraction(index40), ...
                fit(1), nonfiniteCount, continued, ...
                'VariableNames', {'Network','Target', ...
                'StateErrorFraction5S','StateErrorFraction20S', ...
                'StateErrorFraction40S','TwentyToFiveStateRatio', ...
                'ProspectiveErrorFraction5S', ...
                'ProspectiveErrorFraction20S', ...
                'ProspectiveErrorFraction40S', ...
                'LogDistanceSlope10To20PerS','NonfiniteCount','Pass'});
            extendedSummary = [extendedSummary; summaryRow]; %#ok<AGROW>
            nTimes = numel(extended.timesS);
            timeRow = table(repmat(network, nTimes, 1), ...
                repmat(failedTarget, nTimes, 1), extended.timesS, distance, ...
                stateFraction, qError, qFraction, ...
                'VariableNames', {'Network','Target','TimeS','Distance', ...
                'StateErrorFraction','ProspectiveError', ...
                'ProspectiveErrorFraction'});
            extendedTimecourse = [extendedTimecourse; timeRow]; %#ok<AGROW>
        end
        fprintf('Diagnostic network %02d complete; k95=%d.\n', network, k95);
    end

    assert(height(stability) == 80 && height(potency) == 80);
    assert(height(extendedSummary) == 4);
    failedPotency = innerjoin(array2table(cfg.conditional.failedRows, ...
        'VariableNames', {'Network','Target'}), potency, ...
        'Keys', {'Network','Target'});
    stabilityPass = all(stability.Pass);
    extendedPass = all(extendedSummary.Pass);
    potencyPass = all(failedPotency.LowPotencyEuclideanFraction ...
        > cfg.conditional.minimumLowPotencyEuclideanFraction) ...
        && all(failedPotency.ProspectiveErrorFraction ...
            <= cfg.acceptance.maximumLongProspectiveErrorFraction);
    historicalTargetAudit.HistoricalPass = historicalTargetAudit.Pass;
    historicalTargetAudit.HistoricalFullStatePass = ...
        historicalTargetAudit.LongStateErrorFraction ...
        <= cfg.acceptance.maximumLongStateErrorFraction;
    historicalTargetAudit.HistoricalEndpoint1mmPass = ...
        historicalTargetAudit.LongEndpointErrorM ...
        <= cfg.acceptance.maximumLongEndpointErrorM;
    historicalTargetAudit.RevisedEndpoint2mmPass = ...
        historicalTargetAudit.LongEndpointErrorM ...
        <= cfg.conditional.maximumEndpointErrorM;
    historicalTargetAudit.LocalStabilityPass = stability.Pass;
    historicalTargetAudit.MechanisticGatePass = ...
        historicalTargetAudit.FixedPointResidualNorm ...
            <= cfg.acceptance.fixedPointResidualTolerance ...
        & historicalTargetAudit.LongProspectiveErrorFraction ...
            <= cfg.acceptance.maximumLongProspectiveErrorFraction ...
        & historicalTargetAudit.LongHandTrajectoryNRMSE ...
            <= cfg.acceptance.maximumLongHandNrmse ...
        & historicalTargetAudit.LongTorqueNRMSE ...
            <= cfg.acceptance.maximumLongTorqueNrmse;
    historicalTargetAudit.Pass = historicalTargetAudit.MechanisticGatePass ...
        & historicalTargetAudit.RevisedEndpoint2mmPass ...
        & historicalTargetAudit.LocalStabilityPass;
    for row = 1:height(cfg.conditional.failedRows)
        network = cfg.conditional.failedRows(row, 1);
        target = cfg.conditional.failedRows(row, 2);
        targetRow = historicalTargetAudit.Network == network ...
            & historicalTargetAudit.Target == target;
        diagnosticPass = extendedSummary.Pass(row) ...
            && failedPotency.LowPotencyEuclideanFraction(row) ...
                > cfg.conditional.minimumLowPotencyEuclideanFraction;
        historicalTargetAudit.Pass(targetRow) = ...
            historicalTargetAudit.Pass(targetRow) && diagnosticPass;
    end
    existingHardGatePass = all(historicalTargetAudit.MechanisticGatePass) ...
        && all(historicalNetworkAudit.GoContinuityMaximum ...
            <= cfg.acceptance.goContinuityTolerance) ...
        && all(historicalNetworkAudit.NonfiniteCount == 0);
    revisedEndpointPass = all(historicalTargetAudit.RevisedEndpoint2mmPass);
    conditionalAccepted = stabilityPass && extendedPass && potencyPass ...
        && existingHardGatePass && revisedEndpointPass ...
        && all(historicalTargetAudit.Pass);

    historicalNetworkAudit.HistoricalPass = historicalNetworkAudit.Pass;
    historicalNetworkAudit.HistoricalFullStatePass = ...
        historicalNetworkAudit.MaximumLongStateErrorFraction ...
        <= cfg.acceptance.maximumLongStateErrorFraction;
    historicalNetworkAudit.HistoricalEndpoint1mmPass = ...
        historicalNetworkAudit.MaximumLongEndpointErrorM ...
        <= cfg.acceptance.maximumLongEndpointErrorM;
    historicalNetworkAudit.RevisedEndpoint2mmPass = ...
        historicalNetworkAudit.MaximumLongEndpointErrorM ...
        <= cfg.conditional.maximumEndpointErrorM;
    historicalNetworkAudit.Pass = false(height(historicalNetworkAudit), 1);
    for network = 1:cfg.ensemble.count
        historicalNetworkAudit.Pass(network) = all( ...
            historicalTargetAudit.Pass( ...
                historicalTargetAudit.Network == network));
    end
    writetable(stability, fullfile(diagnosticRoot, ...
        'fixed_point_jacobian_stability.csv'));
    writetable(potency, fullfile(diagnosticRoot, ...
        'q_potency_residual_decomposition.csv'));
    writetable(extendedSummary, fullfile(diagnosticRoot, ...
        'extended_convergence_summary.csv'));
    writetable(extendedTimecourse, fullfile(diagnosticRoot, ...
        'extended_convergence_timecourses.csv'));
    writetable(historicalNetworkAudit, fullfile(cfg.workAuditRoot, ...
        'stage2a_network_audit.csv'));
    writetable(historicalTargetAudit, fullfile(cfg.workAuditRoot, ...
        'stage2a_target_audit.csv'));

    stage1After = capture_stage2a_frozen_hashes(cfg, "stage1", "after");
    stage2bAfter = capture_stage2a_frozen_hashes(cfg, "stage2b", "after");
    stage1Unchanged = isequal(stage1Before, stage1After);
    stage2bUnchanged = isequal(stage2bBefore, stage2bAfter);
    assert(stage1Unchanged && stage2bUnchanged);
    report = struct('status', ...
        'GATE 2 CONDITIONAL DIAGNOSTIC COMPLETE', ...
        'conditionalAccepted', conditionalAccepted, ...
        'stabilityPass', stabilityPass, 'extendedConvergencePass', ...
        extendedPass, 'lowPotencyResidualPass', potencyPass, ...
        'existingHardGatesPass', existingHardGatePass, ...
        'revisedEndpoint2mmPass', revisedEndpointPass, ...
        'stableTargetCount', sum(stability.Pass), ...
        'targetCount', height(stability), ...
        'minimumStabilityMarginPerS', min(stability.StabilityMarginPerS), ...
        'maximumFixedPointResidual', max(stability.FixedPointResidualNorm), ...
        'minimumFailedLowPotencyEuclideanFraction', ...
            min(failedPotency.LowPotencyEuclideanFraction), ...
        'maximumFailedHighPotencyEuclideanFraction', ...
            max(failedPotency.HighPotencyEuclideanFraction), ...
        'maximumFailedProspectiveErrorFraction', ...
            max(failedPotency.ProspectiveErrorFraction), ...
        'maximumStateErrorFraction20S', ...
            max(extendedSummary.StateErrorFraction20S), ...
        'maximumTwentyToFiveStateRatio', ...
            max(extendedSummary.TwentyToFiveStateRatio), ...
        'maximumLogDistanceSlope10To20PerS', ...
            max(extendedSummary.LogDistanceSlope10To20PerS), ...
        'revisedEndpointThresholdM', ...
            cfg.conditional.maximumEndpointErrorM, ...
        'stage1ArtifactsUnchanged', stage1Unchanged, ...
        'stage1FileCount', height(stage1After), ...
        'stage2bArtifactsUnchanged', stage2bUnchanged, ...
        'stage2bFileCount', height(stage2bAfter), ...
        'runtimeSeconds', toc(startTime), 'stage2bExecuted', false);
    write_json(fullfile(cfg.workAuditRoot, ...
        'stage2a_conditional_diagnostic_report.json'), report);
end

function preserve_initial_stop(cfg)
    historyRoot = fullfile(cfg.workRoot, 'audit_history', ...
        'gate2_initial_stop');
    if isfolder(historyRoot)
        return
    end
    mkdir(historyRoot);
    auditFiles = {'stage2a_network_audit.csv', ...
        'stage2a_target_audit.csv', 'stage2a_failure_reasons.csv', ...
        'gate2_failure_diagnostic_manifest.csv', ...
        'gate2_failure_verification.json', ...
        'stage1_frozen_hashes_before.csv', ...
        'stage1_frozen_hashes_after.csv', ...
        'stage2b_frozen_hashes_before.csv', ...
        'stage2b_frozen_hashes_after.csv'};
    for index = 1:numel(auditFiles)
        source = fullfile(cfg.workAuditRoot, auditFiles{index});
        if isfile(source)
            copyfile(source, fullfile(historyRoot, auditFiles{index}));
        end
    end
    copyfile(fullfile(cfg.workResultsRoot, 'stage2a_summary.json'), ...
        fullfile(historyRoot, 'stage2a_summary.json'));
    movable = {'stage2a_failure_reasons.csv', ...
        'gate2_failure_diagnostic_manifest.csv', ...
        'gate2_failure_verification.json'};
    for index = 1:numel(movable)
        source = fullfile(cfg.workAuditRoot, movable{index});
        if isfile(source)
            movefile(source, fullfile(historyRoot, movable{index}));
        end
    end
end

function write_json(path, value)
    fid = fopen(path, 'w');
    assert(fid ~= -1);
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(value, PrettyPrint=true));
end
