function report = run_stage2a_smoke_tests(cfg, model, tonicInput, ...
        fixedPointResidual, preparation, analysis)
    initialMismatch = max(abs(preparation.initialState ...
        - repmat(model.spontaneous, 1, model.nMovements)), [], 'all');
    maximumResidual = max(vecnorm(fixedPointResidual, 2, 1));
    longStateError = max(analysis.validation.LongStateErrorFraction);
    longProspectiveError = max(analysis.validation.LongProspectiveErrorFraction);
    longEndpointErrorM = max(analysis.validation.LongEndpointErrorM);
    longHandNrmse = max(analysis.validation.LongHandTrajectoryNRMSE);
    longTorqueNrmse = max(analysis.validation.LongTorqueNRMSE);
    correctInputSize = isequal(size(tonicInput), ...
        [model.n, model.nMovements]);
    passed = correctInputSize && initialMismatch == 0 ...
        && maximumResidual <= cfg.acceptance.fixedPointResidualTolerance ...
        && analysis.goContinuityMaximum ...
            <= cfg.acceptance.goContinuityTolerance ...
        && analysis.nonfiniteCount == 0 ...
        && longStateError <= cfg.acceptance.maximumLongStateErrorFraction ...
        && longProspectiveError ...
            <= cfg.acceptance.maximumLongProspectiveErrorFraction ...
        && longEndpointErrorM <= cfg.acceptance.maximumLongEndpointErrorM ...
        && longHandNrmse <= cfg.acceptance.maximumLongHandNrmse ...
        && longTorqueNrmse <= cfg.acceptance.maximumLongTorqueNrmse;
    report = struct('passed', passed, ...
        'correctInputSize', correctInputSize, ...
        'initialStateMismatch', initialMismatch, ...
        'maximumFixedPointResidual', maximumResidual, ...
        'goContinuityMaximum', analysis.goContinuityMaximum, ...
        'nonfiniteCount', analysis.nonfiniteCount, ...
        'maximumLongStateErrorFraction', longStateError, ...
        'maximumLongProspectiveErrorFraction', longProspectiveError, ...
        'maximumLongEndpointErrorM', longEndpointErrorM, ...
        'maximumLongHandNrmse', longHandNrmse, ...
        'maximumLongTorqueNrmse', longTorqueNrmse);
end
