function ensemble = summarize_stage2a_ensemble(cfg, networkAudit, ...
        targetAudit, movementMetrics, stateByNetwork, prospectiveByNetwork, ...
        endpointByNetwork, handByNetwork, torqueByNetwork)
    assert(height(networkAudit) == cfg.ensemble.count);
    assert(height(targetAudit) == cfg.ensemble.count * 8);
    durations = cfg.preparation.metricDurationsS;
    assert(isequal(size(stateByNetwork), ...
        [numel(durations), cfg.ensemble.count]));
    timeValues = {stateByNetwork.', prospectiveByNetwork.'};
    timeNames = {'StateErrorFraction', 'ProspectiveErrorFraction'};
    timeTable = table(durations, 'VariableNames', {'PreparationDurationS'});
    for metric = 1:numel(timeValues)
        statistics = bootstrap_network_median(timeValues{metric}, ...
            cfg.ensemble.bootstrapSamples, ...
            cfg.ensemble.bootstrapSeed + metric - 1);
        name = timeNames{metric};
        timeTable.([name 'Median']) = statistics.median.';
        timeTable.([name 'BootstrapSE']) = statistics.standardError.';
        timeTable.([name 'Minimum']) = statistics.minimum.';
        timeTable.([name 'Maximum']) = statistics.maximum.';
    end
    movementValues = {endpointByNetwork.', handByNetwork.', torqueByNetwork.'};
    movementNames = {'EndpointErrorM', 'HandTrajectoryNRMSE', 'TorqueNRMSE'};
    movementTable = table(durations, 'VariableNames', ...
        {'PreparationDurationS'});
    for metric = 1:numel(movementValues)
        statistics = bootstrap_network_median(movementValues{metric}, ...
            cfg.ensemble.bootstrapSamples, ...
            cfg.ensemble.bootstrapSeed + 10 + metric - 1);
        name = movementNames{metric};
        movementTable.([name 'Median']) = statistics.median.';
        movementTable.([name 'BootstrapSE']) = statistics.standardError.';
        movementTable.([name 'Minimum']) = statistics.minimum.';
        movementTable.([name 'Maximum']) = statistics.maximum.';
    end
    networkMetricNames = {'MaximumFixedPointResidual', ...
        'MaximumLongStateErrorFraction', ...
        'MaximumLongProspectiveErrorFraction', ...
        'MaximumLongEndpointErrorM', 'MaximumLongHandNRMSE', ...
        'MaximumLongTorqueNRMSE', 'ProspectiveMovementLogCorrelation'};
    distributionRows = cell(numel(networkMetricNames), 7);
    for metric = 1:numel(networkMetricNames)
        name = networkMetricNames{metric};
        values = networkAudit.(name);
        statistics = bootstrap_network_median(values, ...
            cfg.ensemble.bootstrapSamples, ...
            cfg.ensemble.bootstrapSeed + 100 + metric - 1);
        distributionRows(metric, :) = {name, statistics.median, ...
            statistics.standardError, statistics.lower95, statistics.upper95, ...
            statistics.minimum, statistics.maximum};
    end
    distributionTable = cell2table(distributionRows, 'VariableNames', ...
        {'Metric','NetworkMedian','BootstrapSE','BootstrapLower95', ...
        'BootstrapUpper95','Minimum','Maximum'});
    ensemble.networkAudit = networkAudit;
    ensemble.targetAudit = targetAudit;
    ensemble.movementMetrics = movementMetrics;
    ensemble.timecourse = timeTable;
    ensemble.movementSummary = movementTable;
    ensemble.networkDistributions = distributionTable;
    ensemble.stateByNetwork = stateByNetwork;
    ensemble.prospectiveByNetwork = prospectiveByNetwork;
    ensemble.endpointByNetwork = endpointByNetwork;
    ensemble.handByNetwork = handByNetwork;
    ensemble.torqueByNetwork = torqueByNetwork;
    ensemble.bootstrap = struct('samples', cfg.ensemble.bootstrapSamples, ...
        'seed', cfg.ensemble.bootstrapSeed, ...
        'method', cfg.ensemble.bootstrapMethod, ...
        'unit', 'network', ...
        'targetAggregation', ...
            'median across eight targets within network before network bootstrap');
end
