function report = validate_stage2a_ensemble_components(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src', 'stage_2a'));
    addpath(fullfile(projectRoot, 'analysis', 'stage_2a'));
    cfg = stage_2a_config(projectRoot);
    first = load(fullfile(cfg.ensemble.stage1Root, 'network_01.mat'), ...
        'model', 'networkRow');
    second = load(fullfile(cfg.ensemble.stage1Root, 'network_02.mat'), ...
        'model', 'networkRow');
    assert(norm(first.model.W - second.model.W, 'fro') > 0, ...
        'The first two accepted recurrent matrices are not independent.');
    [tonicFirst, residualFirst] = compute_tonic_input(first.model);
    [tonicSecond, residualSecond] = compute_tonic_input(second.model);
    assert(max(abs(residualFirst), [], 'all') == 0);
    assert(max(abs(residualSecond), [], 'all') == 0);
    assert(norm(tonicFirst - tonicSecond, 'fro') > 0, ...
        'Network-specific analytical tonic inputs unexpectedly match.');
    shortFirst = simulate_naive_preparation(first.model, tonicFirst, 0.01);
    shortSecond = simulate_naive_preparation(second.model, tonicSecond, 0.01);
    initialFirst = repmat(first.model.spontaneous, 1, first.model.nMovements);
    initialSecond = repmat(second.model.spontaneous, 1, second.model.nMovements);
    assert(max(abs(shortFirst.initialState - initialFirst), [], 'all') == 0);
    assert(max(abs(shortSecond.initialState - initialSecond), [], 'all') == 0);
    testValues = (1:10).';
    bootstrapA = bootstrap_network_median(testValues, 1000, ...
        cfg.ensemble.bootstrapSeed);
    bootstrapB = bootstrap_network_median(testValues, 1000, ...
        cfg.ensemble.bootstrapSeed);
    assert(isequaln(bootstrapA, bootstrapB), ...
        'Network bootstrap is not deterministic.');
    report = struct('passed', true, ...
        'networkOneRecurrentSeed', double(first.networkRow.RecurrentSeed), ...
        'networkTwoRecurrentSeed', double(second.networkRow.RecurrentSeed), ...
        'recurrentDifferenceFrobenius', ...
            norm(first.model.W - second.model.W, 'fro'), ...
        'networkOneMaximumFixedPointResidual', ...
            max(vecnorm(residualFirst, 2, 1)), ...
        'networkTwoMaximumFixedPointResidual', ...
            max(vecnorm(residualSecond, 2, 1)), ...
        'networkSpecificTonicDifferenceFrobenius', ...
            norm(tonicFirst - tonicSecond, 'fro'), ...
        'shortPreparationDurationS', 0.01, ...
        'bootstrapDeterministic', true);
    if ~isfolder(cfg.workAuditRoot)
        mkdir(cfg.workAuditRoot);
    end
    fid = fopen(fullfile(cfg.workAuditRoot, ...
        'stage2a_component_validation.json'), 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(report, PrettyPrint=true));
end
