function outcome = run_v2_workflow(projectRoot, executionBenchmark)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(mfilename('fullpath'));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src'));
    addpath(fullfile(projectRoot, 'analysis'));
    addpath(fullfile(projectRoot, 'figures'));
    params = resolve_output_paths(v2_model_params(), projectRoot);
    create_output_directories(params);
    fixed = load_hennequin_isn(params, projectRoot);
    initialModel = initialize_v2_model(params, fixed);
    if nargin < 2 || isempty(executionBenchmark)
        executionBenchmark = benchmark_v2_training(initialModel, params);
    end
    save(params.files.runtimeBenchmark, 'executionBenchmark', 'params');
    report_benchmark(executionBenchmark);
    if executionBenchmark.estimatedSecondsFor3000Updates > ...
            params.training.maximumEstimatedRuntimeSeconds
        error('V2Model:RuntimeGate', ...
            ['Estimated 3,000-update runtime is %.1f minutes, above ', ...
            'the configured 60-minute gate. Training was not started.'], ...
            executionBenchmark.estimatedSecondsFor3000Updates / 60);
    end

    [stageAModel, stageAHistory] = train_v2_stage(initialModel, params, ...
        'A', executionBenchmark.useAccelerated, fullfile( ...
        params.files.resultRoot, 'training_stageA_latest.mat'));
    stageAEvaluation = evaluate_v2_canonical(stageAModel, params, false, ...
        params.evaluation.deterministicTrialsPerTarget, ...
        params.seed.deterministicEvaluation);
    stageADelay = evaluate_v2_delay_robustness(stageAModel, params, ...
        false, params.evaluation.deterministicTrialsPerTarget, ...
        params.seed.delayEvaluation);
    stageAGate = deterministic_gate(stageAEvaluation.diagnostics.metrics, ...
        stageADelay, params);
    save(fullfile(params.files.resultRoot, 'checkpoint_stageA.mat'), ...
        'stageAModel', 'stageAHistory', 'stageAEvaluation', ...
        'stageADelay', 'stageAGate', 'params', '-v7.3');
    if ~stageAGate.allPassed
        error('V2Model:StageAFailed', ...
            ['Deterministic acquisition did not meet the frozen intact ', ...
            'criteria. No noisy training was started.']);
    end

    [learnedModel, stageBHistory] = train_v2_stage(stageAModel, params, ...
        'B', executionBenchmark.useAccelerated, fullfile( ...
        params.files.resultRoot, 'training_stageB_latest.mat'));
    deterministicEvaluation = evaluate_v2_canonical(learnedModel, ...
        params, false, params.evaluation.deterministicTrialsPerTarget, ...
        params.seed.deterministicEvaluation + 100);
    noisyEvaluation = evaluate_v2_canonical(learnedModel, params, true, ...
        params.evaluation.noisyTrialsPerTarget, params.seed.noisyEvaluation);
    delayRobustness.deterministic = evaluate_v2_delay_robustness( ...
        learnedModel, params, false, ...
        params.evaluation.deterministicTrialsPerTarget, ...
        params.seed.delayEvaluation);
    delayRobustness.noisy = evaluate_v2_delay_robustness(learnedModel, ...
        params, true, params.evaluation.noisyTrialsPerTarget, ...
        params.seed.delayEvaluation + 1000);
    validation = validate_v2_intact(deterministicEvaluation.diagnostics, ...
        noisyEvaluation.diagnostics, delayRobustness.deterministic, ...
        delayRobustness.noisy, params);
    trainingHistory.stageA = stageAHistory;
    trainingHistory.stageB = stageBHistory;
    trainingHistory.executionBenchmark = executionBenchmark;
    model = learnedModel;
    model.metadata = model_metadata(params, fixed, validation);
    numericalSummary = build_v2_numerical_summary(model, fixed, ...
        trainingHistory, deterministicEvaluation, noisyEvaluation, ...
        delayRobustness, validation, executionBenchmark, params);
    save(params.files.model, 'model', 'params', '-v7.3');
    save(params.files.trainingHistory, 'trainingHistory', 'params', '-v7.3');
    save(params.files.deterministicEvaluation, ...
        'deterministicEvaluation', 'params', '-v7.3');
    save(params.files.noisyEvaluation, 'noisyEvaluation', 'params', '-v7.3');
    save(params.files.delayEvaluation, 'delayRobustness', 'params', '-v7.3');
    save(params.files.numericalSummary, 'numericalSummary', 'params', '-v7.3');
    figureFiles = create_v2_diagnostic_plots(deterministicEvaluation, ...
        noisyEvaluation, delayRobustness, trainingHistory, params);
    print_summary(numericalSummary);
    outcome.completed = true;
    outcome.validation = validation;
    outcome.numericalSummary = numericalSummary;
    outcome.figureFiles = figureFiles;
    outcome.noLesionImplemented = true;
end

function params = resolve_output_paths(params, projectRoot)
    names = fieldnames(params.files);
    for index = 1:numel(names)
        name = names{index};
        if ~strcmp(name, 'isnMatrix')
            params.files.(name) = fullfile(projectRoot, params.files.(name));
        end
    end
end

function create_output_directories(params)
    directories = {params.files.resultRoot, params.files.figureRoot};
    for index = 1:numel(directories)
        if ~isfolder(directories{index})
            mkdir(directories{index});
        end
    end
end

function gate = deterministic_gate(metrics, delays, params)
    gate.meanEndpointPassed = metrics.meanEndpointErrorM <= ...
        params.validation.maxMeanEndpointErrorM && all( ...
        delays.meanEndpointErrorM <= params.validation.maxMeanEndpointErrorM);
    gate.worstTargetPassed = ...
        metrics.maximumTargetAveragedEndpointErrorM <= ...
        params.validation.maxTargetAveragedEndpointErrorM && all( ...
        delays.maximumTargetAveragedEndpointErrorM <= ...
        params.validation.maxTargetAveragedEndpointErrorM);
    gate.terminalSpeedPassed = metrics.meanTerminalSpeedMPerSec <= ...
        params.validation.maxTerminalSpeedMPerSec && all( ...
        delays.meanTerminalSpeedMPerSec <= ...
        params.validation.maxTerminalSpeedMPerSec);
    gate.preGoSpeedPassed = metrics.preGoRmsSpeedMPerSec <= ...
        params.validation.maxDeterministicPreGoRmsSpeedMPerSec && all( ...
        delays.preGoRmsSpeedMPerSec <= ...
        params.validation.maxDeterministicPreGoRmsSpeedMPerSec);
    gate.holdPassed = metrics.meanHoldErrorM <= ...
        params.validation.maxMeanHoldErrorM && ...
        metrics.meanHoldSpeedMPerSec <= ...
        params.validation.maxMeanHoldSpeedMPerSec && all( ...
        delays.meanHoldErrorM <= params.validation.maxMeanHoldErrorM) && ...
        all(delays.meanHoldSpeedMPerSec <= ...
        params.validation.maxMeanHoldSpeedMPerSec);
    gate.allTargetsPassed = metrics.allTargetsSuccessful;
    gate.finitePassed = metrics.finite;
    gate.allPassed = all(structfun(@(value) ...
        islogical(value) && value, gate));
end

function metadata = model_metadata(params, fixed, validation)
    metadata.projectVersion = params.project.version;
    metadata.trainedAt = char(datetime('now', 'TimeZone', 'local', ...
        'Format', 'yyyy-MM-dd HH:mm:ss Z'));
    metadata.intactOnly = true;
    metadata.noBiomechanicalPlant = true;
    metadata.output = 'linear cortical-rate readout [vx, vy]';
    metadata.positionUpdate = 'p(t+dt)=p(t)+dt*v(t)';
    metadata.fixedHennequinBackbone = true;
    metadata.fixedBaseline = true;
    metadata.trainableFields = v2_trainable_fields();
    metadata.targetInput = 'persistent 8-D one-hot identity';
    metadata.goInput = 'target-independent 75-ms cortical pulse';
    metadata.cerebellarInput = 'target identity only';
    metadata.cerebellarReceivesGo = false;
    metadata.cerebellarReceivesElapsedTime = false;
    metadata.cerebellarReceivesStateFeedback = false;
    metadata.cerebellarDynamics = ...
        'tau_cb*dc/dt=-c+c_target, c(0)=0, tau_cb=150 ms';
    metadata.WrecSourceSha256 = fixed.sourceSha256;
    metadata.WrecSourceCommit = fixed.sourceCommit;
    metadata.WrecSpectralAbscissa = fixed.spectralAbscissa;
    metadata.validation = validation;
end

function report_benchmark(benchmark)
    fprintf(['Runtime benchmark on %s: %.4f s/update; estimated ', ...
        '1,000 updates %.2f min, 3,000 updates %.2f min; ', ...
        'maximum observed GPU memory %.2f GiB.\n'], benchmark.gpuName, ...
        benchmark.secondsPerUpdate, ...
        benchmark.estimatedSecondsFor1000Updates / 60, ...
        benchmark.estimatedSecondsFor3000Updates / 60, ...
        benchmark.gpuMemoryUsedAfterUpdatesBytes / 1024^3);
end

function print_summary(summary)
    d = summary.deterministic;
    n = summary.noisy;
    fprintf(['Deterministic: endpoint %.3f mm, worst target %.3f mm, ', ...
        'terminal %.4f m/s, pre-go %.4f m/s, hold %.3f mm.\n'], ...
        1000 * d.meanEndpointErrorM, ...
        1000 * d.maximumTargetAveragedEndpointErrorM, ...
        d.meanTerminalSpeedMPerSec, d.preGoRmsSpeedMPerSec, ...
        1000 * d.meanHoldErrorM);
    fprintf(['Noisy: endpoint %.3f mm, worst target %.3f mm, ', ...
        'terminal %.4f m/s, pre-go %.4f m/s, hold %.3f mm.\n'], ...
        1000 * n.meanEndpointErrorM, ...
        1000 * n.maximumTargetAveragedEndpointErrorM, ...
        n.meanTerminalSpeedMPerSec, n.preGoRmsSpeedMPerSec, ...
        1000 * n.meanHoldErrorM);
    fprintf('All intact checks passed: %d. No lesion was run.\n', ...
        summary.validation.allPassed);
end
