clearvars;
close all;
clc;

projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'src', 'stage_2a'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'stage_2a'));
addpath(fullfile(projectRoot, 'figures'));
addpath(fullfile(projectRoot, 'figures', 'stage_2a'));
cfg = stage_2a_config(projectRoot);
requiredFolders = {cfg.workRoot, cfg.workResultsRoot, cfg.workAuditRoot, ...
    cfg.workEnsembleRoot, cfg.workPlotsPngRoot, cfg.workPlotsFigRoot};
for folder = 1:numel(requiredFolders)
    if ~isfolder(requiredFolders{folder})
        mkdir(requiredFolders{folder});
    end
end
fprintf('Gate 2 / Stage 2A: deterministic naive preparation across 10 networks.\n');
fprintf('No training, noise, controller, or Stage 2B computation.\n');
stage1Before = capture_stage2a_frozen_hashes(cfg, "stage1", "before");
stage2bBefore = capture_stage2a_frozen_hashes(cfg, "stage2b", "before");
acceptedAudit = readtable(fullfile(projectRoot, 'results', 'stage_1', ...
    'current', 'audit', 'accepted_ensemble_audit.csv'));
assert(height(acceptedAudit) == cfg.ensemble.count && all(acceptedAudit.Pass), ...
    'The frozen Stage-1 accepted audit is not 10/10 PASS.');

nNetworks = cfg.ensemble.count;
nTargets = 8;
nDurations = numel(cfg.preparation.metricDurationsS);
stateByNetwork = zeros(nDurations, nNetworks);
prospectiveByNetwork = zeros(nDurations, nNetworks);
endpointByNetwork = zeros(nDurations, nNetworks);
handByNetwork = zeros(nDurations, nNetworks);
torqueByNetwork = zeros(nDurations, nNetworks);
networkAudit = table();
targetAudit = table();
convergenceAudit = table();
movementMetrics = table();
representative = struct();
startTime = tic;

for network = 1:nNetworks
    networkPath = fullfile(cfg.ensemble.stage1Root, ...
        sprintf('network_%02d.mat', network));
    saved = load(networkPath, 'model', 'networkRow');
    model = saved.model;
    recurrentSeed = double(saved.networkRow.RecurrentSeed);
    calibrationSeed = double(saved.networkRow.CalibrationSeed);
    stage1Hash = sha256_file(networkPath);
    validate_frozen_stage1_member(model, saved.networkRow, network);
    idealCortex = simulate_published_cortex(model, model.xstar, true);
    [idealTheta, idealHand] = simulate_published_arm(model, idealCortex.torque);
    ideal = struct('cortex', idealCortex, 'theta', idealTheta, 'hand', idealHand);
    [tonicInput, fixedPointResidual] = compute_tonic_input(model);
    preparation = simulate_naive_preparation( ...
        model, tonicInput, cfg.preparation.maximumDurationS);
    analysis = analyze_stage2a(cfg, model, tonicInput, fixedPointResidual, ...
        preparation, ideal);
    smoke = run_stage2a_smoke_tests(cfg, model, tonicInput, ...
        fixedPointResidual, preparation, analysis);
    qResidual = model.A.' * model.Qnative + model.Qnative * model.A ...
        + model.C.' * model.C;
    qRelativeResidual = norm(qResidual, 'fro') ...
        / max(norm(model.C.' * model.C, 'fro'), eps);
    networkRow = table(network, recurrentSeed, calibrationSeed, stage1Hash, ...
        smoke.initialStateMismatch, smoke.maximumFixedPointResidual, ...
        smoke.goContinuityMaximum, smoke.nonfiniteCount, ...
        smoke.maximumLongStateErrorFraction, ...
        smoke.maximumLongProspectiveErrorFraction, ...
        smoke.maximumLongEndpointErrorM, smoke.maximumLongHandNrmse, ...
        smoke.maximumLongTorqueNrmse, ...
        analysis.prospectiveMovementLogCorrelation, qRelativeResidual, ...
        smoke.passed, 'VariableNames', {'Network','RecurrentSeed', ...
        'CalibrationSeed','Stage1FileSha256','InitialStateMismatch', ...
        'MaximumFixedPointResidual','GoContinuityMaximum','NonfiniteCount', ...
        'MaximumLongStateErrorFraction', ...
        'MaximumLongProspectiveErrorFraction','MaximumLongEndpointErrorM', ...
        'MaximumLongHandNRMSE','MaximumLongTorqueNRMSE', ...
        'ProspectiveMovementLogCorrelation','QRelativeResidual','Pass'});
    networkAudit = [networkAudit; networkRow]; %#ok<AGROW>
    currentTarget = analysis.validation;
    currentTarget.Network = repmat(network, height(currentTarget), 1);
    currentTarget.RecurrentSeed = repmat(recurrentSeed, height(currentTarget), 1);
    currentTarget.CalibrationSeed = repmat( ...
        calibrationSeed, height(currentTarget), 1);
    currentTarget = movevars(currentTarget, ...
        {'Network','RecurrentSeed','CalibrationSeed'}, 'Before', 'Target');
    currentTarget.Pass = currentTarget.FixedPointResidualNorm ...
        <= cfg.acceptance.fixedPointResidualTolerance ...
        & currentTarget.LongStateErrorFraction ...
        <= cfg.acceptance.maximumLongStateErrorFraction ...
        & currentTarget.LongProspectiveErrorFraction ...
        <= cfg.acceptance.maximumLongProspectiveErrorFraction ...
        & currentTarget.LongEndpointErrorM ...
        <= cfg.acceptance.maximumLongEndpointErrorM ...
        & currentTarget.LongHandTrajectoryNRMSE ...
        <= cfg.acceptance.maximumLongHandNrmse ...
        & currentTarget.LongTorqueNRMSE ...
        <= cfg.acceptance.maximumLongTorqueNrmse;
    targetAudit = [targetAudit; currentTarget]; %#ok<AGROW>
    currentConvergence = analysis.convergence;
    currentConvergence.Network = repmat(network, height(currentConvergence), 1);
    currentConvergence = movevars(currentConvergence, 'Network', ...
        'Before', 'Target');
    convergenceAudit = [convergenceAudit; currentConvergence]; %#ok<AGROW>
    currentMovement = analysis.movement.metrics;
    currentMovement.Network = repmat(network, height(currentMovement), 1);
    currentMovement = movevars(currentMovement, 'Network', 'Before', 'Target');
    movementMetrics = [movementMetrics; currentMovement]; %#ok<AGROW>
    denseIndices = round(cfg.preparation.metricDurationsS ...
        / model.samplingDt) + 1;
    stateByNetwork(:, network) = median( ...
        analysis.preparation.normalizedStateError(denseIndices, :), 2);
    prospectiveByNetwork(:, network) = median( ...
        analysis.preparation.normalizedProspectiveError(denseIndices, :), 2);
    endpointByNetwork(:, network) = median(reshape( ...
        currentMovement.EndpointErrorM, nTargets, nDurations), 1).';
    handByNetwork(:, network) = median(reshape( ...
        currentMovement.HandTrajectoryNRMSE, nTargets, nDurations), 1).';
    torqueByNetwork(:, network) = median(reshape( ...
        currentMovement.TorqueNRMSE, nTargets, nDurations), 1).';
    networkResult = struct('network', network, ...
        'recurrentSeed', recurrentSeed, 'calibrationSeed', calibrationSeed, ...
        'stage1FileSha256', stage1Hash, 'tonicInput', tonicInput, ...
        'fixedPointResidual', fixedPointResidual, ...
        'preparationTimesS', preparation.timesS, ...
        'normalizedStateError', analysis.preparation.normalizedStateError, ...
        'normalizedProspectiveError', ...
            analysis.preparation.normalizedProspectiveError, ...
        'validation', currentTarget, 'convergence', currentConvergence, ...
        'movementMetrics', currentMovement, 'smoke', smoke, ...
        'qRelativeResidual', qRelativeResidual);
    save(fullfile(cfg.workEnsembleRoot, ...
        sprintf('network_%02d_stage2a.mat', network)), ...
        'networkResult', '-v7.3');
    if network == cfg.ensemble.representativeIndex
        representative = struct('index', network, 'model', model, ...
            'tonicInput', tonicInput, 'fixedPointResidual', ...
            fixedPointResidual, 'preparation', preparation, 'ideal', ideal, ...
            'analysis', analysis, 'smoke', smoke);
    end
    if smoke.passed
        auditStatus = 'PASS';
    else
        auditStatus = 'FAIL';
    end
    fprintf(['Network %02d %s: fixed %.3e; 5-s state %.3e; ' ...
        'prospective %.3e; endpoint %.3e m.\n'], network, auditStatus, ...
        smoke.maximumFixedPointResidual, ...
        smoke.maximumLongStateErrorFraction, ...
        smoke.maximumLongProspectiveErrorFraction, ...
        smoke.maximumLongEndpointErrorM);
    clear model idealCortex idealTheta idealHand ideal tonicInput ...
        fixedPointResidual preparation analysis smoke networkResult
end

ensemble = summarize_stage2a_ensemble(cfg, networkAudit, targetAudit, ...
    movementMetrics, stateByNetwork, prospectiveByNetwork, ...
    endpointByNetwork, handByNetwork, torqueByNetwork);
writetable(networkAudit, fullfile(cfg.workAuditRoot, ...
    'stage2a_network_audit.csv'));
writetable(targetAudit, fullfile(cfg.workAuditRoot, ...
    'stage2a_target_audit.csv'));
writetable(convergenceAudit, fullfile(cfg.workResultsRoot, ...
    'prospective_error_reduction_times.csv'));
writetable(movementMetrics, fullfile(cfg.workResultsRoot, ...
    'movement_metrics_by_preparation_duration.csv'));
writetable(ensemble.timecourse, fullfile(cfg.workResultsRoot, ...
    'ensemble_preparation_timecourse_summary.csv'));
writetable(ensemble.movementSummary, fullfile(cfg.workResultsRoot, ...
    'ensemble_movement_summary.csv'));
writetable(ensemble.networkDistributions, fullfile(cfg.workResultsRoot, ...
    'ensemble_network_distributions.csv'));
write_json(fullfile(cfg.workAuditRoot, 'bootstrap_method.json'), ...
    ensemble.bootstrap);

stage1After = capture_stage2a_frozen_hashes(cfg, "stage1", "after");
stage2bAfter = capture_stage2a_frozen_hashes(cfg, "stage2b", "after");
stage1Unchanged = isequal(stage1Before, stage1After);
stage2bUnchanged = isequal(stage2bBefore, stage2bAfter);
assert(stage1Unchanged, 'A frozen Stage-1 artifact changed during Stage 2A.');
assert(stage2bUnchanged, 'A frozen Stage-2B artifact changed during Stage 2A.');
runtimeSeconds = toc(startTime);
allNetworksPassed = height(networkAudit) ...
    == cfg.acceptance.requiredNetworkCount && all(networkAudit.Pass);
allTargetRowsPassed = height(targetAudit) ...
    == cfg.acceptance.requiredTargetRows && all(targetAudit.Pass);
if allNetworksPassed && allTargetRowsPassed
    runStatus = cfg.acceptance.status;
else
    runStatus = 'GATE 2 STOPPED — STAGE 2A VALIDATION FAILURE';
end
summary = struct('status', runStatus, ...
    'networkCount', nNetworks, 'targetRows', height(targetAudit), ...
    'representativeNetwork', cfg.ensemble.representativeIndex, ...
    'allNetworksPassed', allNetworksPassed, ...
    'allTargetRowsPassed', allTargetRowsPassed, ...
    'maximumFixedPointResidual', ...
        max(networkAudit.MaximumFixedPointResidual), ...
    'maximumLongStateErrorFraction', ...
        max(networkAudit.MaximumLongStateErrorFraction), ...
    'maximumLongProspectiveErrorFraction', ...
        max(networkAudit.MaximumLongProspectiveErrorFraction), ...
    'maximumLongEndpointErrorM', ...
        max(networkAudit.MaximumLongEndpointErrorM), ...
    'maximumLongHandNRMSE', max(networkAudit.MaximumLongHandNRMSE), ...
    'maximumLongTorqueNRMSE', max(networkAudit.MaximumLongTorqueNRMSE), ...
    'networkMedianProspectiveMovementLogCorrelation', ...
        median(networkAudit.ProspectiveMovementLogCorrelation), ...
    'minimumProspectiveMovementLogCorrelation', ...
        min(networkAudit.ProspectiveMovementLogCorrelation), ...
    'maximumProspectiveMovementLogCorrelation', ...
        max(networkAudit.ProspectiveMovementLogCorrelation), ...
    'bootstrapSamples', cfg.ensemble.bootstrapSamples, ...
    'bootstrapSeed', cfg.ensemble.bootstrapSeed, ...
    'bootstrapUnit', 'network', 'stage1ArtifactsUnchanged', ...
        stage1Unchanged, 'stage1FileCount', height(stage1After), ...
    'stage2bArtifactsUnchanged', stage2bUnchanged, ...
    'stage2bFileCount', height(stage2bAfter), ...
    'runtimeSeconds', runtimeSeconds, 'training', 'none', ...
    'noise', 'none', 'stage2bExecuted', false);
write_json(fullfile(cfg.workResultsRoot, 'stage2a_summary.json'), summary);
inventory = cell(0, 2);
save(fullfile(cfg.workResultsRoot, 'stage2a_complete_results.mat'), ...
    'cfg', 'representative', 'ensemble', 'inventory', 'summary', '-v7.3');
diagnostic = run_stage2a_conditional_diagnostic(projectRoot);
assert(diagnostic.conditionalAccepted, ...
    ['Stage 2A failed the predeclared conditional-acceptance criteria. ' ...
    'Diagnostic audits were saved; canonical cleanup was not performed.']);
prepare_stage2a_conditional_acceptance(projectRoot);
fprintf('%s across %d/10 networks in %.1f s.\n', ...
    cfg.acceptance.status, nNetworks, runtimeSeconds);

function validate_frozen_stage1_member(model, networkRow, member)
    assert(networkRow.Pass && networkRow.AcceptedMember == member);
    assert(model.n == 200 && model.nE == 160 && model.nI == 40);
    assert(model.nMovements == 8 && rank(model.C) == 2);
    assert(model.dt == 2e-4 && model.samplingDt == 1e-3 ...
        && model.tau == 0.15);
    assert(all(model.W(:, 1:model.nE) >= 0, 'all'));
    assert(all(model.W(:, (model.nE + 1):end) <= 0, 'all'));
    assert(all(diag(model.W) == 0));
    assert(all(isfinite(model.W), 'all') && all(isfinite(model.C), 'all') ...
        && all(isfinite(model.xstar), 'all') ...
        && all(isfinite(model.Qnative), 'all'));
end

function write_json(path, value)
    fid = fopen(path, 'w');
    assert(fid ~= -1, 'Could not open %s for writing.', path);
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(value, PrettyPrint=true));
end
