clearvars;
close all;
clc;

projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
addpath(fullfile(projectRoot, 'figures'));
addpath(fullfile(projectRoot, 'figures', 'published_generator'));
cfg = stage_1_gate1_config(projectRoot);
require_kao_reference(cfg);
fprintf('Stage 1: accepted 10-cm QC-passing project ensemble.\n');
fprintf('This deterministic entry point performs no optimization or training.\n');
acceptedAuditPath = fullfile(cfg.gate1.auditRoot, ...
    'accepted_ensemble_audit.csv');
assert(isfile(acceptedAuditPath), 'Accepted Stage-1 ensemble audit is missing.');
acceptedAudit = readtable(acceptedAuditPath);
assert(height(acceptedAudit) == cfg.gate1.rejectionSampling.acceptedCount ...
    && all(acceptedAudit.Pass), 'The accepted Stage-1 audit is not 10/10 PASS.');
targetBundle = load(fullfile(cfg.gate1.targetRoot, ...
    'stage1_gate1_targets.mat'), 'target', 'targetTorques', 'summary');
assert(targetBundle.summary.allTargetsPassed ...
    && targetBundle.summary.targetRadiusM == cfg.gate1.radiusM, ...
    'The accepted 10-cm target bundle failed verification.');
saved = load(fullfile(cfg.gate1.ensembleRoot, 'network_01.mat'), ...
    'model', 'calibration', 'recurrent', 'networkRow');
model = saved.model;
assert(saved.networkRow.Pass && saved.networkRow.AcceptedMember == 1, ...
    'The canonical primary network is not accepted member 1.');
pinned = verify_pinned_reference(cfg);
assert(pinned.allMatched, 'Pinned Kao benchmark verification failed.');
startTime = tic;
baseline = simulate_published_cortex(model, model.xstar, true);
[theta, hand] = simulate_published_arm(model, baseline.torque);
analysis = analyze_published_generator(cfg, model, baseline, theta, hand);
inventory = create_stage1_figures(cfg, model, baseline, hand, analysis);
writetable(table(inventory(:, 1), inventory(:, 2), ...
    'VariableNames', {'FIG', 'PNG'}), ...
    fullfile(cfg.gate1.resultsRoot, 'plot_inventory.csv'));
runtimeSeconds = toc(startTime);
summary = struct('status', 'ACCEPTED — FROZEN', ...
    'modelType', 'first 10 QC-passing independent source-faithful ISNs', ...
    'targetRadiusM', cfg.gate1.radiusM, ...
    'targetAnglesDeg', cfg.gate1.targetAnglesDeg, ...
    'ensembleCount', height(acceptedAudit), ...
    'primaryMember', 1, ...
    'primaryRecurrentSeed', acceptedAudit.RecurrentSeed(1), ...
    'primaryCalibrationSeed', acceptedAudit.CalibrationSeed(1), ...
    'maximumEnsembleAngleErrorDeg', max(acceptedAudit.MaxAngleErrorDeg), ...
    'maximumEnsembleRadiusErrorM', max(acceptedAudit.MaxRadiusErrorM), ...
    'maximumEnsembleEndpointErrorM', max(acceptedAudit.MaxEndpointErrorM), ...
    'maximumEnsembleWeightedTorqueCost', ...
    max(acceptedAudit.WeightedTorqueCost), ...
    'potencyParticipationRatioPrimary', analysis.potency.participationRatio, ...
    'nonlinearPotencyRankCorrelationPrimary', ...
    analysis.perturbations.rankCorrelation, ...
    'endpointMappingR2Primary', analysis.mapping.endpointR2, ...
    'maximumTransientGainPrimary', analysis.stability.maximumTransientGain, ...
    'pinnedBenchmarkManifestEntries', pinned.manifestEntries, ...
    'pinnedBenchmarkAllMatched', pinned.allMatched, ...
    'runtimeSeconds', runtimeSeconds, 'stage2Executed', false);
save(fullfile(cfg.gate1.resultsRoot, 'stage1_primary_analysis.mat'), ...
    'cfg', 'model', 'baseline', 'theta', 'hand', 'analysis', ...
    'inventory', 'acceptedAudit', 'summary', '-v7.3');
fid = fopen(fullfile(cfg.gate1.resultsRoot, ...
    'stage1_primary_analysis_summary.json'), 'w');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(summary, PrettyPrint=true));
fprintf(['STAGE 1 ACCEPTED — FROZEN; primary member regenerated in %.1f s; ' ...
    'no optimization or Stage 2 execution.\n'], runtimeSeconds);
