function candidates = run_v2_stationarity_candidate_tests(projectRoot, weights)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(mfilename('fullpath'));
    end
    if nargin < 2 || isempty(weights)
        weights = 50;
    end
    if ~isscalar(weights)
        error('V2Model:CandidateProcessIsolation', ...
            ['Run one stationarity weight per fresh MATLAB process so ', ...
            'captured GPU data cannot outlive its accelerated closure.']);
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src'));
    addpath(fullfile(projectRoot, 'analysis'));
    params = v2_model_params();
    params.training.stageAMaxIterations = 1100;
    params.training.validationFrequency = 50;
    params.training.displayEvery = 50;
    params.training.checkpointFrequency = 250;
    resultRoot = fullfile(projectRoot, params.files.resultRoot);
    source = load(fullfile(resultRoot, ...
        'stage_a_checkpoint_latest.mat'), 'checkpoint');
    if source.checkpoint.iteration ~= 1000
        error('V2Model:CandidateSource', ...
            'Candidate tests require the preserved update-1000 checkpoint.');
    end
    candidates = repmat(struct(), 1, numel(weights));
    for candidateIndex = 1:numel(weights)
        weight = weights(candidateIndex);
        candidateParams = params;
        candidateParams.training.latePreGoVelocityLossWeight = weight;
        checkpointPath = fullfile(resultRoot, sprintf( ...
            'stationarity_candidate_weight_%03d_checkpoint.mat', weight));
        fprintf(['Launching stationarity candidate %d/%d: late-pre-go ', ...
            'weight %g, updates 1001-1100, deterministic only.\n'], ...
            candidateIndex, numel(weights), weight);
        [model, history] = train_v2_stage( ...
            source.checkpoint.currentModel, candidateParams, 'A', true, ...
            checkpointPath, source.checkpoint);
        evaluation = evaluate_v2_canonical(model, candidateParams, false, ...
            candidateParams.evaluation.deterministicTrialsPerTarget, ...
            candidateParams.seed.deterministicEvaluation);
        leakage = diagnose_v2_pre_go_leakage(model, candidateParams);
        metrics = evaluation.diagnostics.metrics;
        candidates(candidateIndex).weight = weight;
        candidates(candidateIndex).model = model;
        candidates(candidateIndex).history = history;
        candidates(candidateIndex).metrics = metrics;
        candidates(candidateIndex).leakage = leakage;
        fprintf(['Candidate weight %g best update %d | endpoint %.3f mm | ', ...
            'worst %.3f mm | terminal %.5f m/s | canonical pre-go %.5f ', ...
            '| delay-grid full %.5f final150 %.5f final100 %.5f ', ...
            'max %.5f m/s.\n'], weight, history.bestIteration, ...
            1000 * metrics.meanEndpointErrorM, ...
            1000 * metrics.maximumTargetAveragedEndpointErrorM, ...
            metrics.meanTerminalSpeedMPerSec, ...
            metrics.preGoRmsSpeedMPerSec, ...
            leakage.aggregate.fullRmsSpeedMPerSec, ...
            leakage.aggregate.final150RmsSpeedMPerSec, ...
            leakage.aggregate.final100RmsSpeedMPerSec, ...
            leakage.aggregate.maximumPreGoSpeedMPerSec);
        candidate = candidates(candidateIndex);
        save(fullfile(resultRoot, sprintf( ...
            'stationarity_candidate_weight_%03d_result.mat', weight)), ...
            'candidate', '-v7.3');
    end
    save(fullfile(resultRoot, 'stationarity_candidate_results.mat'), ...
        'candidates', 'weights', '-v7.3');
end
