function outcome = run_v2_stage_a_stationarity_refinement(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(mfilename('fullpath'));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src'));
    addpath(fullfile(projectRoot, 'analysis'));
    addpath(fullfile(projectRoot, 'figures'));
    params = v2_model_params();
    params.training.stageAMaxIterations = 1500;
    params.training.validationFrequency = 50;
    params.training.displayEvery = 50;
    params.training.checkpointFrequency = 250;
    params = resolve_output_paths(params, projectRoot);
    paths = refinement_paths(params);
    create_directories(params, paths);
    fixed = load_hennequin_isn(params, projectRoot);
    source = load(fullfile(params.files.resultRoot, ...
        'stage_a_checkpoint_latest.mat'), 'checkpoint');
    if source.checkpoint.iteration ~= 1000
        error('V2Model:RefinementSource', ...
            'Refinement requires the preserved update-1000 checkpoint.');
    end
    verify_refinement_batch(params);
    fprintf(['Launching deterministic Stage-A stationarity refinement ', ...
        'from update 1000 through at most update 1500; late-pre-go ', ...
        'weight %.1f; Stage B disabled.\n'], ...
        params.training.latePreGoVelocityLossWeight);
    [bestModel, history] = train_v2_stage( ...
        source.checkpoint.currentModel, params, 'A', true, ...
        paths.checkpoint, source.checkpoint);
    fprintf(['Refinement optimizer returned after %d additional updates ', ...
        '(absolute update %d) in %.2f min; best update %d.\n'], ...
        history.additionalUpdatesCompleted, history.updatesCompleted, ...
        history.elapsedSeconds / 60, history.bestIteration);

    evaluation = evaluate_v2_canonical(bestModel, params, false, ...
        params.evaluation.deterministicTrialsPerTarget, ...
        params.seed.deterministicEvaluation);
    delay = evaluate_v2_delay_robustness(bestModel, params, false, ...
        params.evaluation.deterministicTrialsPerTarget, ...
        params.seed.delayEvaluation);
    leakage = diagnose_v2_pre_go_leakage(bestModel, params);
    subspace = compute_v2_subspace_diagnostics(bestModel, ...
        evaluation.simulation, evaluation.task, params);
    validation = validate_v2_stage_a(evaluation.diagnostics, delay, params);
    trainingHistory.stageA = history;
    delayRobustness.deterministic = delay;
    figureFiles = create_v2_diagnostic_plots(evaluation, [], ...
        delayRobustness, trainingHistory, params);
    figureFiles = [figureFiles, plot_v2_subspace_diagnostics( ...
        subspace, evaluation, params)];
    summary = build_v2_stage_a_summary(bestModel, fixed, history, ...
        evaluation, delay, validation, figureFiles, paths, params);
    summary.scope = 'Stage A deterministic stationarity refinement only';
    summary.training.additionalUpdatesCompleted = ...
        history.additionalUpdatesCompleted;
    summary.stationarity.oldEquation = ...
        'mean_{trial,time<go}((vx^2+vy^2)/velocityScale^2)';
    summary.stationarity.oldWeight = params.training.preGoVelocityLossWeight;
    summary.stationarity.newEquation = [ ...
        'old term + mean_{trial,go-150ms<=time<go}', ...
        '((vx^2+vy^2)/velocityScale^2)'];
    summary.stationarity.lateWindowMs = ...
        params.training.latePreGoWindowMs;
    summary.stationarity.lateWeight = ...
        params.training.latePreGoVelocityLossWeight;
    summary.stationarity.maskBugFound = false;
    summary.stationarity.leakage = leakage;
    summary.subspace = subspace;
    model = bestModel;
    model.metadata.scope = summary.scope;
    model.metadata.bestIteration = history.bestIteration;
    model.metadata.bestValidationLoss = history.bestValidationLoss;
    model.metadata.fixedWrec = true;
    model.metadata.WrecSha256 = fixed.sourceSha256;
    model.metadata.stageBRun = false;
    model.metadata.lesionRun = false;
    save(paths.model, 'model', 'params', '-v7.3');
    save(paths.history, 'history', 'params', '-v7.3');
    save(paths.evaluation, 'evaluation', 'params', '-v7.3');
    save(paths.delay, 'delay', 'params', '-v7.3');
    save(paths.leakage, 'leakage', 'params');
    save(paths.subspace, 'subspace', 'params', '-v7.3');
    save(paths.summary, 'summary', 'params', '-v7.3');
    print_refinement_summary(summary);
    outcome.completed = true;
    outcome.summary = summary;
    outcome.validation = validation;
    outcome.figureFiles = figureFiles;
    outcome.stageBRun = false;
    outcome.lesionRun = false;
end

function params = resolve_output_paths(params, projectRoot)
    names = fieldnames(params.files);
    for nameIndex = 1:numel(names)
        name = names{nameIndex};
        if ~strcmp(name, 'isnMatrix')
            params.files.(name) = fullfile(projectRoot, params.files.(name));
        end
    end
end

function paths = refinement_paths(params)
    root = params.files.resultRoot;
    paths.checkpoint = fullfile(root, ...
        'stage_a_refinement_checkpoint_latest.mat');
    paths.model = fullfile(root, 'stage_a_refinement_best_model.mat');
    paths.history = fullfile(root, 'stage_a_refinement_training_history.mat');
    paths.evaluation = fullfile(root, ...
        'stage_a_refinement_deterministic_evaluation.mat');
    paths.delay = fullfile(root, ...
        'stage_a_refinement_delay_robustness.mat');
    paths.leakage = fullfile(root, ...
        'stage_a_refinement_pre_go_diagnosis.mat');
    paths.subspace = fullfile(root, ...
        'stage_a_refinement_subspace_diagnostics.mat');
    paths.summary = fullfile(root, ...
        'stage_a_refinement_numerical_summary.mat');
end

function create_directories(params, paths)
    directories = {params.files.resultRoot, params.files.figureRoot, ...
        fileparts(paths.checkpoint)};
    for directoryIndex = 1:numel(directories)
        if ~isfolder(directories{directoryIndex})
            mkdir(directories{directoryIndex});
        end
    end
end

function verify_refinement_batch(params)
    stream = RandStream('mt19937ar', 'Seed', ...
        params.seed.trainingTask + 8000);
    task = sample_balanced_v2_task(params, ...
        params.training.trialsPerTarget, stream);
    counts = accumarray(task.targetIndex(:), 1, ...
        [params.task.numTargets 1]);
    expectedTimeSteps = params.task.maximumTrialDurationMs / ...
        params.model.dtMs + 1;
    passed = task.numTrials == 64 && all(counts == 8) && ...
        task.numTimeSteps == expectedTimeSteps && ...
        isequal(size(task.preGoMask), [64 expectedTimeSteps]) && ...
        isequal(size(task.latePreGoMask), [64 expectedTimeSteps]);
    if ~passed
        error('V2Model:RefinementBatch', ...
            'Refinement batch/mask verification failed.');
    end
    fprintf(['Refinement batch verified once: 64 trials, 8/target, ', ...
        'fixed 261-step full and late-pre-go masks, no neural noise.\n']);
end

function print_refinement_summary(summary)
    metrics = summary.metrics;
    leakage = summary.stationarity.leakage.aggregate;
    subspace = summary.subspace;
    fprintf(['Best refined model: endpoint %.3f mm, worst %.3f mm, ', ...
        'terminal %.5f m/s, canonical pre-go %.5f m/s; delay-grid ', ...
        'full %.5f, final150 %.5f, final100 %.5f, max %.5f m/s.\n'], ...
        1000 * metrics.meanEndpointErrorM, ...
        1000 * metrics.maximumTargetAveragedEndpointErrorM, ...
        metrics.meanTerminalSpeedMPerSec, ...
        metrics.preGoRmsSpeedMPerSec, ...
        leakage.fullRmsSpeedMPerSec, ...
        leakage.final150RmsSpeedMPerSec, ...
        leakage.final100RmsSpeedMPerSec, ...
        leakage.maximumPreGoSpeedMPerSec);
    fprintf(['Subspaces: prep-by-move alignment %.4f, ', ...
        'move-by-prep %.4f, prep variance in Wout row space %.4f%%.\n'], ...
        subspace.alignment.preparatoryByMovement, ...
        subspace.alignment.movementByPreparatory, ...
        subspace.outputPotent.preparatoryVariancePercent);
    fprintf('All criteria passed %d. Stage B and lesion work were not run.\n', ...
        summary.validation.allPassed);
end
