clearvars;
close all;
clc;

projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'src', 'stage_2a'));
addpath(fullfile(projectRoot, 'src', 'stage_2b_kao'));
addpath(fullfile(projectRoot, 'src', 'stage_2b_cerebellum'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'stage_2b_shared'));
addpath(fullfile(projectRoot, 'figures', 'stage_2b_shared'));
cfg = stage_2b_cerebellum_config(projectRoot);
cfgKao = stage_2b_kao_config(projectRoot);
require_kao_reference(cfgKao.stage1);
if ~isfolder(cfg.resultsRoot), mkdir(cfg.resultsRoot); end
fprintf('Stage 2B-Cerebellum: fixed top-13-Q normative capacity bound\n');
fprintf('No training, tuning, biological pathway, or lesion simulation.\n');
startTime = tic;
kaoFile = fullfile(cfgKao.resultsRoot, 'stage2b_kao_controller.mat');
assert(isfile(kaoFile), 'Stage 2B-Kao must pass before Stage 2B-Cerebellum.');
savedKao = load(kaoFile, 'model', 'controller', 'validation', 'preparation');
assert(savedKao.validation.passed);
model = savedKao.model;
kao = savedKao.controller;
cerebellum = derive_stage2b_cerebellum_controller(model, cfg);
componentValidation = validate_stage2b_source_gate(cfg, model, cerebellum);
assert(componentValidation.passed);
fprintf(['Component gate PASS: potency %.6f; CARE %.3e; fixed point %.3e; ' ...
    'Jacobian %.3e.\n'], cerebellum.potencyFraction, ...
    cerebellum.careResidualRelative, max(cerebellum.fixedPointResidualNorm), ...
    componentValidation.maximumJacobianRelativeError);
results = run_stage2b_comparative_analysis(cfg, model, kao, cerebellum, ...
    savedKao.preparation);
runtimeScientificSeconds = toc(startTime);

controllerSummary = table(["Stage 2B-Kao"; "Stage 2B-Cerebellum"], ...
    [kao.stateDimension; cerebellum.stateDimension], ...
    [kao.inputDimension; cerebellum.inputDimension], ...
    [kao.lambda; cerebellum.lambda], [kao.qTrace; cerebellum.qTrace], ...
    [kao.careResidualRelative; cerebellum.careResidualRelative], ...
    [kao.gainFrobeniusNorm; cerebellum.gainFrobeniusNorm], ...
    [NaN; cerebellum.BOrthonormalResidual], [1; cerebellum.potencyFraction], ...
    [kao.stabilizable; cerebellum.stabilizable], ...
    'VariableNames', {'Controller','StateDimension','InputDimension','Lambda', ...
    'QTrace','CareResidualRelative','GainFrobeniusNorm', ...
    'BOrthonormalResidual','ActuatorPotencyFraction','Stabilizable'});

resultRoots = {cfgKao.resultsRoot, cfg.resultsRoot};
for rootIndex = 1:numel(resultRoots)
    root = resultRoots{rootIndex};
    if ~isfolder(root), mkdir(root); end
    writetable(controllerSummary, fullfile(root, 'controller_derivation_summary.csv'));
    writetable(results.validation, fullfile(root, 'controller_validation.csv'));
    writetable(results.local.targets, fullfile(root, 'local_stability.csv'));
    writetable(results.local.finiteTime, fullfile(root, 'finite_time_q_gain.csv'));
    writetable(results.movement, fullfile(root, 'movement_metrics_by_preparation_duration.csv'));
    writetable(results.effort, fullfile(root, 'control_effort.csv'));
    writetable(results.clouds, fullfile(root, 'nonlinear_cloud_trials.csv'));
    writetable(results.cloudSummary, fullfile(root, 'nonlinear_cloud_summary.csv'));
    writetable(results.perturbations, fullfile(root, 'midpreparation_perturbation_recovery.csv'));
    writetable(results.potency, fullfile(root, 'potency_band_recovery.csv'));
    writetable(results.alignment, fullfile(root, 'prep_move_alignment.csv'));
    writetable(results.alignmentNull, fullfile(root, 'prep_move_alignment_null_10000.csv'));
    writetable(results.amplification, fullfile(root, 'movement_amplification.csv'));
    writetable(results.rotation, fullfile(root, 'prep_move_rotation.csv'));
    writetable(results.flow.grid, fullfile(root, 'flow_field_q1_q2.csv'));
end

save(fullfile(cfg.resultsRoot, 'stage2b_cerebellum_complete_results.mat'), ...
    'cfg', 'cfgKao', 'model', 'kao', 'cerebellum', 'componentValidation', ...
    'controllerSummary', 'results', 'runtimeScientificSeconds', '-v7.3');
save(fullfile(cfgKao.resultsRoot, 'stage2b_kao_comparative_results.mat'), ...
    'cfgKao', 'kao', 'controllerSummary', 'results', ...
    'runtimeScientificSeconds', '-v7.3');

inventory = create_stage2b_comparative_figures(cfgKao, cfg, model, results);
inventoryTable = array2table(inventory, 'VariableNames', ...
    {'Basename','KaoFIG','KaoPNG','CerebellumFIG','CerebellumPNG'});
writetable(inventoryTable, fullfile(cfgKao.resultsRoot, 'plot_inventory.csv'));
writetable(inventoryTable, fullfile(cfg.resultsRoot, 'plot_inventory.csv'));

for rootIndex = 1:2
    plotCfg = {cfgKao, cfg}; plotCfg = plotCfg{rootIndex};
    png = dir(fullfile(plotCfg.plotsPngRoot, '*.png'));
    fig = dir(fullfile(plotCfg.plotsFigRoot, '*.fig'));
    assert(numel(png) == 10 && numel(fig) == 10);
    assert(isequal(sort(erase(string({png.name}), '.png')), ...
        sort(erase(string({fig.name}), '.fig'))));
    for index = 1:numel(fig)
        handle = openfig(fullfile(fig(index).folder, fig(index).name), ...
            'invisible');
        assert(isgraphics(handle)); close(handle);
    end
end

maximumSpectral = groupsummary(results.local.targets, 'Controller', 'max', ...
    'SpectralAbscissaPerS');
cloudMatched = results.cloudSummary(results.cloudSummary.SeedSet == "Matched", :);
cloudUntouched = results.cloudSummary(results.cloudSummary.SeedSet == "Untouched", :);
summary = struct('status', cfg.status, 'upstreamCommit', cfg.upstreamCommit, ...
    'scientificRuntimeSeconds', runtimeScientificSeconds, ...
    'kaoSourceGatePassed', savedKao.validation.passed, ...
    'cerebellumComponentGatePassed', componentValidation.passed, ...
    'lambda', cerebellum.lambda, 'actuatorDimension', cerebellum.inputDimension, ...
    'actuatorPotencyFraction', cerebellum.potencyFraction, ...
    'actuatorOrthonormalResidual', cerebellum.BOrthonormalResidual, ...
    'kaoCareResidual', kao.careResidualRelative, ...
    'cerebellumCareResidual', cerebellum.careResidualRelative, ...
    'maximumFixedPointResidual', max(results.validation.MaximumFixedPointResidual), ...
    'maximumJacobianFdRelativeError', ...
        max(results.validation.MaximumJacobianFdRelativeError), ...
    'maximumSpectralAbscissaByController', table2struct(maximumSpectral), ...
    'matchedCloudSummary', table2struct(cloudMatched), ...
    'untouchedCloudSummary', table2struct(cloudUntouched), ...
    'alignment', table2struct(results.alignment), ...
    'training', 'none', 'tuning', 'none', 'lesion', 'none');
for rootIndex = 1:numel(resultRoots)
    fid = fopen(fullfile(resultRoots{rootIndex}, 'stage2b_comparative_summary.json'), 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(summary, PrettyPrint=true));
    clear cleanup;
end
fprintf('COMPLETE in %.1f s scientific runtime; ten mirrored figure pairs generated.\n', ...
    runtimeScientificSeconds);
