function [loss, gradients, moveCost, regularization] = ...
        source_calibration_parameter_objective(parameters, constants)
    [xstars, readout, auxiliary] = source_calibration_unpack(parameters, ...
        constants.observabilityBasis, constants.spontaneous, ...
        constants.nE, constants.xstarStd);
    [loss, physicalGradient, moveCost, regularization] = ...
        source_calibration_objective_adjoint(xstars, readout, constants);
    gradients = source_calibration_unpack_vjp(parameters, auxiliary, ...
        physicalGradient, constants.observabilityBasis, constants.nE);
end
