function receipt = stage3_registry_receipt(cfg,registry)
    % Compact index; complete numerical definitions are retained in MAT.
    receipt=struct('completeDefinitionsFile','selected_solution_registry.mat', ...
        'completeDefinitionsSHA256',sha256_file(fullfile(cfg.resultsRoot,'selected_solution_registry.mat')), ...
        'primaryGridIndex',registry.primaryGridIndex,'frozenUTC',registry.frozenUTC, ...
        'movementInspectedAtSelection',registry.movementInspected,'primaryRule',registry.rule, ...
        'additionalRule',registry.additionalRule,'primary',{{}},'additional',{{}});
    for category={'primary','additional'}
        key=category{1}; defs=registry.(key);
        for j=1:numel(defs)
            d=defs{j};
            receipt.(key){j,1}=struct('network',d.member,'direction',d.direction,'gridIndex',d.gridIndex, ...
                'alpha',d.alpha,'betaNormalized',d.betaNormalized,'beta',d.beta,'kappa',d.kappa,'nu',d.nu, ...
                'stateDimensions',size(d.xB),'settledRank',numel(d.ell));
        end
    end
    stage3_write_json(fullfile(cfg.resultsRoot,'selected_solution_registry.json'),receipt);
end
