clearvars;
close all;
clc;

projectRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
cfg = stage_1_gate1_config(projectRoot);
assert(~isfile(fullfile(cfg.gate1.targetRoot, 'stage1_gate1_targets.mat')), ...
    'Accepted target bundle exists; construction must not overwrite frozen assets.');
if ~isfolder(cfg.gate1.targetRoot)
    mkdir(cfg.gate1.targetRoot);
end
if ~isfolder(cfg.gate1.auditRoot)
    mkdir(cfg.gate1.auditRoot);
end
fprintf('Gate 1 target layer only: eight 10-cm source-faithful targets.\n');
fprintf('No recurrent network or cortical calibration is invoked.\n');
startTime = tic;
pinnedBefore = verify_pinned_reference(cfg);
baseModel = load_published_generator(cfg);
target = source_target_hand_trajectories(cfg, baseModel.arm);
desiredAngles = mod(cfg.gate1.targetAnglesDeg(:), 360);
angleConstructionError = mod(target.endpointAngleDeg - desiredAngles + 180, 360) - 180;
assert(max(abs(angleConstructionError)) < 1e-10, ...
    'The constructed target directions do not match the authorized angles.');
assert(max(abs(target.endpointRadiusM - cfg.gate1.radiusM)) ...
    <= cfg.gate1.validation.targetRadiusToleranceM, ...
    'The constructed target radius is not 0.10 m within tolerance.');
[targetTorques, targetTorqueDiagnostics] = ...
    optimize_source_target_torques(cfg, target, baseModel.arm);
targetAudit = summarize_target_torque_benchmark( ...
    "MATLAB 10-cm project geometry", cfg.gate1.targetAnglesDeg, ...
    target.hands, targetTorques, targetTorqueDiagnostics, baseModel, ...
    cfg.gate1.validation.maxEndpointErrorM);
finiteMetrics = all(isfinite(targetAudit{:, [7:17, 19, 21]}), 'all');
optimizerClean = all(~contains(targetAudit.OptimizerStatus, ...
    ["nonfinite", "failed line search"], 'IgnoreCase', true));
allTargetsPass = all(targetAudit.ProjectEndpointGatePass) ...
    && finiteMetrics && optimizerClean;
assert(allTargetsPass, ...
    'The 10-cm target/torque layer failed; Gate 1 must stop before the ensemble.');
pinnedAfter = verify_pinned_reference(cfg);
assert(isequal(pinnedBefore, pinnedAfter), ...
    'Pinned Kao reference verification changed during target validation.');
runtimeSeconds = toc(startTime);
summary = struct('status', 'PASS', 'scope', '10-cm target/torque layer only', ...
    'sourceCommit', cfg.gate1.sourceCommit, ...
    'targetAnglesDeg', cfg.gate1.targetAnglesDeg, ...
    'targetRadiusM', cfg.gate1.radiusM, ...
    'targetCount', height(targetAudit), ...
    'allTargetsPassed', allTargetsPass, ...
    'maximumEndpointErrorM', max(targetAudit.EndpointErrorM), ...
    'maximumAbsoluteAngularErrorDeg', max(abs(targetAudit.AngularErrorDeg)), ...
    'maximumAbsoluteRadialErrorM', max(abs(targetAudit.RadialErrorM)), ...
    'maximumPositionTrajectoryRmseM', max(targetAudit.PositionTrajectoryRmseM), ...
    'maximumSourceObjective', max(targetAudit.SourceTotalObjective), ...
    'pinnedManifestEntries', pinnedAfter.manifestEntries, ...
    'pinnedManifestAllMatched', pinnedAfter.allMatched, ...
    'ensembleGenerated', false, ...
    'runtimeSeconds', runtimeSeconds);
writetable(targetAudit, fullfile(cfg.gate1.targetRoot, ...
    'target_torque_audit_by_target.csv'));
save(fullfile(cfg.gate1.targetRoot, 'stage1_gate1_targets.mat'), ...
    'cfg', 'target', 'targetTorques', 'targetTorqueDiagnostics', ...
    'targetAudit', 'summary', '-v7.3');
fid = fopen(fullfile(cfg.gate1.targetRoot, ...
    'target_torque_validation_summary.json'), 'w');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(summary, PrettyPrint=true));
clear cleanup;
manifest = hash_tree(projectRoot, "results/stage_1/current/targets");
manifest(endsWith(manifest.relative_path, ...
    'target_torque_validation_manifest.csv'), :) = [];
writetable(manifest, fullfile(cfg.gate1.targetRoot, ...
    'target_torque_validation_manifest.csv'));
fprintf('10-CM TARGET/TORQUE LAYER PASS in %.1f s; 8/8 targets passed.\n', ...
    runtimeSeconds);
