clearvars;
close all;
clc;

projectRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
addpath(fullfile(projectRoot, 'figures'));
addpath(fullfile(projectRoot, 'figures', 'published_generator'));
cfg = stage_1_gate1_config(projectRoot);
roots = {cfg.resultsRoot, cfg.gate1.resultsRoot, cfg.gate1.ensembleRoot, ...
    cfg.gate1.targetRoot, cfg.gate1.auditRoot, cfg.plotsPngRoot, cfg.plotsFigRoot};
for index = 1:numel(roots)
    if ~isfolder(roots{index})
        mkdir(roots{index});
    end
end
fprintf('Gate 1 / Stage 1 only: source-faithful target recalibration and 10-network audit.\n');
fprintf('No Stage 2A or Stage 2B code path is invoked.\n');
startTime = tic;
pinnedBefore = verify_pinned_reference(cfg);
stage2Roots = ["config/stage_2b_kao_config.m", ...
    "config/stage_2b_cerebellum_config.m", "src/stage_2a", ...
    "src/stage_2b_kao", "src/stage_2b_cerebellum", ...
    "analysis/stage_2a", "analysis/stage_2b_shared", ...
    "figures/stage_2a", "figures/stage_2b_shared", ...
    "results/stage_2a", "results/stage_2b_kao", ...
    "results/stage_2b_cerebellum", "plots/stage_2a", ...
    "plots/stage_2b_kao", "plots/stage_2b_cerebellum"];
stage2Before = hash_tree(projectRoot, stage2Roots);
writetable(stage2Before, fullfile(cfg.gate1.auditRoot, ...
    'stage2_frozen_hashes_before.csv'));
baseModel = load_published_generator(cfg);
targetBundlePath = fullfile(cfg.gate1.targetRoot, 'stage1_gate1_targets.mat');
assert(isfile(targetBundlePath), ...
    ['Run and pass workflows/stage_1/construction/' ...
    'run_stage_1_gate1_target_validation.m first.']);
targetBundle = load(targetBundlePath, 'cfg', 'target', 'targetTorques', ...
    'targetTorqueDiagnostics', 'targetAudit', 'summary');
assert(targetBundle.summary.allTargetsPassed ...
    && targetBundle.summary.targetRadiusM == cfg.gate1.radiusM ...
    && isequal(targetBundle.summary.targetAnglesDeg, cfg.gate1.targetAnglesDeg), ...
    'The saved target bundle does not match the authorized 10-cm geometry.');
target = targetBundle.target;
targetTorques = targetBundle.targetTorques;
targetTorqueDiagnostics = targetBundle.targetTorqueDiagnostics;
targetAudit = targetBundle.targetAudit;
desiredAngles = mod(cfg.gate1.targetAnglesDeg(:), 360);
angleError = mod(target.endpointAngleDeg - desiredAngles + 180, 360) - 180;
assert(max(abs(angleError)) < 1e-10, 'Target-direction construction failed.');
assert(max(abs(target.endpointRadiusM - cfg.gate1.radiusM)) ...
    <= cfg.gate1.validation.targetRadiusToleranceM, 'Target-radius construction failed.');
targetPathRmseM = max(targetAudit.PositionTrajectoryRmseM);
targetEndpointErrorM = max(targetAudit.EndpointErrorM);
fprintf('Verified 10-cm target bundle PASS; generating nine independent seeded recurrent substrates.\n');
recurrentMatrices = cell(cfg.gate1.networkCount, 1);
recurrentDiagnostics = cell(cfg.gate1.networkCount, 1);
recurrentMatrices{1} = baseModel.W;
recurrentDiagnostics{1} = struct('seed', NaN, 'iterations', NaN, ...
    'savedSpectralAbscissa', max(real(eig(baseModel.W))), ...
    'provenance', 'pinned released realization');
parfor member = 2:cfg.gate1.networkCount
    [recurrentMatrices{member}, recurrentDiagnostics{member}] = ...
        generate_source_faithful_recurrent(cfg, ...
        cfg.gate1.generatedNetworkSeeds(member - 1));
end
fprintf('Recurrent substrates complete; calibrating x* and C for all ten once.\n');
models = cell(cfg.gate1.networkCount, 1);
calibrationDiagnostics = cell(cfg.gate1.networkCount, 1);
spontaneousStates = cell(cfg.gate1.networkCount, 1);
spontaneousStates{1} = baseModel.spontaneous;
parfor member = 1:cfg.gate1.networkCount
    [models{member}, calibrationDiagnostics{member}] = ...
        calibrate_source_faithful_generator(cfg, recurrentMatrices{member}, ...
        spontaneousStates{member}, targetTorques, ...
        cfg.gate1.calibrationSeeds(member), baseModel);
end
for member = 1:cfg.gate1.networkCount
    model = models{member};
    model.targetHand = target.hands;
    model.targetTorque = targetTorques;
    models{member} = model;
    calibration = calibrationDiagnostics{member};
    recurrent = recurrentDiagnostics{member};
    save(fullfile(cfg.gate1.ensembleRoot, ...
        sprintf('network_%02d.mat', member)), 'model', 'calibration', ...
        'recurrent', '-v7.3');
end
[audit, targetNetworkAudit, model] = audit_stage1_gate1_ensemble(cfg, models, ...
    calibrationDiagnostics, recurrentDiagnostics, target, targetTorques);
writetable(audit, fullfile(cfg.gate1.auditRoot, 'network_audit.csv'));
writetable(targetNetworkAudit, fullfile(cfg.gate1.auditRoot, ...
    'network_target_audit.csv'));
assert(all(audit.pass), ...
    'Gate 1 ensemble validation failed; Stage 1 stops here.');
baseline = simulate_published_cortex(model, model.xstar, true);
[theta, hand] = simulate_published_arm(model, baseline.torque);
analysis = analyze_published_generator(cfg, model, baseline, theta, hand);
inventory = create_stage1_figures(cfg, model, baseline, hand, analysis);
writetable(table(inventory(:, 1), inventory(:, 2), ...
    'VariableNames', {'FIG', 'PNG'}), fullfile(cfg.resultsRoot, 'plot_inventory.csv'));
stage2After = hash_tree(projectRoot, stage2Roots);
writetable(stage2After, fullfile(cfg.gate1.auditRoot, ...
    'stage2_frozen_hashes_after.csv'));
stage2Unchanged = isequal(stage2Before, stage2After);
assert(stage2Unchanged, 'A frozen Stage 2 artifact changed during Gate 1.');
pinnedAfter = verify_pinned_reference(cfg);
assert(isequal(pinnedBefore, pinnedAfter), 'Pinned benchmark verification changed.');
runtimeSeconds = toc(startTime);
summary = struct('status', 'PASS', 'scope', cfg.gate1.status, ...
    'sourceCommit', cfg.gate1.sourceCommit, ...
    'targetAnglesDeg', cfg.gate1.targetAnglesDeg, ...
    'targetRadiusM', cfg.gate1.radiusM, 'networkCount', height(audit), ...
    'allNetworksPassed', all(audit.pass), ...
    'maximumAngleErrorDeg', max(audit.maxAngleErrorDeg), ...
    'maximumRadiusErrorM', max(audit.maxRadiusErrorM), ...
    'maximumEndpointErrorM', max(audit.maxEndpointErrorM), ...
    'maximumWeightedTorqueCost', max(audit.weightedTorqueCost), ...
    'targetPathRmseM', targetPathRmseM, ...
    'targetEndpointErrorM', targetEndpointErrorM, ...
    'pinnedManifestEntries', pinnedAfter.manifestEntries, ...
    'pinnedManifestAllMatched', pinnedAfter.allMatched, ...
    'stage2ArtifactsUnchanged', stage2Unchanged, ...
    'primaryMember', cfg.gate1.pinnedMember, ...
    'primarySelectionRule', 'predeclared pinned released substrate; no outcome selection', ...
    'runtimeSeconds', runtimeSeconds);
save(fullfile(cfg.gate1.resultsRoot, 'stage1_gate1_complete_results.mat'), ...
    'cfg', 'target', 'targetTorques', 'targetTorqueDiagnostics', ...
    'audit', 'targetNetworkAudit', 'targetAudit', 'model', ...
    'baseline', 'theta', 'hand', 'analysis', ...
    'inventory', 'summary', '-v7.3');
fid = fopen(fullfile(cfg.gate1.resultsRoot, 'stage1_gate1_summary.json'), 'w');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(summary, PrettyPrint=true));
clear cleanup;
artifactRoots = ["results/stage_1/gate1_recalibrated", ...
    "plots/stage_1/png", "plots/stage_1/fig"];
artifactManifest = hash_tree(projectRoot, artifactRoots);
writetable(artifactManifest, fullfile(cfg.gate1.auditRoot, ...
    'gate1_artifact_manifest.csv'));
fprintf('GATE 1 / STAGE 1 PASS in %.1f s; 10/10 networks passed.\n', runtimeSeconds);
