clearvars;
close all;
clc;

projectRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
cfg = stage_1_gate1_config(projectRoot);
diagnosticRoot = fullfile(cfg.gate1.resultsRoot, 'target_torque_diagnostic');
if ~isfolder(diagnosticRoot)
    mkdir(diagnosticRoot);
end
failedAuditPath = fullfile(cfg.gate1.auditRoot, 'gate1_failed_run_audit.json');
assert(isfile(failedAuditPath), 'The previous failed-run audit must be preserved.');
failedAuditHashBefore = sha256_file(failedAuditPath);
pinnedBefore = verify_pinned_reference(cfg);
stage2Roots = ["config/stage_2b_kao_config.m", ...
    "config/stage_2b_cerebellum_config.m", "src/stage_2a", ...
    "src/stage_2b_kao", "src/stage_2b_cerebellum", ...
    "analysis/stage_2a", "analysis/stage_2b_shared", ...
    "figures/stage_2a", "figures/stage_2b_shared", ...
    "results/stage_2a", "results/stage_2b_kao", ...
    "results/stage_2b_cerebellum", "plots/stage_2a", ...
    "plots/stage_2b_kao", "plots/stage_2b_cerebellum"];
stage2Before = hash_tree(projectRoot, stage2Roots);
model = load_published_generator(cfg);
gateThresholdM = cfg.gate1.validation.maxEndpointErrorM;
fprintf('D1-D4 target-torque diagnostic only. Project endpoint threshold: %.6f m.\n', ...
    gateThresholdM);
[nativeAngles, nativeTargetHands, nativeTorques, nativeDiagnostics] = ...
    load_native_target_torque_benchmark(cfg);
nativeTable = summarize_target_torque_benchmark("Pinned native Kao", ...
    nativeAngles, nativeTargetHands, nativeTorques, nativeDiagnostics, ...
    model, gateThresholdM);
originalCfg = cfg;
originalCfg.gate1.targetAnglesDeg = nativeAngles;
originalCfg.gate1.targetLabels = "K" + string(1:8);
originalTarget = source_target_hand_trajectories(originalCfg, model.arm);
fprintf('D2 benchmark 2/3: MATLAB optimizer on original Kao geometry.\n');
[originalTorques, originalDiagnostics] = ...
    optimize_source_target_torques(originalCfg, originalTarget, model.arm);
save(fullfile(diagnosticRoot, 'matlab_original_geometry_raw.mat'), ...
    'nativeAngles', 'originalTarget', 'originalTorques', ...
    'originalDiagnostics', '-v7.3');
originalTable = summarize_target_torque_benchmark( ...
    "MATLAB original geometry", nativeAngles, originalTarget.hands, ...
    originalTorques, originalDiagnostics, model, gateThresholdM);
newTarget = source_target_hand_trajectories(cfg, model.arm);
fprintf('D2 benchmark 3/3: MATLAB optimizer on new project geometry.\n');
[newTorques, newDiagnostics] = ...
    optimize_source_target_torques(cfg, newTarget, model.arm);
save(fullfile(diagnosticRoot, 'matlab_new_geometry_raw.mat'), ...
    'newTarget', 'newTorques', 'newDiagnostics', '-v7.3');
newTable = summarize_target_torque_benchmark("MATLAB new geometry", ...
    cfg.gate1.targetAnglesDeg, newTarget.hands, newTorques, ...
    newDiagnostics, model, gateThresholdM);
comparison = [nativeTable; originalTable; newTable];
writetable(comparison, fullfile(diagnosticRoot, ...
    'target_torque_comparison_by_target.csv'));
diagnosis = classify_target_torque_diagnostic(comparison, gateThresholdM);
summary = groupsummary(comparison, 'Benchmark', {'min','median','max'}, ...
    {'EndpointErrorM','AngularErrorDeg','RadialErrorM', ...
    'PositionTrajectoryRmseM','SourceTotalObjective','MaximumAbsoluteTorque'});
writetable(summary, fullfile(diagnosticRoot, ...
    'target_torque_comparison_summary.csv'));
stage2After = hash_tree(projectRoot, stage2Roots);
stage2Unchanged = isequal(stage2Before, stage2After);
pinnedAfter = verify_pinned_reference(cfg);
failedAuditHashAfter = sha256_file(failedAuditPath);
assert(stage2Unchanged, 'Frozen Stage-2 artifacts changed during D1-D4.');
assert(isequal(pinnedBefore, pinnedAfter), 'Pinned reference verification changed.');
assert(failedAuditHashBefore == failedAuditHashAfter, ...
    'Previous failed-run audit was modified.');
diagnosis.stage2ArtifactsUnchanged = stage2Unchanged;
diagnosis.pinnedManifestEntries = pinnedAfter.manifestEntries;
diagnosis.pinnedManifestAllMatched = pinnedAfter.allMatched;
diagnosis.previousFailedAuditPreserved = true;
diagnosis.tenNetworkEnsembleGenerated = false;
diagnosis.stage2AOr2BExecuted = false;
fid = fopen(fullfile(diagnosticRoot, 'target_torque_diagnosis.json'), 'w');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(diagnosis, PrettyPrint=true));
clear cleanup;
save(fullfile(diagnosticRoot, 'target_torque_diagnostic_complete.mat'), ...
    'cfg', 'comparison', 'summary', 'diagnosis', ...
    'nativeAngles', 'nativeTargetHands', 'nativeTorques', 'nativeDiagnostics', ...
    'originalTarget', 'originalTorques', 'originalDiagnostics', ...
    'newTarget', 'newTorques', 'newDiagnostics', '-v7.3');
manifest = hash_tree(projectRoot, ...
    "results/stage_1/gate1_recalibrated/target_torque_diagnostic");
manifest(endsWith(manifest.relative_path, 'target_torque_diagnostic_manifest.csv'), :) = [];
writetable(manifest, fullfile(diagnosticRoot, ...
    'target_torque_diagnostic_manifest.csv'));
fprintf('D1-D4 complete. Classification: %s\n', diagnosis.classification);
