clearvars;
close all;
clc;

projectRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
addpath(fullfile(projectRoot, 'figures'));
addpath(fullfile(projectRoot, 'figures', 'published_generator'));
cfg = stage_1_gate1_config(projectRoot);
assert(~isfile(fullfile(cfg.gate1.ensembleRoot, 'network_01.mat')), ...
    'Accepted ensemble exists; construction must not overwrite frozen assets.');
sampling = cfg.gate1.rejectionSampling;
roots = {sampling.workRoot, sampling.attemptRoot, ...
    sampling.acceptedRoot, sampling.auditRoot};
for rootIndex = 1:numel(roots)
    if ~isfolder(roots{rootIndex})
        mkdir(roots{rootIndex});
    end
end
assert(isempty(dir(fullfile(sampling.attemptRoot, 'attempt_*.mat'))), ...
    'Rejection-sampling work folder is not empty; do not silently resume or overwrite.');
fprintf('Gate 1 rejection sampling only; first 10 QC-passing independent ISNs.\n');
fprintf('Seed schedule: W %d onward; calibration %d onward; one pair per attempt.\n', ...
    sampling.recurrentSeedStart, sampling.calibrationSeedStart);
startTime = tic;
pinnedBefore = verify_pinned_reference(cfg);
baseModel = load_published_generator(cfg);
targetSource = fullfile(cfg.gate1.targetRoot, 'stage1_gate1_targets.mat');
assert(isfile(targetSource), 'Accepted 10-cm target bundle is missing.');
targetBundle = load(targetSource, 'target', 'targetTorques', ...
    'targetTorqueDiagnostics', 'targetAudit', 'summary');
assert(targetBundle.summary.allTargetsPassed ...
    && targetBundle.summary.targetRadiusM == cfg.gate1.radiusM ...
    && isequal(targetBundle.summary.targetAnglesDeg, cfg.gate1.targetAnglesDeg), ...
    'The saved target bundle is not the accepted 10-cm target layer.');
attemptAudit = table();
attemptTargetAudit = table();
acceptedModels = cell(sampling.acceptedCount, 1);
acceptedCalibrations = cell(sampling.acceptedCount, 1);
acceptedRecurrents = cell(sampling.acceptedCount, 1);
acceptedCount = 0;
for attempt = 1:sampling.maximumAttempts
    recurrentSeed = sampling.recurrentSeedStart + attempt - 1;
    calibrationSeed = sampling.calibrationSeedStart + attempt - 1;
    fprintf('Attempt %d: W seed %d; calibration seed %d.\n', ...
        attempt, recurrentSeed, calibrationSeed);
    [W, recurrent] = generate_source_faithful_recurrent(cfg, recurrentSeed);
    [model, calibration] = calibrate_source_faithful_generator(cfg, W, [], ...
        targetBundle.targetTorques, calibrationSeed, baseModel);
    model.targetHand = targetBundle.target.hands;
    model.targetTorque = targetBundle.targetTorques;
    proposedMember = acceptedCount + 1;
    [networkRow, targetRows] = evaluate_stage1_gate1_candidate(cfg, ...
        model, calibration, recurrent, targetBundle.target, ...
        targetBundle.targetTorques, attempt, recurrentSeed, ...
        calibrationSeed, proposedMember);
    if ~networkRow.Pass
        networkRow.AcceptedMember = 0;
        targetRows.AcceptedMember(:) = 0;
    end
    attemptAudit = [attemptAudit; networkRow]; %#ok<AGROW>
    attemptTargetAudit = [attemptTargetAudit; targetRows]; %#ok<AGROW>
    save(fullfile(sampling.attemptRoot, ...
        sprintf('attempt_%03d.mat', attempt)), 'model', 'calibration', ...
        'recurrent', 'networkRow', 'targetRows', '-v7.3');
    writetable(attemptAudit, fullfile(sampling.auditRoot, ...
        'attempted_realization_audit.csv'));
    writetable(attemptTargetAudit, fullfile(sampling.auditRoot, ...
        'attempted_target_audit.csv'));
    if networkRow.Pass
        acceptedCount = proposedMember;
        acceptedModels{acceptedCount} = model;
        acceptedCalibrations{acceptedCount} = calibration;
        acceptedRecurrents{acceptedCount} = recurrent;
        save(fullfile(sampling.acceptedRoot, ...
            sprintf('network_%02d.mat', acceptedCount)), 'model', ...
            'calibration', 'recurrent', 'networkRow', 'targetRows', '-v7.3');
        fprintf('Attempt %d ACCEPTED as member %d.\n', attempt, acceptedCount);
    else
        fprintf('Attempt %d REJECTED: %s.\n', attempt, networkRow.FailureReason);
    end
    if acceptedCount == sampling.acceptedCount
        break
    end
end
assert(acceptedCount == sampling.acceptedCount, ...
    'Maximum attempts reached before obtaining ten accepted networks.');
acceptedAudit = attemptAudit(attemptAudit.Pass, :);
acceptedTargetAudit = attemptTargetAudit(attemptTargetAudit.AcceptedMember > 0, :);
acceptedAudit = sortrows(acceptedAudit, 'AcceptedMember');
acceptedTargetAudit = sortrows(acceptedTargetAudit, ...
    {'AcceptedMember', 'Target'});
assert(height(acceptedAudit) == sampling.acceptedCount ...
    && all(acceptedAudit.Pass) && all(acceptedTargetAudit.Pass), ...
    'Accepted-ensemble revalidation failed.');
writetable(acceptedAudit, fullfile(sampling.auditRoot, ...
    'accepted_ensemble_audit.csv'));
writetable(acceptedTargetAudit, fullfile(sampling.auditRoot, ...
    'accepted_ensemble_target_audit.csv'));
primaryModel = acceptedModels{1};
baseline = simulate_published_cortex(primaryModel, primaryModel.xstar, true);
[theta, hand] = simulate_published_arm(primaryModel, baseline.torque);
analysis = analyze_published_generator(cfg, primaryModel, baseline, theta, hand);
inventory = create_stage1_figures(cfg, primaryModel, baseline, hand, analysis);
pinnedAfter = verify_pinned_reference(cfg);
assert(isequal(pinnedBefore, pinnedAfter), ...
    'Pinned Kao benchmark verification changed during Gate 1.');
runtimeSeconds = toc(startTime);
summary = struct('status', 'PASS', ...
    'scope', 'Gate 1 rejection-sampling completion only', ...
    'sourceCommit', cfg.gate1.sourceCommit, ...
    'targetRadiusM', cfg.gate1.radiusM, ...
    'targetAnglesDeg', cfg.gate1.targetAnglesDeg, ...
    'attemptedCount', height(attemptAudit), ...
    'acceptedCount', height(acceptedAudit), ...
    'rejectedCount', sum(~attemptAudit.Pass), ...
    'acceptanceRate', mean(attemptAudit.Pass), ...
    'acceptedRecurrentSeeds', acceptedAudit.RecurrentSeed.', ...
    'acceptedCalibrationSeeds', acceptedAudit.CalibrationSeed.', ...
    'maximumAcceptedAngleErrorDeg', max(acceptedAudit.MaxAngleErrorDeg), ...
    'maximumAcceptedRadiusErrorM', max(acceptedAudit.MaxRadiusErrorM), ...
    'maximumAcceptedEndpointErrorM', max(acceptedAudit.MaxEndpointErrorM), ...
    'maximumAcceptedWeightedTorqueCost', max(acceptedAudit.WeightedTorqueCost), ...
    'pinnedManifestEntries', pinnedAfter.manifestEntries, ...
    'pinnedManifestAllMatched', pinnedAfter.allMatched, ...
    'primaryMember', 1, ...
    'primarySelectionRule', 'first QC-passing attempt; no downstream selection', ...
    'runtimeSeconds', runtimeSeconds);
save(fullfile(sampling.workRoot, 'stage1_gate1_complete_results.mat'), ...
    'cfg', 'targetBundle', 'attemptAudit', 'attemptTargetAudit', ...
    'acceptedAudit', 'acceptedTargetAudit', 'primaryModel', 'baseline', ...
    'theta', 'hand', 'analysis', 'inventory', 'summary', '-v7.3');
fid = fopen(fullfile(sampling.workRoot, 'stage1_gate1_summary.json'), 'w');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', jsonencode(summary, PrettyPrint=true));
clear cleanup;
manifest = hash_tree(projectRoot, "results/stage_1/rejection_sampling_work");
manifest(endsWith(manifest.relative_path, ...
    'rejection_sampling_manifest.csv'), :) = [];
writetable(manifest, fullfile(sampling.auditRoot, ...
    'rejection_sampling_manifest.csv'));
fprintf('REJECTION SAMPLING PASS: %d attempts, %d accepted, %d rejected.\n', ...
    height(attemptAudit), height(acceptedAudit), sum(~attemptAudit.Pass));
fprintf('Stage-1-only construction completed.\n');
