clear;
close all;
clc;

projectRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'src', 'stage_2a'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'stage_2a'));

cfg = stage_2a_config(projectRoot);
audit = revalidate_stage2a_ensemble(projectRoot, false);
maximumTonicDifference = 0;
maximumTrajectoryStateErrorDifference = 0;
maximumTrajectoryProspectiveErrorDifference = 0;

for network = 1:cfg.ensemble.count
    stage1 = load(fullfile(cfg.ensemble.stage1Root, ...
        sprintf('network_%02d.mat', network)), 'model');
    stage2a = load(fullfile(cfg.resultsRoot, 'current', 'ensemble', ...
        sprintf('network_%02d_stage2a.mat', network)), 'networkResult');
    saved = stage2a.networkResult;
    [tonicInput, residual] = compute_tonic_input(stage1.model);
    maximumTonicDifference = max(maximumTonicDifference, ...
        max(abs(tonicInput - saved.tonicInput), [], 'all'));
    assert(max(abs(residual - saved.fixedPointResidual), [], 'all') == 0);
    preparation = simulate_naive_preparation(stage1.model, tonicInput, ...
        cfg.preparation.maximumDurationS);
    assert(isequal(preparation.timesS, saved.preparationTimesS));
    for target = 1:stage1.model.nMovements
        delta = preparation.states(:, :, target) ...
            - stage1.model.xstar(:, target).';
        stateError = vecnorm(delta, 2, 2);
        stateError = stateError / max(stateError(1), eps);
        prospectiveError = sum((delta * stage1.model.Qnative) .* delta, 2);
        prospectiveError = prospectiveError / max(prospectiveError(1), eps);
        maximumTrajectoryStateErrorDifference = max( ...
            maximumTrajectoryStateErrorDifference, ...
            max(abs(stateError - saved.normalizedStateError(:, target))));
        maximumTrajectoryProspectiveErrorDifference = max( ...
            maximumTrajectoryProspectiveErrorDifference, ...
            max(abs(prospectiveError ...
                - saved.normalizedProspectiveError(:, target))));
    end
end

stability = readtable(fullfile(cfg.resultsRoot, 'current', 'diagnostics', ...
    'fixed_point_jacobian_stability.csv'));
summary = jsondecode(fileread(fullfile(cfg.resultsRoot, 'current', ...
    'stage2a_summary.json')));
assert(height(stability) == 80 && all(stability.Pass));
assert(summary.allNetworksPassed && summary.allTargetRowsPassed);
assert(maximumTonicDifference <= 1e-12);
assert(maximumTrajectoryStateErrorDifference <= 1e-12);
assert(maximumTrajectoryProspectiveErrorDifference <= 1e-12);

report = struct('status', 'PASS', 'networkCount', cfg.ensemble.count, ...
    'targetCount', height(stability), ...
    'stableTargetCount', nnz(stability.Pass), ...
    'maximumAuditDifference', audit.maximumAuditDifference, ...
    'maximumTonicDifference', maximumTonicDifference, ...
    'maximumTrajectoryStateErrorDifference', ...
        maximumTrajectoryStateErrorDifference, ...
    'maximumTrajectoryProspectiveErrorDifference', ...
        maximumTrajectoryProspectiveErrorDifference, ...
    'maximumLongEndpointErrorM', summary.maximumLongEndpointErrorM, ...
    'figurePairsReopened', audit.figurePairCount);
disp(jsonencode(report, PrettyPrint=true));
