clear;
close all;
clc;

projectRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(genpath(fullfile(projectRoot, 'config')));
addpath(genpath(fullfile(projectRoot, 'src')));
addpath(genpath(fullfile(projectRoot, 'analysis')));

gate2Path = fullfile(projectRoot, 'results', 'stage_2b_kao', ...
    'diagnostics', 'active_set_gate2', ...
    'gate2_active_set_diagnostics_complete.mat');
gate2Saved = load(gate2Path, 'results', 'diagnostic');
gate2 = gate2Saved.results;
switchingRows = gate2.stage1Target.SwitchingFraction > 0;
exactRows = gate2.frozenRegimeTarget.EndpointErrorM == 0;
assert(height(gate2.stage1Target) == 80);
assert(nnz(switchingRows) == 8 && nnz(~switchingRows) == 72);
assert(nnz(exactRows) == 72);
assert(height(gate2.stage1Overlap) == 280);
assert(all(gate2.stage1Overlap.UnionSetJaccard == 1));
assert(all(gate2.validation.Passed));

cfg = stage_2b_kao_config(projectRoot);
lambdaPath = fullfile(cfg.resultsRoot, 'diagnostics', ...
    'lambda_sensitivity', 'stage2b_kao_lambda_sensitivity_complete.mat');
lambdaSaved = load(lambdaPath, 'complete');
lambdaResults = lambdaSaved.complete.results;
assert(lambdaSaved.complete.networkCount == 10);
assert(isequal(lambdaSaved.complete.lambdas(:), [0.01; 0.03; 0.1; 0.3; 1]));
lambda01 = lambdaResults.reproduction( ...
    lambdaResults.reproduction.Lambda == 0.1, :);
assert(height(lambda01) == 10);
assert(max(lambda01.MaximumCanonicalGainDifference) <= 1e-12);
assert(max(lambda01.MaximumCanonicalProspectiveDifference) <= 1e-12);
assert(max(lambda01.MaximumCanonicalEndpointDifference) <= 1e-12);

component = analyze_stage2b_kao_lambda_sensitivity(cfg, ...
    NetworkCount=1, MovementDurationsS=[0.100; 0.200], ...
    SavePerNetwork=false);
component01 = component.results.reproduction( ...
    component.results.reproduction.Lambda == 0.1, :);
assert(max(component01.MaximumCanonicalGainDifference) <= 1e-12);
assert(max(component01.MaximumCanonicalProspectiveDifference) <= 1e-12);
assert(max(component01.MaximumCanonicalEndpointDifference) <= 1e-12);

report = struct('status', 'PASS', 'stage1ExactRows', nnz(~switchingRows), ...
    'stage1SwitchingRows', nnz(switchingRows), ...
    'jaccardExactPairs', nnz(gate2.stage1Overlap.UnionSetJaccard == 1), ...
    'lambdaCount', numel(lambdaSaved.complete.lambdas), ...
    'lambdaNetworkCount', lambdaSaved.complete.networkCount, ...
    'savedLambda01MaximumGainDifference', ...
        max(lambda01.MaximumCanonicalGainDifference), ...
    'savedLambda01MaximumProspectiveDifference', ...
        max(lambda01.MaximumCanonicalProspectiveDifference), ...
    'savedLambda01MaximumEndpointDifference', ...
        max(lambda01.MaximumCanonicalEndpointDifference), ...
    'componentLambda01MaximumGainDifference', ...
        max(component01.MaximumCanonicalGainDifference), ...
    'componentLambda01MaximumProspectiveDifference', ...
        max(component01.MaximumCanonicalProspectiveDifference), ...
    'componentLambda01MaximumEndpointDifference', ...
        max(component01.MaximumCanonicalEndpointDifference));
disp(jsonencode(report, PrettyPrint=true));
