clear;
close all;
clc;

projectRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(projectRoot, 'config'));
addpath(fullfile(projectRoot, 'src', 'published_generator'));
addpath(fullfile(projectRoot, 'src', 'stage_2b_kao'));
addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
addpath(fullfile(projectRoot, 'analysis', 'stage_2b_shared'));

cfg = stage_2b_kao_config(projectRoot);
require_kao_reference(cfg.stage1);
maximumGainReloadDifference = 0;
maximumCareResidual = 0;
maximumFixedPointResidual = 0;
maximumJacobianError = 0;
maximumSpectralAbscissa = -Inf;

for network = 1:cfg.ensemble.count
    stage1 = load(fullfile(cfg.ensemble.stage1Root, ...
        sprintf('network_%02d.mat', network)), 'model');
    stored = load(fullfile(cfg.resultsRoot, 'ensemble', ...
        sprintf('network_%02d_stage2b_kao_controller.mat', network)), ...
        'controllerSaved');
    controller = derive_stage2b_kao_controller(stage1.model, cfg);
    savedController = stored.controllerSaved;
    maximumGainReloadDifference = max(maximumGainReloadDifference, ...
        max(abs(controller.K - savedController.K), [], 'all'));
    sourceGate = validate_stage2b_source_gate(cfg, stage1.model, controller);
    maximumCareResidual = max(maximumCareResidual, ...
        controller.careResidualRelative);
    maximumFixedPointResidual = max(maximumFixedPointResidual, ...
        max(controller.fixedPointResidualNorm));
    maximumJacobianError = max(maximumJacobianError, ...
        sourceGate.maximumJacobianRelativeError);
    maximumSpectralAbscissa = max(maximumSpectralAbscissa, ...
        max(sourceGate.spectralAbscissaPerS));
end

saved = load(fullfile(cfg.resultsRoot, ...
    'stage2b_kao_gate3_complete.mat'), 'complete');
results = saved.complete.results;
summary = jsondecode(fileread(fullfile(cfg.resultsRoot, ...
    'stage2b_kao_gate3_summary.json')));
inventory = readtable(fullfile(cfg.resultsRoot, ...
    'canonical_figure_inventory.csv'), Delimiter=',', TextType='string');
assert(height(results.controller) == 10);
assert(height(results.targetValidation) == 160);
assert(height(results.alignment) == 10);
assert(height(results.alignmentNull) == 100000);
assert(all(groupsummary(results.alignmentNull, 'Network').GroupCount == 10000));
assert(height(results.corticalDimensionality) == 40);
assert(height(results.prStatistics) == 2);
assert(height(inventory) == 9);
assert(abs(median(results.alignment.ObservedAlignment) ...
    - summary.medianObservedAlignment) <= 1e-12);
assert(abs(median(results.alignment.NullMedian) ...
    - summary.medianExpectedAlignment) <= 1e-12);
assert(nnz(results.alignment.BhAdjustedLowerTailP < 0.05) ...
    == summary.bhSignificantAlignmentCount);
assert(maximumGainReloadDifference <= 1e-12);
assert(maximumCareResidual < cfg.validation.careResidualTolerance);
assert(maximumFixedPointResidual < cfg.validation.fixedPointTolerance);
assert(maximumJacobianError < cfg.validation.jacobianDirectionalTolerance);
assert(maximumSpectralAbscissa < 0);

figure5 = readtable(fullfile(cfg.resultsRoot, 'audit', ...
    'figure5_final_100_vs_200_network_audit.csv'), ...
    Delimiter=',', TextType='string');
assert(height(figure5) == 20);
stage2aFigure5 = figure5(figure5.Controller == "Stage 2A", :);
kaoFigure5 = figure5(figure5.Controller == "Stage 2B-Kao", :);
assert(nnz(stage2aFigure5.EndpointErrorMLowerAt200) ...
    == summary.stage2aEndpointLowerAt200NetworkCount);
assert(nnz(kaoFigure5.EndpointErrorMLowerAt200) ...
    == summary.stage2bKaoEndpointLowerAt200NetworkCount);

report = struct('status', 'PASS', 'networkCount', 10, ...
    'controllerReloadMaximumDifference', maximumGainReloadDifference, ...
    'maximumCareResidual', maximumCareResidual, ...
    'maximumFixedPointResidual', maximumFixedPointResidual, ...
    'maximumJacobianRelativeError', maximumJacobianError, ...
    'maximumSpectralAbscissaPerS', maximumSpectralAbscissa, ...
    'medianObservedAlignment', median(results.alignment.ObservedAlignment), ...
    'medianExpectedAlignment', median(results.alignment.NullMedian), ...
    'significantAlignmentNetworks', ...
        nnz(results.alignment.BhAdjustedLowerTailP < 0.05), ...
    'canonicalFigurePairs', height(inventory));
disp(jsonencode(report, PrettyPrint=true));
