function require_kao_reference(cfg)
    setupScript = fullfile(cfg.projectRoot, 'third_party', ...
        'kao_optimal_preparation', 'setup_local_cache.ps1');
    required = {
        fullfile(cfg.referenceRoot, 'artifact_manifest.tsv'), ...
        fullfile(cfg.dataRoot, 'native_cortical_r1_1.tsv')};
    if ~isfolder(cfg.referenceRoot) || ~all(cellfun(@isfile, required))
        error('KaoReference:MissingLocalCache', [ ...
            'The pinned project-local Kao/native-reference cache is missing. ' ...
            'Restore it with PowerShell script "%s", then rerun. ' ...
            'Historical result bundles are not a supported fallback.'], ...
            setupScript);
    end
end
