function report = analyze_gate2_active_set_diagnostics(projectRoot)
    %#ok<*AGROW,*UDIM>
    cfg = stage_2b_kao_config(projectRoot);
    diagnostic = diagnostic_config(cfg);
    make_directories(diagnostic);
    frozenBefore = capture_frozen_manifest(projectRoot, diagnostic.frozenRoots);
    writetable(frozenBefore, fullfile(diagnostic.auditRoot, ...
        'frozen_canonical_manifest_before.csv'));
    savedKao = load(fullfile(cfg.resultsRoot, ...
        'stage2b_kao_gate3_complete.mat'), 'complete');
    acceptedMovement = savedKao.complete.results.movement;
    assert(height(acceptedMovement) == 2 * cfg.ensemble.count * 8 * 51);
    stage1Target = table();
    stage1Overlap = table();
    stage1ActiveCurve = table();
    frozenMetrics = table();
    frozenCurves = table();
    preparationTarget = table();
    representative = struct();
    validationRows = table();
    startTime = tic;
    for network = 1:cfg.ensemble.count
        modelPath = fullfile(cfg.ensemble.stage1Root, ...
            sprintf('network_%02d.mat', network));
        loaded = load(modelPath, 'model');
        model = loaded.model;
        stage2aPath = fullfile(cfg.ensemble.stage2aRoot, ...
            sprintf('network_%02d_stage2a.mat', network));
        stage2aSaved = load(stage2aPath, 'networkResult');
        tonic = model.xstar - model.W * max(model.xstar, 0) - model.h;
        assert(max(abs(tonic - stage2aSaved.networkResult.tonicInput), ...
            [], 'all') < 1e-12);
        kao = derive_stage2b_kao_controller(model, cfg);
        [targetRows, overlapRows, curveRows, frozenRows, curveMismatch, ...
            representativeMovement, stage1Validation] = ...
            analyze_stage1_network(model, network);
        stage1Target = [stage1Target; targetRows];
        stage1Overlap = [stage1Overlap; overlapRows];
        stage1ActiveCurve = [stage1ActiveCurve; curveRows];
        frozenMetrics = [frozenMetrics; frozenRows];
        frozenCurves = [frozenCurves; curveMismatch];
        [preparationRows, preparationValidation] = ...
            analyze_preparation_network(cfg, model, tonic, kao, network, ...
            acceptedMovement);
        preparationTarget = [preparationTarget; preparationRows];
        validationRows = [validationRows; stage1Validation; ...
            preparationValidation];
        if network == cfg.ensemble.representativeIndex
            representative.movement = representativeMovement;
        end
        fprintf('Completed Gate-2 diagnostic network %d/%d.\n', ...
            network, cfg.ensemble.count);
    end
    [stage1Network, activeCurveNetwork, frozenNetwork, frozenCurveNetwork] = ...
        summarize_stage1(stage1Target, stage1Overlap, stage1ActiveCurve, ...
        frozenMetrics, frozenCurves, diagnostic);
    [preparationNetwork, preparationEnsemble, timing] = ...
        summarize_preparation(preparationTarget, diagnostic);
    results = struct('stage1Target', stage1Target, ...
        'stage1Overlap', stage1Overlap, ...
        'stage1ActiveCurve', stage1ActiveCurve, ...
        'stage1Network', stage1Network, ...
        'stage1ActiveCurveNetwork', activeCurveNetwork, ...
        'frozenRegimeTarget', frozenMetrics, ...
        'frozenRegimeCurve', frozenCurves, ...
        'frozenRegimeNetwork', frozenNetwork, ...
        'frozenRegimeCurveNetwork', frozenCurveNetwork, ...
        'preparationTarget', preparationTarget, ...
        'preparationNetwork', preparationNetwork, ...
        'preparationEnsemble', preparationEnsemble, ...
        'preparationTiming', timing, 'validation', validationRows);
    save(fullfile(diagnostic.resultsRoot, ...
        'gate2_active_set_diagnostics_complete.mat'), 'results', ...
        'representative', 'diagnostic', '-v7.3');
    write_result_tables(diagnostic.tableRoot, results);
    figureFiles = create_gate2_active_set_figures(cfg, diagnostic, ...
        results, representative);
    figureValidation = validate_figures(figureFiles);
    frozenAfter = capture_frozen_manifest(projectRoot, diagnostic.frozenRoots);
    writetable(frozenAfter, fullfile(diagnostic.auditRoot, ...
        'frozen_canonical_manifest_after.csv'));
    [frozenMatched, frozenCheck] = compare_manifests(frozenBefore, frozenAfter);
    assert(frozenMatched, 'A frozen canonical artifact changed.');
    writetable(frozenCheck, fullfile(diagnostic.auditRoot, ...
        'frozen_canonical_verification.csv'));
    assert(all(validationRows.Passed));
    summary = build_summary(results, figureFiles, figureValidation, ...
        frozenMatched, toc(startTime), diagnostic);
    write_json(fullfile(diagnostic.resultsRoot, ...
        'gate2_active_set_diagnostics_summary.json'), summary);
    artifactManifest = hash_tree(projectRoot, [
        "results/stage_1/diagnostics/active_set_gate2";
        "results/stage_2a/diagnostics/active_set_gate2";
        "results/stage_2b_kao/diagnostics/active_set_gate2";
        "plots/stage_1/diagnostics/active_set_gate2";
        "plots/stage_2b_kao/diagnostics/active_set_gate2"]);
    writetable(artifactManifest, fullfile(diagnostic.auditRoot, ...
        'diagnostic_artifact_manifest_sha256.csv'));
    codeManifest = hash_tree(projectRoot, [
        "workflows/diagnostics/stage_2b_kao/run_gate2_active_set_diagnostics.m";
        "analysis/stage_2b_shared/analyze_gate2_active_set_diagnostics.m";
        "figures/stage_2b_shared/create_gate2_active_set_figures.m"]);
    writetable(codeManifest, fullfile(diagnostic.auditRoot, ...
        'diagnostic_code_manifest_sha256.csv'));
    report = struct('summary', summary, 'figureFiles', figureFiles, ...
        'figureValidation', figureValidation, ...
        'frozenVerification', frozenCheck);
end

function output = diagnostic_config(cfg)
    output.resultsRoot = fullfile(cfg.resultsRoot, 'diagnostics', ...
        'active_set_gate2');
    output.tableRoot = fullfile(output.resultsRoot, 'tables');
    output.auditRoot = fullfile(output.resultsRoot, 'audit');
    output.stage1ResultsRoot = fullfile(cfg.projectRoot, 'results', ...
        'stage_1', 'diagnostics', 'active_set_gate2');
    output.stage2aResultsRoot = fullfile(cfg.projectRoot, 'results', ...
        'stage_2a', 'diagnostics', 'active_set_gate2');
    output.stage1PlotsRoot = fullfile(cfg.projectRoot, 'plots', 'stage_1', ...
        'diagnostics', 'active_set_gate2');
    output.stage1PngRoot = fullfile(output.stage1PlotsRoot, 'png');
    output.stage1FigRoot = fullfile(output.stage1PlotsRoot, 'fig');
    output.comparisonPlotsRoot = fullfile(cfg.projectRoot, 'plots', ...
        'stage_2b_kao', 'diagnostics', 'active_set_gate2');
    output.comparisonPngRoot = fullfile(output.comparisonPlotsRoot, 'png');
    output.comparisonFigRoot = fullfile(output.comparisonPlotsRoot, 'fig');
    output.bootstrapSamples = 10000;
    output.bootstrapSeed = 2026090202;
    output.durationsS = (0:0.010:0.500).';
    output.activeMismatchThresholdPercent = 1;
    output.prospectiveThreshold = 0.05;
    output.endpointThresholdM = 0.002;
    output.frozenRoots = [
        "results/stage_1/current";
        "plots/stage_1/png";
        "plots/stage_1/fig";
        "results/stage_2a/current";
        "plots/stage_2a/png";
        "plots/stage_2a/fig";
        "results/stage_2b_kao/stage2b_kao_gate3_complete.mat";
        "results/stage_2b_kao/stage2b_kao_gate3_summary.json";
        "results/stage_2b_kao/canonical_figure_inventory.csv";
        "results/stage_2b_kao/tables";
        "results/stage_2b_kao/alignment_nulls";
        "plots/stage_2b_kao/png";
        "plots/stage_2b_kao/fig";
        "results/stage_2b_cerebellum";
        "plots/stage_2b_cerebellum"];
end

function make_directories(diagnostic)
    paths = {diagnostic.resultsRoot, diagnostic.tableRoot, ...
        diagnostic.auditRoot, diagnostic.stage1ResultsRoot, ...
        diagnostic.stage2aResultsRoot, diagnostic.stage1PngRoot, ...
        diagnostic.stage1FigRoot, diagnostic.comparisonPngRoot, ...
        diagnostic.comparisonFigRoot};
    for index = 1:numel(paths)
        if ~isfolder(paths{index}), mkdir(paths{index}); end
    end
end

function [targetRows, overlapRows, curveRows, frozenRows, mismatchRows, ...
        representative, validation] = analyze_stage1_network(model, network)
    trueMovement = simulate_true_movement(model);
    representative = struct();
    accepted = simulate_published_cortex(model, model.xstar, true);
    maxRateDifference = max(abs(trueMovement.rates - accepted.rates), [], 'all');
    maxTorqueDifference = max(abs(trueMovement.torque - accepted.torque), [], 'all');
    assert(maxRateDifference <= 1e-12 && maxTorqueDifference <= 1e-12);
    [~, trueHand] = simulate_published_arm(model, trueMovement.torque);
    nTargets = model.nMovements;
    active = trueMovement.states > 0;
    targetRows = table();
    curveRows = table();
    frozenRows = table();
    mismatchRows = table();
    unionSets = false(model.n, nTargets);
    meanRates = squeeze(mean(trueMovement.rates, 1));
    for target = 1:nTargets
        targetActive = squeeze(active(:, :, target));
        transitions = sum(diff(targetActive, 1, 1) ~= 0, 1);
        switchingFraction = mean(transitions > 0);
        transitionsPerNeuron = mean(transitions);
        transitionsPerNeuronPerS = transitionsPerNeuron / ...
            ((model.nSamples - 1) * model.samplingDt);
        unionSets(:, target) = any(targetActive, 1).';
        occupancy = mean(targetActive, 1).';
        targetRows = [targetRows; table(network, target, ... %#ok<AGROW>
            switchingFraction, sum(transitions), transitionsPerNeuron, ...
            transitionsPerNeuronPerS, mean(occupancy), ... %#ok<UDIM>
            'VariableNames', {'Network','Target','SwitchingFraction', ...
            'TotalTransitions','TransitionsPerNeuron', ...
            'TransitionsPerNeuronPerS','MeanActiveFraction'})];
        fractionActive = mean(targetActive, 2);
        timeS = trueMovement.timesS;
        curveRows = [curveRows; table(repmat(network, numel(timeS), 1), ... %#ok<AGROW>
            repmat(target, numel(timeS), 1), timeS, fractionActive, ...
            'VariableNames', {'Network','Target','MovementTimeS', ...
            'ActiveFraction'})];
        frozen = simulate_frozen_regime(model, model.xstar(:, target), ...
            targetActive(1, :).');
        [~, frozenHand] = simulate_published_arm(model, frozen.torque);
        trueRates = trueMovement.rates(:, :, target);
        trueTorque = trueMovement.torque(:, :, target);
        targetHand = trueHand(:, [1, 3], target);
        fixedHand = frozenHand(:, [1, 3]);
        corticalNrmse = normalized_rmse(frozen.rates, trueRates);
        torqueNrmse = normalized_rmse(frozen.torque, trueTorque);
        handNrmse = normalized_rmse(fixedHand - fixedHand(1, :), ...
            targetHand - targetHand(1, :));
        endpointErrorM = norm(fixedHand(end, :) - targetHand(end, :));
        frozenRows = [frozenRows; table(network, target, corticalNrmse, ... %#ok<AGROW>
            torqueNrmse, handNrmse, endpointErrorM, ...
            'VariableNames', {'Network','Target','CorticalRateNRMSE', ...
            'TorqueNRMSE','HandTrajectoryNRMSE','EndpointErrorM'})];
        rateDifference = squeeze(vecnorm(frozen.rates - trueRates, 2, 2));
        torqueDifference = squeeze(vecnorm(frozen.torque - trueTorque, 2, 2));
        handDifference = vecnorm(fixedHand - targetHand, 2, 2);
        mismatchRows = [mismatchRows; table( ... %#ok<AGROW>
            repmat(network, model.nSamples, 1), ...
            repmat(target, model.nSamples, 1), trueMovement.timesS, ...
            rateDifference, torqueDifference, handDifference(1:end-1), ...
            'VariableNames', {'Network','Target','MovementTimeS', ...
            'CorticalDifferenceNorm','TorqueDifferenceNorm', ...
            'HandPositionDifferenceM'})];
        if network == 1 && target == 1
            representative.trueHand = targetHand;
            representative.frozenHand = fixedHand;
        end
    end
    overlapRows = table();
    for first = 1:(nTargets - 1)
        for second = (first + 1):nTargets
            intersection = sum(unionSets(:, first) & unionSets(:, second));
            unionCount = sum(unionSets(:, first) | unionSets(:, second));
            jaccard = intersection / max(unionCount, 1);
            overlapRows = [overlapRows; table(network, first, second, ... %#ok<AGROW>
                jaccard, intersection, unionCount, 'VariableNames', ...
                {'Network','Target1','Target2','UnionSetJaccard', ...
                'IntersectionCount','UnionCount'})];
        end
    end
    if network == 1
        [~, preferredTarget] = max(meanRates, [], 2);
        modulation = max(meanRates, [], 2) - min(meanRates, [], 2);
        orderingTable = table((1:model.n).', preferredTarget, modulation, ...
            'VariableNames', {'Neuron','PreferredTarget','Modulation'});
        orderingTable = sortrows(orderingTable, ...
            {'PreferredTarget','Modulation','Neuron'}, {'ascend','descend','ascend'});
        ordering = orderingTable.Neuron;
        normalizedMean = meanRates ./ max(max(meanRates, [], 2), eps);
        normalizedMean(~isfinite(normalizedMean)) = 0;
        representative.activeRaster = active(:, ordering, :);
        representative.meanRatesRaw = meanRates(ordering, :);
        representative.meanRatesNormalized = normalizedMean(ordering, :);
        representative.neuronOrdering = orderingTable;
        representative.timesS = trueMovement.timesS;
    end
    validation = table(network, "Stage 1 nonlinear reproduction", ...
        max(maxRateDifference, maxTorqueDifference), 1e-12, true, ...
        'VariableNames', {'Network','Check','MaximumDifference', ...
        'Tolerance','Passed'});
end

function output = simulate_true_movement(model)
    x = model.xstar;
    sampleEvery = round(model.samplingDt / model.dt);
    states = zeros(model.nSamples, model.n, model.nMovements);
    rates = zeros(model.nSamples, model.n, model.nMovements);
    torque = zeros(model.nSamples, 2, model.nMovements);
    sample = 0;
    for step = 0:(model.nInternalSteps - 1)
        r = max(x, 0);
        if mod(step, sampleEvery) == 0
            sample = sample + 1;
            states(sample, :, :) = permute(x, [3, 1, 2]);
            rates(sample, :, :) = permute(r, [3, 1, 2]);
            torque(sample, :, :) = permute(model.C * r, [3, 1, 2]);
        end
        drive = published_movement_input(model.dt * step, model);
        x = x + (model.dt / model.tau) * ...
            (-x + model.W * r + model.h + drive);
    end
    output = struct('states', states, 'rates', rates, 'torque', torque, ...
        'timesS', (0:(model.nSamples - 1)).' * model.samplingDt);
end

function output = simulate_frozen_regime(model, initialState, activeAtGo)
    x = initialState;
    activeAtGo = double(activeAtGo(:));
    sampleEvery = round(model.samplingDt / model.dt);
    rates = zeros(model.nSamples, model.n);
    torque = zeros(model.nSamples, 2);
    sample = 0;
    for step = 0:(model.nInternalSteps - 1)
        r = activeAtGo .* x;
        if mod(step, sampleEvery) == 0
            sample = sample + 1;
            rates(sample, :) = r.';
            torque(sample, :) = (model.C * r).';
        end
        drive = published_movement_input(model.dt * step, model);
        x = x + (model.dt / model.tau) * ...
            (-x + model.W * r + model.h + drive);
    end
    output = struct('rates', rates, 'torque', torque);
end

function [rows, validation] = analyze_preparation_network(~, model, tonic, ...
        kao, network, acceptedMovement)
    prepA = simulate_naive_preparation(model, tonic, 0.500);
    prepK = simulate_stage2b_kao_preparation(model, kao, 0.500);
    sampleIndices = round((0:0.010:0.500) / model.samplingDt) + 1;
    preparations = {prepA, prepK};
    controllers = ["Stage 2A", "Stage 2B-Kao"];
    rows = table();
    maximumMetricDifference = 0;
    maximumEndpointDifference = 0;
    checkDurations = [0, 0.100, 0.200, 0.500];
    idealCortex = simulate_published_cortex(model, model.xstar, false);
    [~, idealHand] = simulate_published_arm(model, idealCortex.torque);
    for controllerIndex = 1:2
        states = preparations{controllerIndex}.states(sampleIndices, :, :);
        checkIndices = round(checkDurations / 0.010) + 1;
        checkStates = reshape(permute(states(checkIndices, :, :), ...
            [2, 3, 1]), model.n, []);
        checkCortex = simulate_published_cortex(model, checkStates, false);
        [~, checkHand] = simulate_published_arm(model, checkCortex.torque);
        for target = 1:model.nMovements
            delta0 = model.spontaneous - model.xstar(:, target);
            q0 = delta0.' * kao.Q * delta0;
            for durationIndex = 1:numel(sampleIndices)
                state = squeeze(states(durationIndex, :, target)).';
                desired = model.xstar(:, target);
                mismatchPercent = 100 * mean((state > 0) ~= (desired > 0));
                delta = state - desired;
                stateFraction = norm(delta) / max(norm(delta0), eps);
                prospectiveFraction = (delta.' * kao.Q * delta) / max(q0, eps);
                durationS = (durationIndex - 1) * 0.010;
                savedRow = acceptedMovement.Network == network & ...
                    acceptedMovement.Controller == controllers(controllerIndex) & ...
                    acceptedMovement.Target == target & abs( ...
                    acceptedMovement.PreparationDurationS - durationS) < 1e-12;
                assert(sum(savedRow) == 1);
                savedState = acceptedMovement.StateErrorFraction(savedRow);
                savedQ = acceptedMovement.ProspectiveErrorFraction(savedRow);
                endpoint = acceptedMovement.EndpointErrorM(savedRow);
                maximumMetricDifference = max(maximumMetricDifference, ...
                    max(abs([stateFraction - savedState, ...
                    prospectiveFraction - savedQ])));
                rows = [rows; table(network, controllers(controllerIndex), ... %#ok<AGROW>
                    target, durationS, mismatchPercent, stateFraction, ...
                    prospectiveFraction, endpoint, 'VariableNames', ...
                    {'Network','Controller','Target','PreparationDurationS', ...
                    'ActiveSetMismatchPercent','StateErrorFraction', ...
                    'ProspectiveErrorFraction','EndpointErrorM'})];
            end
            for checkIndex = 1:numel(checkDurations)
                batch = (checkIndex - 1) * model.nMovements + target;
                actualEndpoint = squeeze(checkHand(end, [1, 3], batch)).';
                directEndpoint = norm(actualEndpoint - ...
                    squeeze(idealHand(end, [1, 3], target)).');
                savedRow = acceptedMovement.Network == network & ...
                    acceptedMovement.Controller == controllers(controllerIndex) & ...
                    acceptedMovement.Target == target & abs( ...
                    acceptedMovement.PreparationDurationS - ...
                    checkDurations(checkIndex)) < 1e-12;
                maximumEndpointDifference = max(maximumEndpointDifference, ...
                    abs(directEndpoint - acceptedMovement.EndpointErrorM(savedRow)));
            end
        end
    end
    passed = maximumMetricDifference <= 1e-12 && ...
        maximumEndpointDifference <= 1e-12;
    assert(passed);
    validation = table(network, "Stage 2A/Kao saved-output reproduction", ...
        max(maximumMetricDifference, maximumEndpointDifference), 1e-12, ...
        passed, 'VariableNames', {'Network','Check','MaximumDifference', ...
        'Tolerance','Passed'});
end

function [networkSummary, activeCurve, frozenSummary, frozenCurve] = ...
        summarize_stage1(target, overlap, curve, frozen, mismatch, diagnostic)
    networks = unique(target.Network);
    networkSummary = table();
    frozenSummary = table();
    for network = networks.'
        rows = target.Network == network;
        pairRows = overlap.Network == network;
        networkSummary = [networkSummary; table(network, ... %#ok<AGROW>
            median(target.SwitchingFraction(rows)), ...
            median(target.TransitionsPerNeuronPerS(rows)), ...
            median(target.MeanActiveFraction(rows)), ...
            median(overlap.UnionSetJaccard(pairRows)), ...
            'VariableNames', {'Network','MedianSwitchingFraction', ...
            'MedianTransitionsPerNeuronPerS','MedianActiveFraction', ...
            'MedianUnionSetJaccard'})];
        rows = frozen.Network == network;
        frozenSummary = [frozenSummary; table(network, ... %#ok<AGROW>
            median(frozen.CorticalRateNRMSE(rows)), ...
            median(frozen.TorqueNRMSE(rows)), ...
            median(frozen.HandTrajectoryNRMSE(rows)), ...
            median(frozen.EndpointErrorM(rows)), ...
            'VariableNames', {'Network','MedianCorticalRateNRMSE', ...
            'MedianTorqueNRMSE','MedianHandTrajectoryNRMSE', ...
            'MedianEndpointErrorM'})];
    end
    activeCurve = aggregate_target_curves(curve, 'MovementTimeS', ...
        'ActiveFraction');
    frozenCurve = aggregate_target_curves(mismatch, 'MovementTimeS', ...
        'HandPositionDifferenceM');
    networkSummary = add_scalar_bootstrap(networkSummary, diagnostic, 1);
    frozenSummary = add_scalar_bootstrap(frozenSummary, diagnostic, 2);
end

function output = aggregate_target_curves(input, timeName, valueName)
    networks = unique(input.Network);
    times = unique(input.(timeName));
    output = table();
    for network = networks.'
        values = zeros(numel(times), 1);
        for timeIndex = 1:numel(times)
            rows = input.Network == network & ...
                input.(timeName) == times(timeIndex);
            values(timeIndex) = median(input.(valueName)(rows));
        end
        output = [output; table(repmat(network, numel(times), 1), times, ... %#ok<AGROW>
            values, 'VariableNames', {'Network', timeName, valueName})];
    end
end

function output = add_scalar_bootstrap(input, diagnostic, seedOffset)
    output = input;
    variables = input.Properties.VariableNames(2:end);
    for index = 1:numel(variables)
        summary = bootstrap_network_median(input.(variables{index}), ...
            diagnostic.bootstrapSamples, diagnostic.bootstrapSeed + ...
            100 * seedOffset + index);
        output.([variables{index}, 'AcrossNetworkMedian']) = ...
            repmat(summary.median, height(output), 1);
        output.([variables{index}, 'BootstrapSE']) = ...
            repmat(summary.standardError, height(output), 1);
    end
end

function [network, ensemble, timing] = summarize_preparation(target, diagnostic)
    controllers = unique(target.Controller, 'stable');
    networks = unique(target.Network);
    durations = unique(target.PreparationDurationS);
    metrics = {'ActiveSetMismatchPercent','StateErrorFraction', ...
        'ProspectiveErrorFraction','EndpointErrorM'};
    network = table();
    for controllerIndex = 1:numel(controllers)
        for networkIndex = 1:numel(networks)
            for durationIndex = 1:numel(durations)
                selected = target.Controller == controllers(controllerIndex) & ...
                    target.Network == networks(networkIndex) & ...
                    target.PreparationDurationS == durations(durationIndex);
                values = cellfun(@(name) median(target.(name)(selected)), ...
                    metrics);
                network = [network; table(networks(networkIndex), ... %#ok<AGROW>
                    controllers(controllerIndex), durations(durationIndex), ...
                    values(1), values(2), values(3), values(4), ...
                    'VariableNames', {'Network','Controller', ...
                    'PreparationDurationS', metrics{:}})]; %#ok<CCAT>
            end
        end
    end
    ensemble = table();
    for controllerIndex = 1:numel(controllers)
        for durationIndex = 1:numel(durations)
            selected = network.Controller == controllers(controllerIndex) & ...
                network.PreparationDurationS == durations(durationIndex);
            for metricIndex = 1:numel(metrics)
                summary = bootstrap_network_median( ...
                    network.(metrics{metricIndex})(selected), ...
                    diagnostic.bootstrapSamples, diagnostic.bootstrapSeed + ...
                    1000 * controllerIndex + 100 * durationIndex + metricIndex);
                ensemble = [ensemble; table(controllers(controllerIndex), ... %#ok<AGROW>
                    durations(durationIndex), string(metrics{metricIndex}), ...
                    summary.median, summary.standardError, summary.minimum, ...
                    summary.maximum, 'VariableNames', {'Controller', ...
                    'PreparationDurationS','Metric','Median','BootstrapSE', ...
                    'Minimum','Maximum'})];
            end
        end
    end
    timing = table();
    for controllerIndex = 1:numel(controllers)
        for networkIndex = 1:numel(networks)
            selected = network.Controller == controllers(controllerIndex) & ...
                network.Network == networks(networkIndex);
            current = sortrows(network(selected, :), 'PreparationDurationS');
            active1 = first_crossing(current.PreparationDurationS, ...
                current.ActiveSetMismatchPercent <= ...
                diagnostic.activeMismatchThresholdPercent);
            active0 = first_crossing(current.PreparationDurationS, ...
                current.ActiveSetMismatchPercent == 0);
            t95 = first_crossing(current.PreparationDurationS, ...
                current.ProspectiveErrorFraction <= ...
                diagnostic.prospectiveThreshold);
            endpoint = first_crossing(current.PreparationDurationS, ...
                current.EndpointErrorM <= diagnostic.endpointThresholdM);
            timing = [timing; table(networks(networkIndex), ... %#ok<AGROW>
                controllers(controllerIndex), active1, active0, t95, endpoint, ...
                'VariableNames', {'Network','Controller', ...
                'FirstActiveMismatchAtMost1PercentS', ...
                'FirstZeroMedianActiveMismatchS','FirstT95ProspectiveS', ...
                'FirstMedianEndpointAtMost2mmS'})];
        end
    end
end

function value = first_crossing(times, condition)
    found = find(condition, 1, 'first');
    if isempty(found), value = NaN; else, value = times(found); end
end

function write_result_tables(root, results)
    names = fieldnames(results);
    for index = 1:numel(names)
        value = results.(names{index});
        if istable(value)
            writetable(value, fullfile(root, [names{index}, '.csv']));
        end
    end
    copyfile(fullfile(root, 'stage1Target.csv'), ...
        fullfile(fileparts(fileparts(root)), '..', '..', 'stage_1', ...
        'diagnostics', 'active_set_gate2', 'stage1_target_metrics.csv'));
    stage1Names = {'stage1Overlap','stage1ActiveCurve','stage1Network', ...
        'stage1ActiveCurveNetwork','frozenRegimeTarget', ...
        'frozenRegimeCurve','frozenRegimeNetwork', ...
        'frozenRegimeCurveNetwork'};
    for index = 1:numel(stage1Names)
        copyfile(fullfile(root, [stage1Names{index}, '.csv']), ...
            fullfile(fileparts(fileparts(root)), '..', '..', 'stage_1', ...
            'diagnostics', 'active_set_gate2', ...
            [stage1Names{index}, '.csv']));
    end
    copyfile(fullfile(root, 'preparationTarget.csv'), ...
        fullfile(fileparts(fileparts(root)), '..', '..', 'stage_2a', ...
        'diagnostics', 'active_set_gate2', ...
        'preparation_active_set_metrics.csv'));
    stage2aNames = {'preparationNetwork','preparationEnsemble', ...
        'preparationTiming'};
    for index = 1:numel(stage2aNames)
        copyfile(fullfile(root, [stage2aNames{index}, '.csv']), ...
            fullfile(fileparts(fileparts(root)), '..', '..', 'stage_2a', ...
            'diagnostics', 'active_set_gate2', ...
            [stage2aNames{index}, '.csv']));
    end
end

function validation = validate_figures(files)
    validation = table();
    names = fieldnames(files);
    for index = 1:numel(names)
        item = files.(names{index});
        reopened = openfig(item.fig, 'invisible');
        assert(isgraphics(reopened));
        close(reopened);
        image = imread(item.png);
        passed = size(image, 1) >= 800 && size(image, 2) >= 1200;
        assert(passed);
        validation = [validation; table(string(names{index}), ... %#ok<AGROW>
            string(item.png), string(item.fig), size(image, 2), ...
            size(image, 1), passed, 'VariableNames', {'Figure','PNG','FIG', ...
            'Width','Height','Passed'})];
    end
end

function [matched, check] = compare_manifests(before, after)
    before = sortrows(before, 'relative_path');
    after = sortrows(after, 'relative_path');
    samePaths = isequal(before.relative_path, after.relative_path);
    if samePaths
        same = before.sha256 == after.sha256 & before.bytes == after.bytes;
    else
        same = false(max(height(before), height(after)), 1);
    end
    matched = samePaths && all(same);
    check = table("All frozen canonical scopes", height(before), ...
        height(after), matched, 'VariableNames', {'Scope','FilesBefore', ...
        'FilesAfter','AllHashesMatch'});
end

function manifest = capture_frozen_manifest(projectRoot, roots)
    manifest = hash_tree(projectRoot, roots);
end

function output = build_summary(results, figures, figureValidation, ...
        frozenMatched, runtimeSeconds, diagnostic)
    stage1 = results.stage1Network;
    frozen = results.frozenRegimeNetwork;
    timing = results.preparationTiming;
    output = struct('status', 'PASS', 'networkCount', 10, ...
        'targetCount', 8, 'bootstrapResamples', ...
        diagnostic.bootstrapSamples, 'figureCount', numel(fieldnames(figures)), ...
        'stage1', struct( ...
        'switchingFractionMedian', median(stage1.MedianSwitchingFraction), ...
        'switchingFractionRange', [min(stage1.MedianSwitchingFraction), ...
        max(stage1.MedianSwitchingFraction)], ...
        'targetRowsWithSwitching', sum( ...
        results.stage1Target.SwitchingFraction > 0), ...
        'totalTargetRows', height(results.stage1Target), ...
        'maximumTargetSwitchingFraction', ...
        max(results.stage1Target.SwitchingFraction), ...
        'maximumTargetTransitions', ...
        max(results.stage1Target.TotalTransitions), ...
        'minimumTargetMeanActiveFraction', ...
        min(results.stage1Target.MeanActiveFraction), ...
        'transitionsPerNeuronPerSMedian', ...
        median(stage1.MedianTransitionsPerNeuronPerS), ...
        'unionSetJaccardMedian', median(stage1.MedianUnionSetJaccard), ...
        'unionSetJaccardRange', [min(results.stage1Overlap.UnionSetJaccard), ...
        max(results.stage1Overlap.UnionSetJaccard)]), ...
        'frozenRegime', struct( ...
        'corticalRateNRMSEMedian', median(frozen.MedianCorticalRateNRMSE), ...
        'torqueNRMSEMedian', median(frozen.MedianTorqueNRMSE), ...
        'handNRMSEMedian', median(frozen.MedianHandTrajectoryNRMSE), ...
        'endpointErrorMmMedian', 1000 * median(frozen.MedianEndpointErrorM), ...
        'targetRowsWithNonzeroMismatch', sum( ...
        results.frozenRegimeTarget.EndpointErrorM > 1e-12), ...
        'maximumCorticalRateNRMSE', ...
        max(results.frozenRegimeTarget.CorticalRateNRMSE), ...
        'maximumTorqueNRMSE', max(results.frozenRegimeTarget.TorqueNRMSE), ...
        'maximumHandNRMSE', ...
        max(results.frozenRegimeTarget.HandTrajectoryNRMSE), ...
        'maximumEndpointErrorMm', ...
        1000 * max(results.frozenRegimeTarget.EndpointErrorM)), ...
        'timing', timing_to_struct(timing), ...
        'maximumSavedOutputReproductionDifference', ...
        max(results.validation.MaximumDifference), ...
        'allValidationChecksPassed', all(results.validation.Passed), ...
        'allFrozenCanonicalHashesMatch', frozenMatched, ...
        'allFiguresReopened', all(figureValidation.Passed), ...
        'runtimeSeconds', runtimeSeconds);
end

function output = timing_to_struct(timing)
    controllers = unique(timing.Controller, 'stable');
    output = repmat(struct(), numel(controllers), 1);
    for index = 1:numel(controllers)
        rows = timing.Controller == controllers(index);
        output(index).controller = char(controllers(index));
        output(index).activeMismatchAtMost1PercentMedianMs = ...
            1000 * median(timing.FirstActiveMismatchAtMost1PercentS(rows), ...
            'omitmissing');
        output(index).zeroMedianActiveMismatchMedianMs = ...
            1000 * median(timing.FirstZeroMedianActiveMismatchS(rows), ...
            'omitmissing');
        output(index).t95ProspectiveMedianMs = ...
            1000 * median(timing.FirstT95ProspectiveS(rows), 'omitmissing');
        output(index).endpointAtMost2mmMedianMs = ...
            1000 * median(timing.FirstMedianEndpointAtMost2mmS(rows), ...
            'omitmissing');
        output(index).networksReachingActive1Percent = sum(~isnan( ...
            timing.FirstActiveMismatchAtMost1PercentS(rows)));
        output(index).networksReachingT95 = sum(~isnan( ...
            timing.FirstT95ProspectiveS(rows)));
        output(index).networksReachingEndpoint2mm = sum(~isnan( ...
            timing.FirstMedianEndpointAtMost2mmS(rows)));
    end
end

function value = normalized_rmse(actual, reference)
    numerator = sqrt(mean((actual - reference) .^ 2, 'all'));
    denominator = max(max(reference, [], 'all') - ...
        min(reference, [], 'all'), eps);
    value = numerator / denominator;
end

function write_json(path, value)
    text = jsonencode(value, PrettyPrint=true);
    file = fopen(path, 'w');
    assert(file >= 0);
    cleanup = onCleanup(@() fclose(file));
    fprintf(file, '%s\n', text);
end
