function complete = analyze_stage2b_kao_lambda_sensitivity(cfg, options)
    arguments
        cfg
        options.NetworkCount (1, 1) double = cfg.ensemble.count
        options.Lambdas (1, :) double = [0.01, 0.03, 0.1, 0.3, 1]
        options.MovementDurationsS (:, 1) double = ...
            cfg.analysis.densePreparationDurationsS
        options.SavePerNetwork (1, 1) logical = true
        options.OutputRoot string = ""
    end
    lambdas = options.Lambdas(:);
    assert(isequal(lambdas, [0.01; 0.03; 0.1; 0.3; 1]), ...
        'The authorized lambda grid must not be changed.');
    assert(options.NetworkCount >= 1 && ...
        options.NetworkCount <= cfg.ensemble.count);
    durations = options.MovementDurationsS(:);
    assert(all(durations >= 0 & durations <= ...
        cfg.preparation.maximumDurationS));
    if strlength(options.OutputRoot) == 0
        outputRoot = fullfile(cfg.resultsRoot, 'diagnostics', ...
            'lambda_sensitivity');
    else
        outputRoot = char(options.OutputRoot);
    end
    perNetworkRoot = fullfile(outputRoot, 'per_network');
    if options.SavePerNetwork && ~isfolder(perNetworkRoot)
        mkdir(perNetworkRoot);
    end
    canonicalError = readtable(fullfile(cfg.resultsRoot, 'tables', ...
        'errorTimecourse.csv'), TextType='string');
    canonicalError = canonicalError(canonicalError.Controller == ...
        "Stage 2B-Kao", :);
    canonicalMovement = readtable(fullfile(cfg.resultsRoot, 'tables', ...
        'movement.csv'), TextType='string');
    canonicalMovement = canonicalMovement(canonicalMovement.Controller == ...
        "Stage 2B-Kao", :);
    controllerParts = cell(options.NetworkCount, 1);
    targetParts = cell(options.NetworkCount, 1);
    timecourseParts = cell(options.NetworkCount, 1);
    movementParts = cell(options.NetworkCount, 1);
    networkParts = cell(options.NetworkCount, 1);
    reproductionParts = cell(options.NetworkCount, 1);
    startTime = tic;
    for network = 1:options.NetworkCount
        stage1Path = fullfile(cfg.ensemble.stage1Root, ...
            sprintf('network_%02d.mat', network));
        saved = load(stage1Path, 'model', 'networkRow');
        assert(saved.networkRow.Pass && ...
            saved.networkRow.AcceptedMember == network);
        model = saved.model;
        idealCortex = simulate_published_cortex(model, model.xstar, true);
        [~, idealHand] = simulate_published_arm(model, idealCortex.torque);
        nLambda = numel(lambdas);
        controllerRows = cell(nLambda, 1);
        targetRows = cell(nLambda, 1);
        timecourseRows = cell(nLambda, 1);
        movementRows = cell(nLambda, 1);
        networkRows = cell(nLambda, 1);
        reproductionRows = cell(nLambda, 1);
        KByLambda = zeros(model.n, model.n, nLambda);
        for lambdaIndex = 1:nLambda
            lambda = lambdas(lambdaIndex);
            lambdaCfg = cfg;
            lambdaCfg.controller.lambda = lambda;
            controller = derive_stage2b_kao_controller(model, lambdaCfg);
            recomputed = derive_stage2b_kao_controller(model, lambdaCfg);
            recomputeKDifference = max(abs(controller.K - recomputed.K), ...
                [], 'all');
            KByLambda(:, :, lambdaIndex) = controller.K;
            [maximumTargetSpectralAbscissa, maximumTargetFixedResidual] = ...
                validate_targets(model, controller);
            gainSpectral = norm(controller.K, 2);
            gainFrobenius = norm(controller.K, 'fro');
            preparation = simulate_stage2b_kao_preparation(model, ...
                controller, cfg.preparation.maximumDurationS);
            [targetTable, timecourseTable] = preparation_metrics(model, ...
                controller, preparation, network, lambda, gainSpectral, ...
                gainFrobenius);
            movementTable = movement_metrics(model, controller, preparation, ...
                durations, idealHand, network, lambda);
            [maximumCanonicalGainDifference, ...
                maximumCanonicalPDifference, ...
                maximumCanonicalQDifference, ...
                maximumCanonicalInputDifference] = ...
                canonical_controller_difference(cfg, network, controller, lambda);
            [maximumCanonicalProspectiveDifference, ...
                maximumCanonicalEndpointDifference] = ...
                canonical_result_difference(canonicalError, ...
                canonicalMovement, timecourseTable, movementTable, ...
                network, lambda);
            controllerRows{lambdaIndex} = table(network, lambda, ...
                gainSpectral, gainFrobenius, controller.careResidualRelative, ...
                max(real(controller.closedLoopEigenvalues)), ...
                maximumTargetSpectralAbscissa, maximumTargetFixedResidual, ...
                recomputeKDifference, 'VariableNames', {'Network','Lambda', ...
                'GainSpectralNorm','GainFrobeniusNorm', ...
                'CareResidualRelative','MaximumCareClosedLoopRealEigenvalue', ...
                'MaximumTargetJacobianRealEigenvaluePerS', ...
                'MaximumTargetFixedPointResidual','RecomputeKDifference'});
            targetRows{lambdaIndex} = targetTable;
            timecourseRows{lambdaIndex} = timecourseTable;
            movementRows{lambdaIndex} = movementTable;
            networkRows{lambdaIndex} = aggregate_network(targetTable, ...
                movementTable, network, lambda, gainSpectral, gainFrobenius);
            reproductionRows{lambdaIndex} = table(network, lambda, ...
                maximumCanonicalGainDifference, maximumCanonicalPDifference, ...
                maximumCanonicalQDifference, maximumCanonicalInputDifference, ...
                maximumCanonicalProspectiveDifference, ...
                maximumCanonicalEndpointDifference, 'VariableNames', ...
                {'Network','Lambda','MaximumCanonicalGainDifference', ...
                'MaximumCanonicalRiccatiDifference', ...
                'MaximumCanonicalQDifference', ...
                'MaximumCanonicalInputDifference', ...
                'MaximumCanonicalProspectiveDifference', ...
                'MaximumCanonicalEndpointDifference'});
        end
        controllerParts{network} = vertcat(controllerRows{:});
        targetParts{network} = vertcat(targetRows{:});
        timecourseParts{network} = vertcat(timecourseRows{:});
        movementParts{network} = vertcat(movementRows{:});
        networkParts{network} = vertcat(networkRows{:});
        reproductionParts{network} = vertcat(reproductionRows{:});
        if options.SavePerNetwork
            networkResult = struct('controller', controllerParts{network}, ...
                'target', targetParts{network}, ...
                'timecourse', timecourseParts{network}, ...
                'movement', movementParts{network}, ...
                'network', networkParts{network}, ...
                'reproduction', reproductionParts{network});
            lambdaValues = lambdas;
            stage1Sha256 = string(sha256_file(stage1Path));
            perNetworkPath = fullfile(perNetworkRoot, sprintf( ...
                'network_%02d_lambda_sensitivity.mat', network));
            save(perNetworkPath, 'networkResult', 'KByLambda', ...
                'lambdaValues', 'stage1Sha256', '-v7.3');
            reloaded = load(perNetworkPath, 'KByLambda', 'lambdaValues');
            assert(isequal(reloaded.lambdaValues, lambdaValues));
            reloadDifference = max(abs(reloaded.KByLambda - KByLambda), ...
                [], 'all');
            controllerParts{network}.ReloadKDifference(:) = reloadDifference;
            networkResult.controller = controllerParts{network};
            save(perNetworkPath, 'networkResult', 'KByLambda', ...
                'lambdaValues', 'stage1Sha256', '-v7.3');
        else
            controllerParts{network}.ReloadKDifference(:) = 0;
        end
        fprintf(['Lambda sensitivity network %02d/%02d complete: ' ...
            'max CARE %.3e; max target eig %.3e/s.\n'], network, ...
            options.NetworkCount, ...
            max(controllerParts{network}.CareResidualRelative), ...
            max(controllerParts{network}.MaximumTargetJacobianRealEigenvaluePerS));
    end
    results.controller = vertcat(controllerParts{:});
    results.target = vertcat(targetParts{:});
    results.timecourse = vertcat(timecourseParts{:});
    results.movement = vertcat(movementParts{:});
    results.network = vertcat(networkParts{:});
    results.reproduction = vertcat(reproductionParts{:});
    if options.NetworkCount >= 2
        results.ensemble = summarize_ensemble(cfg, results.network, lambdas);
    else
        results.ensemble = table();
    end
    complete = struct('cfg', cfg, 'lambdas', lambdas, ...
        'movementDurationsS', durations, 'results', results, ...
        'networkCount', options.NetworkCount, ...
        'runtimeSeconds', toc(startTime));
end

function [maximumSpectral, maximumResidual] = validate_targets(model, controller)
    spectral = zeros(model.nMovements, 1);
    residual = zeros(model.nMovements, 1);
    for target = 1:model.nMovements
        xstar = model.xstar(:, target);
        D = diag(double(xstar > 0));
        J = (-eye(model.n) + ...
            (model.W + controller.effectiveFeedback) * D) / model.tau;
        spectral(target) = max(real(eig(J)));
        rates = max(xstar, 0);
        derivative = -xstar + model.W * rates + model.h + ...
            controller.tonicInput(:, target) + ...
            controller.effectiveFeedback * ...
            (rates - max(model.xstar(:, target), 0));
        residual(target) = norm(derivative);
    end
    maximumSpectral = max(spectral);
    maximumResidual = max(residual);
    assert(maximumSpectral < 0, ...
        'A target fixed point is not locally stable.');
    assert(maximumResidual < 1e-11, ...
        'A target fixed-point derivative is not numerically zero.');
end

function [targetTable, timecourseTable] = preparation_metrics(model, ...
        controller, preparation, network, lambda, gainSpectral, gainFrobenius)
    nTime = numel(preparation.timesS);
    nTargets = model.nMovements;
    timecourseParts = cell(nTargets, 1);
    targetParts = cell(nTargets, 1);
    feedbackNorm = squeeze(vecnorm(preparation.feedback, 2, 2));
    for target = 1:nTargets
        delta = preparation.states(:, :, target) - ...
            model.xstar(:, target).';
        delta0 = model.spontaneous - model.xstar(:, target);
        prospective = sum((delta * controller.Q) .* delta, 2) / ...
            max(delta0.' * controller.Q * delta0, eps);
        reachedIndex = find(prospective <= 0.05, 1, 'first');
        reached = ~isempty(reachedIndex);
        if reached
            t95S = preparation.timesS(reachedIndex);
        else
            t95S = NaN;
        end
        squaredNorm = feedbackNorm(:, target) .^ 2;
        rawEffort = trapz(preparation.timesS, squaredNorm);
        feedbackRms = sqrt(rawEffort / ...
            cfg_duration(preparation.timesS));
        peakFeedback = max(feedbackNorm(:, target));
        targetParts{target} = table(network, target, lambda, ...
            gainSpectral, gainFrobenius, t95S, reached, rawEffort, ...
            lambda * rawEffort, feedbackRms, peakFeedback, ...
            'VariableNames', {'Network','Target','Lambda', ...
            'GainSpectralNorm','GainFrobeniusNorm','T95S','T95Reached', ...
            'RawUnweightedFeedbackEffort','LambdaWeightedFeedbackEffort', ...
            'FeedbackRmsNorm','PeakFeedbackNorm'});
        timecourseParts{target} = table(repmat(network, nTime, 1), ...
            repmat(target, nTime, 1), repmat(lambda, nTime, 1), ...
            preparation.timesS, prospective, feedbackNorm(:, target), ...
            'VariableNames', {'Network','Target','Lambda', ...
            'PreparationTimeS','ProspectiveErrorFraction','FeedbackNorm'});
    end
    targetTable = vertcat(targetParts{:});
    timecourseTable = vertcat(timecourseParts{:});
end

function duration = cfg_duration(timesS)
    duration = timesS(end) - timesS(1);
    assert(duration > 0);
end

function output = movement_metrics(model, controller, preparation, durations, ...
        idealHand, network, lambda)
    indices = round(durations / model.samplingDt) + 1;
    selected = preparation.states(indices, :, :);
    goStates = reshape(permute(selected, [2, 3, 1]), model.n, []);
    cortex = simulate_published_cortex(model, goStates, false);
    [~, hand] = simulate_published_arm(model, cortex.torque);
    nRows = numel(durations) * model.nMovements;
    networkColumn = repmat(network, nRows, 1);
    targetColumn = zeros(nRows, 1);
    lambdaColumn = repmat(lambda, nRows, 1);
    durationColumn = zeros(nRows, 1);
    endpoint = zeros(nRows, 1);
    prospective = zeros(nRows, 1);
    row = 0;
    for durationIndex = 1:numel(durations)
        for target = 1:model.nMovements
            row = row + 1;
            batch = (durationIndex - 1) * model.nMovements + target;
            delta = goStates(:, batch) - model.xstar(:, target);
            delta0 = model.spontaneous - model.xstar(:, target);
            actualHand = hand(:, [1, 3], batch);
            referenceHand = idealHand(:, [1, 3], target);
            targetColumn(row) = target;
            durationColumn(row) = durations(durationIndex);
            endpoint(row) = norm(actualHand(end, :) - referenceHand(end, :));
            prospective(row) = delta.' * controller.Q * delta / ...
                max(delta0.' * controller.Q * delta0, eps);
        end
    end
    output = table(networkColumn, targetColumn, lambdaColumn, durationColumn, ...
        prospective, endpoint, 'VariableNames', {'Network','Target','Lambda', ...
        'PreparationDurationS','ProspectiveErrorFraction','EndpointErrorM'});
end

function [gainDifference, pDifference, qDifference, inputDifference] = ...
        canonical_controller_difference(cfg, network, controller, lambda)
    gainDifference = NaN;
    pDifference = NaN;
    qDifference = NaN;
    inputDifference = NaN;
    if lambda ~= 0.1
        return
    end
    path = fullfile(cfg.resultsRoot, 'ensemble', sprintf( ...
        'network_%02d_stage2b_kao_controller.mat', network));
    canonical = load(path, 'controllerSaved');
    gainDifference = max(abs(controller.K - canonical.controllerSaved.K), ...
        [], 'all');
    pDifference = max(abs(controller.P - canonical.controllerSaved.P), ...
        [], 'all');
    qDifference = max(abs(controller.Q - canonical.controllerSaved.Q), ...
        [], 'all');
    inputDifference = max(abs(controller.targetInput - ...
        canonical.controllerSaved.targetInput), [], 'all');
end

function [prospectiveDifference, endpointDifference] = ...
        canonical_result_difference(canonicalError, canonicalMovement, ...
        currentError, currentMovement, network, lambda)
    prospectiveDifference = NaN;
    endpointDifference = NaN;
    if lambda ~= 0.1
        return
    end
    referenceError = canonicalError(canonicalError.Network == network, :);
    referenceError = sortrows(referenceError, {'Target','PreparationTimeS'});
    currentError = sortrows(currentError, {'Target','PreparationTimeS'});
    assert(height(referenceError) == height(currentError));
    prospectiveDifference = max(abs(referenceError.ProspectiveErrorFraction - ...
        currentError.ProspectiveErrorFraction));
    durationMatch = ismembertol(canonicalMovement.PreparationDurationS, ...
        currentMovement.PreparationDurationS, 1e-12, 'DataScale', 1);
    referenceMovement = canonicalMovement(canonicalMovement.Network == ...
        network & durationMatch, :);
    referenceMovement = sortrows(referenceMovement, ...
        {'Target','PreparationDurationS'});
    currentMovement = sortrows(currentMovement, ...
        {'Target','PreparationDurationS'});
    assert(height(referenceMovement) == height(currentMovement));
    endpointDifference = max(abs(referenceMovement.EndpointErrorM - ...
        currentMovement.EndpointErrorM));
end

function output = aggregate_network(targetTable, movementTable, network, ...
        lambda, gainSpectral, gainFrobenius)
    t95 = targetTable.T95S;
    reached = isfinite(t95);
    if any(reached)
        medianT95 = median(t95(reached));
    else
        medianT95 = NaN;
    end
    endpoint100 = movementTable.EndpointErrorM(abs( ...
        movementTable.PreparationDurationS - 0.100) < 1e-12);
    endpoint200 = movementTable.EndpointErrorM(abs( ...
        movementTable.PreparationDurationS - 0.200) < 1e-12);
    if isempty(endpoint100)
        medianEndpoint100 = NaN;
    else
        medianEndpoint100 = median(endpoint100) * 1000;
    end
    if isempty(endpoint200)
        medianEndpoint200 = NaN;
    else
        medianEndpoint200 = median(endpoint200) * 1000;
    end
    output = table(network, lambda, gainSpectral, gainFrobenius, ...
        medianT95 * 1000, sum(~reached), ...
        median(targetTable.RawUnweightedFeedbackEffort), ...
        median(targetTable.LambdaWeightedFeedbackEffort), ...
        median(targetTable.FeedbackRmsNorm), ...
        median(targetTable.PeakFeedbackNorm), medianEndpoint100, ...
        medianEndpoint200, 'VariableNames', {'Network','Lambda', ...
        'GainSpectralNorm','GainFrobeniusNorm','TargetMedianT95Ms', ...
        'NotReachedTargetCount','TargetMedianRawEffort', ...
        'TargetMedianWeightedEffort','TargetMedianFeedbackRmsNorm', ...
        'TargetMedianPeakFeedbackNorm','TargetMedianEndpoint100Mm', ...
        'TargetMedianEndpoint200Mm'});
end

function output = summarize_ensemble(cfg, networkTable, lambdas)
    metrics = {'GainSpectralNorm','GainFrobeniusNorm','TargetMedianT95Ms', ...
        'TargetMedianRawEffort','TargetMedianWeightedEffort', ...
        'TargetMedianFeedbackRmsNorm','TargetMedianPeakFeedbackNorm', ...
        'TargetMedianEndpoint100Mm','TargetMedianEndpoint200Mm'};
    rows = cell(numel(lambdas) * numel(metrics), 1);
    row = 0;
    for lambdaIndex = 1:numel(lambdas)
        lambda = lambdas(lambdaIndex);
        selected = networkTable(networkTable.Lambda == lambda, :);
        for metricIndex = 1:numel(metrics)
            row = row + 1;
            metric = metrics{metricIndex};
            values = selected.(metric);
            finite = isfinite(values);
            assert(sum(finite) >= 2, ...
                'Too few finite network values for bootstrap.');
            summary = bootstrap_network_median(values(finite), ...
                cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + ...
                30000 + 100 * lambdaIndex + metricIndex);
            rows{row} = table(lambda, string(metric), summary.median, ...
                summary.standardError, summary.minimum, summary.maximum, ...
                summary.nNetworks, sum(~finite), ...
                sum(selected.NotReachedTargetCount), ...
                'VariableNames', {'Lambda','Metric','Median', ...
                'BootstrapSE','Minimum','Maximum','FiniteNetworks', ...
                'NonfiniteNetworks','NotReachedTargets'});
        end
    end
    output = vertcat(rows{:});
end
