function audit = audit_stage2b_cerebellum_gate4b(cfg)
    ensure_directories(cfg);
    cfgKao = stage_2b_kao_config(cfg.projectRoot);
    controllerRows = cell(cfg.ensemble.count, 1);
    targetRows = cell(cfg.ensemble.count, 1);
    effortRows = cell(cfg.ensemble.count, 1);
    performanceRows = cell(cfg.ensemble.count, 1);
    t95Rows = cell(cfg.ensemble.count, 1);
    upstreamRows = cell(cfg.ensemble.count, 1);

    for network = 1:cfg.ensemble.count
        stage1Path = fullfile(cfg.ensemble.stage1Root, ...
            sprintf('network_%02d.mat', network));
        stage2aPath = fullfile(cfg.ensemble.stage2aRoot, ...
            sprintf('network_%02d_stage2a.mat', network));
        kaoPath = fullfile(cfgKao.resultsRoot, 'ensemble', ...
            sprintf('network_%02d_stage2b_kao_controller.mat', network));
        cachePath = fullfile(cfg.workResultsRoot, 'per_network', ...
            sprintf('network_%02d_gate3_result.mat', network));
        assert(isfile(stage1Path) && isfile(stage2aPath) && ...
            isfile(kaoPath) && isfile(cachePath));

        stage1 = load(stage1Path, 'model');
        stage2a = load(stage2aPath, 'networkResult');
        kaoSaved = load(kaoPath, 'controllerSaved');
        cached = load(cachePath, 'current', 'cacheMetadata');
        model = stage1.model;
        kao = kaoSaved.controllerSaved;
        controller = derive_stage2b_cerebellum_controller(model, cfg);

        [controllerRows{network}, targetRows{network}] = structural_checks( ...
            cfg, model, controller, kao, network);
        [effortRows{network}, preparationFinite] = effort_checks( ...
            model, controller, network);
        [performanceRows{network}, t95Rows{network}, cachedFinite] = ...
            recover_cached_performance(cached.current, network);

        tonicDifference = max(abs(controller.tonicInput - ...
            stage2a.networkResult.tonicInput), [], 'all');
        stage1Hash = string(sha256_file(stage1Path));
        stage2aHash = string(sha256_file(stage2aPath));
        stage1HashMatch = stage1Hash == cached.cacheMetadata.Stage1Sha256;
        stage2aHashMatch = stage2aHash == cached.cacheMetadata.Stage2aSha256;
        timingMatch = abs(model.dt - 0.0002) <= eps && ...
            abs(model.samplingDt - 0.001) <= eps && ...
            abs(model.tau - 0.150) <= eps;
        upstreamRows{network} = table(network, stage1Hash, stage2aHash, ...
            stage1HashMatch, stage2aHashMatch, tonicDifference, ...
            controllerRows{network}.MaximumADifferenceFromKao, ...
            controllerRows{network}.MaximumQDifferenceFromKao, timingMatch, ...
            preparationFinite, cachedFinite, ...
            'VariableNames', {'Network','Stage1Sha256','Stage2aSha256', ...
            'Stage1CacheHashMatch','Stage2aCacheHashMatch', ...
            'MaximumTonicInputDifference','MaximumADifferenceFromKao', ...
            'MaximumQDifferenceFromKao','TimingMatch','PreparationFinite', ...
            'CachedPerformanceFinite'});

        controllerPath = fullfile(cfg.currentEnsembleRoot, ...
            sprintf('network_%02d_stage2b_cerebellum_controller.mat', network));
        controllerSaved = controller;
        save(controllerPath, 'controllerSaved', 'network', '-v7.3');
        reloaded = load(controllerPath, 'controllerSaved');
        controllerRows{network}.MaximumControllerReloadDifference = ...
            max(abs(controller.K - reloaded.controllerSaved.K), [], 'all');
    end

    audit.controllerValidation = vertcat(controllerRows{:});
    audit.targetValidation = vertcat(targetRows{:});
    audit.effortTarget = vertcat(effortRows{:});
    audit.performanceNetwork = vertcat(performanceRows{:});
    audit.t95Target = vertcat(t95Rows{:});
    audit.upstreamVerification = vertcat(upstreamRows{:});
    audit.performanceEnsemble = summarize_performance(cfg, ...
        audit.performanceNetwork);
    [audit.t95Network, audit.t95Summary] = summarize_t95(cfg, audit.t95Target);
    [audit.effortNetwork, audit.effortSummary] = summarize_effort(cfg, ...
        audit.effortTarget, audit.controllerValidation);
    audit.frozenComparison = frozen_comparison(cfgKao, ...
        audit.performanceEnsemble);
    audit.acceptance = acceptance_decision(cfg, audit);
    write_audit_outputs(cfg, audit);
end

function ensure_directories(cfg)
    paths = {cfg.resultsRoot, cfg.currentResultsRoot, cfg.currentAuditRoot, ...
        cfg.currentTablesRoot, cfg.currentEnsembleRoot, cfg.plotsRoot, ...
        cfg.plotsPngRoot, cfg.plotsFigRoot};
    for index = 1:numel(paths)
        if ~exist(paths{index}, 'dir')
            mkdir(paths{index});
        end
    end
end

function [row, targets] = structural_checks(cfg, model, controller, kao, network)
    n = model.n;
    k = cfg.controller.actuatorDimension;
    [vectors, values] = eig(controller.Q, 'vector');
    [values, order] = sort(real(values), 'descend');
    expectedB = vectors(:, order(1:k));
    top13Fraction = sum(values(1:k)) / sum(values);
    k95 = find(cumsum(values) / sum(values) >= 0.95, 1, 'first');
    actuatorDifference = norm(controller.B - expectedB, 'fro');
    orthonormalError = norm(controller.B.' * controller.B - eye(k), 'fro');
    rError = norm(controller.R - cfg.controller.lambda * eye(k), 'fro');
    gainSignError = norm(controller.K + ...
        (controller.R \ (controller.B.' * controller.P)), 'fro') / ...
        max(norm(controller.K, 'fro'), eps);
    feedbackFactorError = norm(controller.effectiveFeedback - ...
        controller.B * controller.K, 'fro');
    maximumADifferenceFromKao = max(abs(controller.A - kao.A), [], 'all');
    maximumQDifferenceFromKao = max(abs(controller.Q - kao.Q), [], 'all');
    careResidual = controller.A.' * controller.P + ...
        controller.P * controller.A - controller.P * controller.B * ...
        (controller.R \ (controller.B.' * controller.P)) + controller.Q;
    careResidualRelative = norm(careResidual, 'fro') / ...
        max(norm(controller.Q, 'fro'), eps);

    openEigenvalues = eig(controller.A);
    pbhModes = find(real(openEigenvalues) >= ...
        -cfg.validation.pbhRelativeTolerance);
    minimumPbhMargin = 1;
    for index = 1:numel(pbhModes)
        lambda = openEigenvalues(pbhModes(index));
        matrix = [lambda * eye(n) - controller.A, controller.B];
        singularValues = svd(matrix);
        minimumPbhMargin = min(minimumPbhMargin, ...
            singularValues(end) / max(norm(matrix, 2), eps));
    end
    stabilizable = isempty(pbhModes) || ...
        minimumPbhMargin > cfg.validation.pbhRelativeTolerance;

    target = (1:model.nMovements).';
    fixedResidual = zeros(model.nMovements, 1);
    feedbackError = zeros(model.nMovements, 1);
    spectralAbscissa = zeros(model.nMovements, 1);
    for movement = 1:model.nMovements
        xstar = model.xstar(:, movement);
        rstar = max(xstar, 0);
        feedback = controller.effectiveFeedback * (rstar - rstar);
        derivative = (-xstar + model.W * rstar + model.h + ...
            controller.tonicInput(:, movement) + feedback) / model.tau;
        D = diag(double(xstar > 0));
        J = (-eye(n) + (model.W + controller.effectiveFeedback) * D) ...
            / model.tau;
        fixedResidual(movement) = norm(derivative);
        feedbackError(movement) = norm(feedback);
        spectralAbscissa(movement) = max(real(eig(J)));
    end
    allTargetChecksPass = fixedResidual < cfg.validation.fixedPointTolerance & ...
        feedbackError <= cfg.validation.feedbackZeroTolerance & ...
        spectralAbscissa < 0;
    targets = table(repmat(network, model.nMovements, 1), target, ...
        fixedResidual, feedbackError, spectralAbscissa, allTargetChecksPass, ...
        'VariableNames', {'Network','Target','FixedPointResidualNormPerS', ...
        'FeedbackErrorNormAtTarget','SpectralAbscissaPerS', ...
        'AllTargetChecksPass'});

    boundaryPass = controller.eigGap13_14 > controller.eigBoundaryTolerance;
    allStructuralChecksPass = abs(top13Fraction - ...
        controller.qPotencyTop13) < eps && k == 13 && ...
        all(size(controller.B) == [200, 13]) && rank(controller.B) == 13 && ...
        orthonormalError < cfg.validation.orthonormalTolerance && ...
        rError < cfg.validation.upstreamEqualityTolerance && ...
        gainSignError < cfg.validation.upstreamEqualityTolerance && ...
        feedbackFactorError < cfg.validation.upstreamEqualityTolerance && ...
        maximumADifferenceFromKao < cfg.validation.upstreamEqualityTolerance && ...
        maximumQDifferenceFromKao < cfg.validation.upstreamEqualityTolerance && ...
        boundaryPass && stabilizable && all(isfinite(controller.P), 'all') && ...
        all(isfinite(controller.K), 'all') && ...
        careResidualRelative < cfg.validation.careResidualTolerance && ...
        max(real(controller.closedLoopEigenvalues)) < 0 && ...
        all(allTargetChecksPass);
    row = table(network, top13Fraction, k95, values(13), values(14), ...
        controller.eigGap13_14, controller.eigGap13_14Relative, ...
        controller.eigBoundaryTolerance, boundaryPass, size(controller.B, 1), ...
        size(controller.B, 2), rank(controller.B), actuatorDifference, ...
        orthonormalError, rError, gainSignError, feedbackFactorError, ...
        maximumADifferenceFromKao, maximumQDifferenceFromKao, ...
        max(real(openEigenvalues)), numel(pbhModes), minimumPbhMargin, ...
        stabilizable, careResidualRelative, ...
        max(real(controller.closedLoopEigenvalues)), ...
        norm(controller.K, 'fro'), norm(controller.K, 2), ...
        norm(controller.effectiveFeedback, 'fro'), ...
        norm(controller.effectiveFeedback, 2), max(fixedResidual), ...
        max(feedbackError), max(spectralAbscissa), 0, allStructuralChecksPass, ...
        'VariableNames', {'Network','Top13PotencyFraction','K95', ...
        'QEigenvalue13','QEigenvalue14','EigenGap13Minus14', ...
        'RelativeEigenGap13Minus14','EigenBoundaryTolerance', ...
        'EigenBoundaryPass','ActuatorRows','ActuatorColumns','ActuatorRank', ...
        'ActuatorExactDifference','OrthonormalError','RExactDifference', ...
        'GainSignRelativeError','FeedbackFactorError', ...
        'MaximumADifferenceFromKao','MaximumQDifferenceFromKao', ...
        'MaximumOpenLoopRealEigenvalue','PbhModesChecked', ...
        'MinimumPbhRelativeMargin','Stabilizable','CareResidualRelative', ...
        'MaximumCareClosedLoopRealEigenvalue','GainFrobeniusNorm', ...
        'GainSpectralNorm','FeedbackFrobeniusNorm','FeedbackSpectralNorm', ...
        'MaximumFixedPointResidualPerS','MaximumFeedbackErrorAtTarget', ...
        'MaximumTargetJacobianRealEigenvalue','MaximumControllerReloadDifference', ...
        'AllStructuralChecksPass'});
end

function [rows, finitePass] = effort_checks(model, controller, network)
    preparation = simulate_stage2b_kao_preparation(model, controller, 0.500);
    feedbackNorm = squeeze(vecnorm(preparation.feedback, 2, 2));
    feedbackRms = sqrt(mean(feedbackNorm .^ 2, 1)).';
    feedbackPeak = max(feedbackNorm, [], 1).';
    rawEffort = (model.samplingDt / model.tau) * ...
        sum(feedbackNorm .^ 2, 1).';
    lambdaWeightedEffort = controller.lambda * rawEffort;
    finitePass = all(isfinite(preparation.states), 'all') && ...
        all(isfinite(preparation.feedback), 'all') && ...
        all(isfinite(feedbackRms)) && all(isfinite(feedbackPeak)) && ...
        all(isfinite(rawEffort));
    rows = table(repmat(network, model.nMovements, 1), ...
        (1:model.nMovements).', feedbackRms, feedbackPeak, rawEffort, ...
        lambdaWeightedEffort, repmat(finitePass, model.nMovements, 1), ...
        'VariableNames', {'Network','Target','FeedbackRmsNorm', ...
        'FeedbackPeakNorm','RawUnweightedEffort','LambdaWeightedEffort', ...
        'Finite'});
end

function [performance, t95, finitePass] = recover_cached_performance(current, network)
    controllers = ["Stage 2A"; "Stage 2B-Kao"; "Stage 2B-Cerebellum"];
    durations = unique(current.movement.PreparationDurationS);
    rows = cell(numel(controllers) * numel(durations), 1);
    row = 0;
    for controller = controllers.'
        for duration = durations.'
            row = row + 1;
            selected = current.movement.Controller == controller & ...
                abs(current.movement.PreparationDurationS - duration) < 1e-12;
            data = current.movement(selected, :);
            assert(height(data) == 8);
            rows{row} = table(network, controller, duration, ...
                median(data.ProspectiveErrorFraction), ...
                median(data.EndpointErrorM), 'VariableNames', {'Network', ...
                'Controller','PreparationDurationS', ...
                'ProspectiveErrorFraction','EndpointErrorM'});
        end
    end
    performance = vertcat(rows{:});

    t95Controllers = ["Stage 2B-Kao"; "Stage 2B-Cerebellum"];
    t95Rows = cell(16, 1);
    row = 0;
    for controller = t95Controllers.'
        for target = 1:8
            row = row + 1;
            selected = current.errorTimecourse.Controller == controller & ...
                current.errorTimecourse.Target == target;
            data = sortrows(current.errorTimecourse(selected, :), ...
                'PreparationTimeS');
            found = find(data.ProspectiveErrorFraction <= 0.05, 1, 'first');
            reached = ~isempty(found);
            firstCrossing = NaN;
            if reached
                firstCrossing = data.PreparationTimeS(found);
            end
            t95Rows{row} = table(network, controller, target, reached, ...
                firstCrossing, 'VariableNames', {'Network','Controller', ...
                'Target','ReachedBy500ms','FirstCrossingTimeS'});
        end
    end
    t95 = vertcat(t95Rows{:});
    finitePass = all(isfinite(current.movement.ProspectiveErrorFraction)) && ...
        all(isfinite(current.movement.EndpointErrorM)) && ...
        all(isfinite(current.errorTimecourse.ProspectiveErrorFraction)) && ...
        all(isfinite(current.inputTimecourse.TargetMedianFeedbackNorm)) && ...
        all(isfinite(current.local.SpectralAbscissaPerS)) && ...
        all(isfinite(current.finiteTime.WorstQ95Gain));
end

function output = summarize_performance(cfg, input)
    controllers = unique(input.Controller, 'stable');
    durations = unique(input.PreparationDurationS);
    metrics = ["ProspectiveErrorFraction"; "EndpointErrorM"];
    rows = cell(numel(controllers) * numel(durations) * numel(metrics), 1);
    row = 0;
    for controller = controllers.'
        for duration = durations.'
            selected = input.Controller == controller & ...
                abs(input.PreparationDurationS - duration) < 1e-12;
            for metric = metrics.'
                row = row + 1;
                values = input.(metric)(selected);
                summary = bootstrap_network_median(values, ...
                    cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + ...
                    40000 + row);
                rows{row} = summary_row(controller, duration, metric, summary);
            end
        end
    end
    output = vertcat(rows{:});
end

function row = summary_row(controller, duration, metric, summary)
    row = table(controller, duration, metric, summary.median, ...
        summary.standardError, summary.lower95, summary.upper95, ...
        summary.minimum, summary.maximum, summary.nNetworks, ...
        summary.nSamples, summary.seed, 'VariableNames', {'Controller', ...
        'PreparationDurationS','Metric','Median','BootstrapSE', ...
        'BootstrapLower95','BootstrapUpper95','Minimum','Maximum', ...
        'Networks','BootstrapSamples','BootstrapSeed'});
end

function [networkTable, summaryTable] = summarize_t95(cfg, input)
    controllers = unique(input.Controller, 'stable');
    networkRows = cell(numel(controllers) * cfg.ensemble.count, 1);
    row = 0;
    for controller = controllers.'
        for network = 1:cfg.ensemble.count
            row = row + 1;
            selected = input.Controller == controller & input.Network == network;
            values = input.FirstCrossingTimeS(selected);
            networkRows{row} = table(network, controller, ...
                median(values, 'omitmissing'), sum(isnan(values)), ...
                'VariableNames', {'Network','Controller','TargetMedianT95S', ...
                'UnreachedTargets'});
        end
    end
    networkTable = vertcat(networkRows{:});
    summaryRows = cell(numel(controllers), 1);
    for index = 1:numel(controllers)
        controller = controllers(index);
        selected = networkTable.Controller == controller;
        values = networkTable.TargetMedianT95S(selected);
        summary = bootstrap_network_median(values, ...
            cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + 50000 + index);
        summaryRows{index} = table(controller, summary.median, ...
            summary.standardError, summary.lower95, summary.upper95, ...
            sum(input.Controller == controller & ~input.ReachedBy500ms), ...
            'VariableNames', {'Controller','MedianT95S','BootstrapSE', ...
            'BootstrapLower95','BootstrapUpper95','UnreachedTargetNetworkCases'});
    end
    summaryTable = vertcat(summaryRows{:});
end

function [networkTable, summaryTable] = summarize_effort(cfg, targetTable, controllerTable)
    metrics = ["FeedbackRmsNorm"; "FeedbackPeakNorm"; ...
        "RawUnweightedEffort"; "LambdaWeightedEffort"];
    networkRows = cell(cfg.ensemble.count, 1);
    for network = 1:cfg.ensemble.count
        selected = targetTable.Network == network;
        networkRows{network} = table(network, ...
            median(targetTable.FeedbackRmsNorm(selected)), ...
            median(targetTable.FeedbackPeakNorm(selected)), ...
            median(targetTable.RawUnweightedEffort(selected)), ...
            median(targetTable.LambdaWeightedEffort(selected)), ...
            'VariableNames', {'Network','FeedbackRmsNorm', ...
            'FeedbackPeakNorm','RawUnweightedEffort','LambdaWeightedEffort'});
    end
    networkTable = vertcat(networkRows{:});
    summaryRows = cell(numel(metrics) + 4, 1);
    row = 0;
    for metric = metrics.'
        row = row + 1;
        summary = bootstrap_network_median(networkTable.(metric), ...
            cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + 60000 + row);
        summaryRows{row} = scalar_summary_row(metric, summary);
    end
    controllerMetrics = ["GainFrobeniusNorm"; "GainSpectralNorm"; ...
        "FeedbackFrobeniusNorm"; "FeedbackSpectralNorm"];
    for metric = controllerMetrics.'
        row = row + 1;
        summary = bootstrap_network_median(controllerTable.(metric), ...
            cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + 60000 + row);
        summaryRows{row} = scalar_summary_row(metric, summary);
    end
    summaryTable = vertcat(summaryRows{:});
end

function row = scalar_summary_row(metric, summary)
    row = table(metric, summary.median, summary.standardError, ...
        summary.lower95, summary.upper95, summary.minimum, summary.maximum, ...
        summary.nNetworks, summary.nSamples, summary.seed, ...
        'VariableNames', {'Metric','Median','BootstrapSE','BootstrapLower95', ...
        'BootstrapUpper95','Minimum','Maximum','Networks','BootstrapSamples', ...
        'BootstrapSeed'});
end

function output = frozen_comparison(cfgKao, performance)
    frozenPath = fullfile(cfgKao.resultsRoot, 'tables', ...
        'ensemble_movement.csv');
    frozen = readtable(frozenPath, 'TextType', 'string');
    durations = [0.100; 0.200];
    controllers = ["Stage 2A"; "Stage 2B-Kao"; "Stage 2B-Cerebellum"];
    rows = cell(6, 1);
    row = 0;
    for duration = durations.'
        for controller = controllers.'
            row = row + 1;
            if controller == "Stage 2B-Cerebellum"
                selected = performance.Controller == controller & ...
                    abs(performance.PreparationDurationS - duration) < 1e-12 & ...
                    performance.Metric == "EndpointErrorM";
                source = performance(selected, :);
                sourceLabel = "Gate-4B recovered network-first summary";
            else
                selected = frozen.Controller == controller & ...
                    abs(frozen.PreparationDurationS - duration) < 1e-12 & ...
                    frozen.Metric == "EndpointErrorM";
                source = frozen(selected, :);
                sourceLabel = "Frozen Stage-2B-Kao ensemble_movement.csv";
            end
            assert(height(source) == 1);
            rows{row} = table(controller, duration, source.Median, ...
                source.BootstrapSE, sourceLabel, 'VariableNames', ...
                {'Controller','PreparationDurationS','EndpointErrorM', ...
                'BootstrapSE','Source'});
        end
    end
    output = vertcat(rows{:});
end

function output = acceptance_decision(cfg, audit)
    structural = all(audit.controllerValidation.AllStructuralChecksPass);
    targets = all(audit.targetValidation.AllTargetChecksPass);
    finite = all(audit.upstreamVerification.PreparationFinite) && ...
        all(audit.upstreamVerification.CachedPerformanceFinite);
    upstream = all(audit.upstreamVerification.Stage1CacheHashMatch) && ...
        all(audit.upstreamVerification.Stage2aCacheHashMatch) && ...
        all(audit.upstreamVerification.TimingMatch) && ...
        max(audit.upstreamVerification.MaximumTonicInputDifference) < ...
        cfg.validation.upstreamEqualityTolerance && ...
        max(audit.upstreamVerification.MaximumADifferenceFromKao) < ...
        cfg.validation.upstreamEqualityTolerance && ...
        max(audit.upstreamVerification.MaximumQDifferenceFromKao) < ...
        cfg.validation.upstreamEqualityTolerance;
    savedControllers = all(audit.controllerValidation. ...
        MaximumControllerReloadDifference == 0);
    passed = structural && targets && finite && upstream && savedControllers;
    status = "CANDIDATE";
    if passed
        status = "ACCEPTED / FROZEN";
    end
    output = table(status, passed, structural, targets, finite, upstream, ...
        savedControllers, 'VariableNames', {'Status','Passed', ...
        'StructuralChecksPass','TargetChecksPass','FiniteChecksPass', ...
        'UpstreamChecksPass','ControllerReloadChecksPass'});
end

function write_audit_outputs(cfg, audit)
    names = {'controllerValidation','targetValidation','effortTarget', ...
        'effortNetwork','effortSummary','performanceNetwork', ...
        'performanceEnsemble','t95Target','t95Network','t95Summary', ...
        'frozenComparison','upstreamVerification','acceptance'};
    for index = 1:numel(names)
        writetable(audit.(names{index}), fullfile(cfg.currentTablesRoot, ...
            [names{index}, '.csv']));
    end
    save(fullfile(cfg.currentAuditRoot, 'gate4b_audit.mat'), 'audit', '-v7.3');
    summary = struct('stage', 'Stage 2B-Cerebellum', 'gate', 'Gate 4B-C', ...
        'status', char(audit.acceptance.Status), ...
        'controllerPassCount', sum(audit.controllerValidation.AllStructuralChecksPass), ...
        'targetPassCount', sum(audit.targetValidation.AllTargetChecksPass), ...
        'networkCount', cfg.ensemble.count, 'targetCount', ...
        height(audit.targetValidation), 'bootstrapSamples', ...
        cfg.ensemble.bootstrapSamples, 'interruptionRecovery', ...
        ['Antigravity dense performance outputs were recovered; Codex ' ...
        'completed structural, effort, reconciliation, and documentation checks.']);
    file = fopen(fullfile(cfg.currentResultsRoot, ...
        'stage2b_cerebellum_gate4b_summary.json'), 'w');
    cleanup = onCleanup(@() fclose(file));
    fprintf(file, '%s\n', jsonencode(summary, PrettyPrint=true));
end
