function audit = audit_stage2b_kao_figure5_final(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    cfg = stage_2b_kao_config(projectRoot);
    savedPath = fullfile(cfg.resultsRoot, 'stage2b_kao_gate3_complete.mat');
    saved = load(savedPath, 'complete');
    movement = saved.complete.results.movement;
    durations = cfg.analysis.densePreparationDurationsS;
    assert(isequal(durations, (0:0.010:0.500).'));
    assert(height(movement) == 2 * 10 * 8 * numel(durations));

    controllers = ["Stage 2A", "Stage 2B-Kao"];
    metrics = ["StateErrorFraction", "ProspectiveErrorFraction", ...
        "EndpointErrorM", "HandTrajectoryNRMSE", "TorqueNRMSE"];
    comparison = build_saved_comparison(movement, controllers, metrics);

    stateTolerance = 5e-13;
    scalarTolerance = 5e-12;
    trajectoryTolerance = 5e-12;
    maximumPreparationStateDifference = 0;
    maximumSavedMetricDifference = 0;
    maximumBatchedTargetDifference = 0;
    maximumInitialTorqueDifference = 0;
    movementSamples = zeros(10, 1);
    handSamples = zeros(10, 1);
    movementOnsetIndex = zeros(10, 1);
    traceRows = cell(10 * 2 * 2 * 8, 23);
    traceRow = 0;

    for network = 1:10
        stage1Path = fullfile(cfg.ensemble.stage1Root, ...
            sprintf('network_%02d.mat', network));
        stage2aPath = fullfile(cfg.ensemble.stage2aRoot, ...
            sprintf('network_%02d_stage2a.mat', network));
        stage1 = load(stage1Path, 'model');
        stage2aSaved = load(stage2aPath, 'networkResult');
        model = stage1.model;
        tonicInput = model.xstar - model.W * max(model.xstar, 0) - model.h;
        assert(max(abs(tonicInput - stage2aSaved.networkResult.tonicInput), ...
            [], 'all') < 1e-12);
        kao = derive_stage2b_kao_controller(model, cfg);
        baseline = struct('name', 'Stage 2A', 'Q', kao.Q);
        preparation = {simulate_naive_preparation(model, tonicInput, 0.200), ...
            simulate_stage2b_kao_preparation(model, kao, 0.200)};
        idealCortex = simulate_published_cortex(model, model.xstar, false);
        [idealTheta, idealHand] = simulate_published_arm(model, ...
            idealCortex.torque);
        movementSamples(network) = size(idealCortex.torque, 1);
        handSamples(network) = size(idealHand, 1);
        movementOnsetIndex(network) = ...
            round(cfg.analysis.movementOnsetAfterControlRemovalS / ...
            model.samplingDt) + 1;
        assert(movementOnsetIndex(network) == ...
            round(0.100 / model.samplingDt) + 1);
        assert(size(idealCortex.torque, 1) == model.nSamples);
        assert(size(idealHand, 1) == model.nSamples + 1);

        for controllerIndex = 1:2
            currentController = {baseline, kao};
            currentController = currentController{controllerIndex};
            for durationIndex = 1:2
                durationS = [0.100, 0.200];
                durationS = durationS(durationIndex);
                sampleIndex = round(durationS / model.samplingDt) + 1;
                assert(abs(preparation{controllerIndex}.timesS(sampleIndex) - ...
                    durationS) < eps(durationS));
                direct = direct_preparation(model, tonicInput, kao, ...
                    controllerIndex, durationS);
                goStates = squeeze(preparation{controllerIndex}.states( ...
                    sampleIndex, :, :));
                maximumPreparationStateDifference = max( ...
                    maximumPreparationStateDifference, ...
                    max(abs(goStates - direct.finalState), [], 'all'));
                cortexBatch = simulate_published_cortex(model, goStates, false);
                [thetaBatch, handBatch] = simulate_published_arm( ...
                    model, cortexBatch.torque);
                assert(size(cortexBatch.torque, 1) == movementSamples(network));
                assert(size(handBatch, 1) == handSamples(network));
                for target = 1:model.nMovements
                    cortexSingle = simulate_published_cortex(model, ...
                        goStates(:, target), false);
                    [thetaSingle, handSingle] = simulate_published_arm(model, ...
                        cortexSingle.torque);
                    maximumBatchedTargetDifference = max( ...
                        maximumBatchedTargetDifference, max([max(abs( ...
                        cortexSingle.torque - cortexBatch.torque(:, :, target)), ...
                        [], 'all'), max(abs(thetaSingle - ...
                        thetaBatch(:, :, target)), [], 'all'), max(abs( ...
                        handSingle - handBatch(:, :, target)), [], 'all')]));
                    expectedInitialTorque = model.C * max(goStates(:, target), 0);
                    maximumInitialTorqueDifference = max( ...
                        maximumInitialTorqueDifference, max(abs( ...
                        squeeze(cortexSingle.torque(1, :, 1)).' - ...
                        expectedInitialTorque)));

                    delta = goStates(:, target) - model.xstar(:, target);
                    delta0 = model.spontaneous - model.xstar(:, target);
                    actualHand = handSingle(:, [1, 3], 1);
                    referenceHand = idealHand(:, [1, 3], target);
                    recomputed = [norm(delta) / max(norm(delta0), eps), ...
                        (delta.' * currentController.Q * delta) / max( ...
                        delta0.' * currentController.Q * delta0, eps), ...
                        norm(actualHand(end, :) - referenceHand(end, :)), ...
                        normalized_rmse_range(actualHand - actualHand(1, :), ...
                        referenceHand - referenceHand(1, :)), ...
                        normalized_rmse_range(cortexSingle.torque, ...
                        idealCortex.torque(:, :, target))];
                    savedRow = movement.Network == network & ...
                        movement.Controller == controllers(controllerIndex) & ...
                        movement.Target == target & abs( ...
                        movement.PreparationDurationS - durationS) < 1e-12;
                    assert(sum(savedRow) == 1);
                    savedValues = zeros(1, numel(metrics));
                    for metric = 1:numel(metrics)
                        savedValues(metric) = movement.(metrics(metric))(savedRow);
                    end
                    maximumSavedMetricDifference = max( ...
                        maximumSavedMetricDifference, max(abs( ...
                        recomputed - savedValues)));

                    torqueErrorMatrix = squeeze(cortexSingle.torque) - ...
                        idealCortex.torque(:, :, target);
                    torqueError = vecnorm(torqueErrorMatrix, 2, 2);
                    handError = vecnorm(actualHand - referenceHand, 2, 2);
                    torqueErrorImpulse = model.samplingDt * ...
                        sum(torqueErrorMatrix, 1);
                    jointAngleError = squeeze(thetaSingle(end, [1, 3], 1)) - ...
                        squeeze(idealTheta(end, [1, 3], target));
                    jointVelocityError = squeeze(thetaSingle(end, [2, 4], 1)) - ...
                        squeeze(idealTheta(end, [2, 4], target));
                    signedHandEndpointError = actualHand(end, :) - ...
                        referenceHand(end, :);
                    onset = movementOnsetIndex(network);
                    lateStart = min(onset + round(0.200 / model.samplingDt), ...
                        numel(torqueError));
                    traceRow = traceRow + 1;
                    traceRows(traceRow, :) = {network, ...
                        controllers(controllerIndex), target, durationS, ...
                        sampleIndex, preparation{controllerIndex}.timesS(sampleIndex), ...
                        movementSamples(network), handSamples(network), onset, ...
                        sqrt(mean(torqueError .^ 2)), ...
                        sqrt(mean(torqueError(1:(onset - 1)) .^ 2)), ...
                        sqrt(mean(torqueError(onset:end) .^ 2)), ...
                        sqrt(mean(torqueError(lateStart:end) .^ 2)), ...
                        max(handError), handError(onset), handError(end), ...
                        norm(torqueErrorImpulse), torqueErrorImpulse(1), ...
                        torqueErrorImpulse(2), norm(jointAngleError), ...
                        norm(jointVelocityError), signedHandEndpointError(1), ...
                        signedHandEndpointError(2)};
                end
            end
        end
    end

    trace = cell2table(traceRows, 'VariableNames', {'Network','Controller', ...
        'Target','PreparationDurationS','PreparationSampleIndex', ...
        'PreparationSampleTimeS','MovementTorqueSamples','HandSamples', ...
        'MovementOnsetSampleIndex','TorqueErrorRms','TorqueErrorPreOnsetRms', ...
        'TorqueErrorPostOnsetRms','TorqueErrorLateRms','MaximumHandErrorM', ...
        'HandErrorAtMovementOnsetM','EndpointErrorM', ...
        'TorqueErrorImpulseNorm','Torque1ErrorImpulse', ...
        'Torque2ErrorImpulse','FinalJointAngleErrorNorm', ...
        'FinalJointVelocityErrorNorm','FinalHandXErrorM','FinalHandYErrorM'});
    traceComparison = build_trace_comparison(trace);

    audit = struct();
    audit.Status = "PASS — no indexing, alignment, target, or extraction bug";
    audit.SavedDenseDurationsS = durations;
    audit.PreparationSampleIndex100ms = ...
        round(0.100 / model.samplingDt) + 1;
    audit.PreparationSampleIndex200ms = ...
        round(0.200 / model.samplingDt) + 1;
    audit.MovementOnsetSampleIndex = unique(movementOnsetIndex);
    audit.MovementTorqueSamples = unique(movementSamples);
    audit.HandSamples = unique(handSamples);
    audit.MaximumPreparationStateDifference = maximumPreparationStateDifference;
    audit.MaximumSavedMetricDifference = maximumSavedMetricDifference;
    audit.MaximumBatchedVersusSingleTargetDifference = ...
        maximumBatchedTargetDifference;
    audit.MaximumInitialTorqueDifference = maximumInitialTorqueDifference;
    audit.PreparationStateTolerance = stateTolerance;
    audit.SavedMetricTolerance = scalarTolerance;
    audit.TrajectoryTolerance = trajectoryTolerance;
    audit.IdenticalMovementHorizon = isscalar(unique(movementSamples)) && ...
        isscalar(unique(handSamples));
    audit.ExactPreparationIndexing = maximumPreparationStateDifference <= ...
        stateTolerance;
    audit.SavedMetricsReproduced = maximumSavedMetricDifference <= scalarTolerance;
    audit.TargetBatchingVerified = maximumBatchedTargetDifference <= ...
        trajectoryTolerance;
    audit.GoStateExtractionVerified = maximumInitialTorqueDifference <= ...
        trajectoryTolerance;
    audit.BugFound = ~(audit.IdenticalMovementHorizon && ...
        audit.ExactPreparationIndexing && audit.SavedMetricsReproduced && ...
        audit.TargetBatchingVerified && audit.GoStateExtractionVerified);
    audit.Comparison = comparison;
    audit.TraceComparison = traceComparison;
    assert(~audit.BugFound, 'Figure-5 diagnostic found an implementation bug.');

    auditRoot = fullfile(cfg.resultsRoot, 'audit');
    if ~exist(auditRoot, 'dir')
        mkdir(auditRoot);
    end
    writetable(comparison, fullfile(auditRoot, ...
        'figure5_final_100_vs_200_network_audit.csv'));
    writetable(traceComparison, fullfile(auditRoot, ...
        'figure5_final_trace_diagnostic.csv'));
    save(fullfile(auditRoot, 'figure5_final_diagnostic.mat'), ...
        'audit', 'comparison', 'trace', 'traceComparison', '-v7.3');
    jsonAudit = rmfield(audit, {'Comparison','TraceComparison', ...
        'SavedDenseDurationsS'});
    fileId = fopen(fullfile(auditRoot, 'figure5_final_diagnostic.json'), 'w');
    cleanup = onCleanup(@() fclose(fileId));
    fprintf(fileId, '%s\n', jsonencode(jsonAudit, 'PrettyPrint', true));
    clear cleanup;
end

function output = direct_preparation(model, tonicInput, kao, ...
        controllerIndex, durationS)
    if controllerIndex == 1
        output = simulate_naive_preparation(model, tonicInput, durationS);
    else
        output = simulate_stage2b_kao_preparation(model, kao, durationS);
    end
end

function output = build_saved_comparison(movement, controllers, metrics)
    rows = cell(10 * numel(controllers), 3 + 5 * numel(metrics));
    row = 0;
    for controllerIndex = 1:numel(controllers)
        for network = 1:10
            row = row + 1;
            rows(row, 1:3) = {network, controllers(controllerIndex), 8};
            column = 3;
            for metric = 1:numel(metrics)
                values = zeros(1, 2);
                for durationIndex = 1:2
                    durationS = [0.100, 0.200];
                    selected = movement.Network == network & ...
                        movement.Controller == controllers(controllerIndex) & ...
                        abs(movement.PreparationDurationS - ...
                        durationS(durationIndex)) < 1e-12;
                    assert(sum(selected) == 8);
                    values(durationIndex) = median(movement.(metrics(metric))(selected));
                end
                rows(row, column + (1:5)) = {values(1), values(2), ...
                    values(2) - values(1), values(2) < values(1), ...
                    values(2) > values(1)};
                column = column + 5;
            end
        end
    end
    names = ["Network","Controller","Targets"];
    for metric = metrics
        names = [names, metric + "100ms", metric + "200ms", ...
            metric + "200Minus100", metric + "LowerAt200", ...
            metric + "HigherAt200"]; %#ok<AGROW>
    end
    output = cell2table(rows, 'VariableNames', cellstr(names));
end

function output = build_trace_comparison(trace)
    metrics = ["TorqueErrorRms", "TorqueErrorPreOnsetRms", ...
        "TorqueErrorPostOnsetRms", "TorqueErrorLateRms", ...
        "MaximumHandErrorM", "HandErrorAtMovementOnsetM", "EndpointErrorM", ...
        "TorqueErrorImpulseNorm", "FinalJointAngleErrorNorm", ...
        "FinalJointVelocityErrorNorm"];
    controllers = ["Stage 2A", "Stage 2B-Kao"];
    rows = cell(10 * 2, 2 + 3 * numel(metrics));
    row = 0;
    for controllerIndex = 1:2
        for network = 1:10
            row = row + 1;
            rows(row, 1:2) = {network, controllers(controllerIndex)};
            column = 2;
            for metric = metrics
                values = zeros(1, 2);
                for durationIndex = 1:2
                    durationS = [0.100, 0.200];
                    selected = trace.Network == network & ...
                        trace.Controller == controllers(controllerIndex) & ...
                        abs(trace.PreparationDurationS - ...
                        durationS(durationIndex)) < 1e-12;
                    values(durationIndex) = median(trace.(metric)(selected));
                end
                rows(row, column + (1:3)) = {values(1), values(2), ...
                    values(2) - values(1)};
                column = column + 3;
            end
        end
    end
    names = ["Network","Controller"];
    for metric = metrics
        names = [names, metric + "100ms", metric + "200ms", ...
            metric + "200Minus100"]; %#ok<AGROW>
    end
    output = cell2table(rows, 'VariableNames', cellstr(names));
end

function value = normalized_rmse_range(actual, reference)
    numerator = sqrt(mean((actual - reference) .^ 2, 'all'));
    denominator = max(max(reference, [], 'all') - min(reference, [], 'all'), eps);
    value = numerator / denominator;
end
