function report = finalize_stage2b_kao_lambda_sensitivity(cfg, complete, component)
    outputRoot = fullfile(cfg.resultsRoot, 'diagnostics', ...
        'lambda_sensitivity');
    tableRoot = fullfile(outputRoot, 'tables');
    auditRoot = fullfile(outputRoot, 'audit');
    plotRoot = fullfile(cfg.plotsRoot, 'diagnostics', 'lambda_sensitivity');
    if ~isfolder(tableRoot), mkdir(tableRoot); end
    if ~isfolder(auditRoot), mkdir(auditRoot); end
    canonicalArtifactPath = fullfile(cfg.resultsRoot, ...
        'final_artifact_manifest_sha256.csv');
    canonicalCodePath = fullfile(cfg.resultsRoot, ...
        'final_code_manifest_sha256.csv');
    beforeArtifact = readtable(canonicalArtifactPath, TextType='string');
    beforeCode = readtable(canonicalCodePath, TextType='string');
    writetable(beforeArtifact, fullfile(auditRoot, ...
        'canonical_stage2b_kao_artifact_manifest_before.csv'));
    writetable(beforeCode, fullfile(auditRoot, ...
        'canonical_stage2b_kao_code_manifest_before.csv'));
    save(fullfile(auditRoot, 'component_validation.mat'), 'component', '-v7.3');
    componentReproduction = component.results.reproduction( ...
        component.results.reproduction.Lambda == 0.1, :);
    componentReport = struct('passed', true, ...
        'network', 1, 'lambdas', component.lambdas.', ...
        'maximumCanonicalGainDifference', ...
        max(componentReproduction.MaximumCanonicalGainDifference), ...
        'maximumCanonicalProspectiveDifference', ...
        max(componentReproduction.MaximumCanonicalProspectiveDifference), ...
        'maximumCanonicalEndpointDifference', ...
        max(componentReproduction.MaximumCanonicalEndpointDifference), ...
        'maximumCareResidualRelative', ...
        max(component.results.controller.CareResidualRelative), ...
        'maximumTargetJacobianRealEigenvaluePerS', ...
        max(component.results.controller.MaximumTargetJacobianRealEigenvaluePerS));
    write_json(fullfile(auditRoot, 'component_validation.json'), ...
        componentReport);
    save(fullfile(outputRoot, ...
        'stage2b_kao_lambda_sensitivity_complete.mat'), 'complete', '-v7.3');
    names = fieldnames(complete.results);
    for index = 1:numel(names)
        value = complete.results.(names{index});
        if istable(value)
            writetable(value, fullfile(tableRoot, [names{index}, '.csv']));
        end
    end
    figureFiles = create_stage2b_kao_lambda_sensitivity_figure(cfg, complete);
    reopened = openfig(figureFiles.fig, 'invisible');
    assert(isgraphics(reopened));
    close(reopened);
    imageData = imread(figureFiles.png);
    assert(size(imageData, 1) >= 800 && size(imageData, 2) >= 1200);
    controller = complete.results.controller;
    reproduction = complete.results.reproduction( ...
        complete.results.reproduction.Lambda == 0.1, :);
    assert(height(reproduction) == cfg.ensemble.count);
    assert(max(reproduction.MaximumCanonicalGainDifference) <= 1e-12);
    assert(max(reproduction.MaximumCanonicalRiccatiDifference) <= 1e-12);
    assert(max(reproduction.MaximumCanonicalQDifference) <= 1e-12);
    assert(max(reproduction.MaximumCanonicalInputDifference) <= 1e-12);
    assert(max(reproduction.MaximumCanonicalProspectiveDifference) <= 1e-12);
    assert(max(reproduction.MaximumCanonicalEndpointDifference) <= 1e-12);
    assert(max(controller.CareResidualRelative) < ...
        cfg.validation.careResidualTolerance);
    assert(all(controller.MaximumCareClosedLoopRealEigenvalue < 0));
    assert(all(controller.MaximumTargetJacobianRealEigenvaluePerS < 0));
    assert(max(controller.MaximumTargetFixedPointResidual) < ...
        cfg.validation.fixedPointTolerance);
    assert(max(controller.RecomputeKDifference) == 0);
    assert(max(controller.ReloadKDifference) == 0);
    frozenSources = {
        'Stage 1', fullfile(cfg.resultsRoot, 'audit', ...
            'stage1_after_figure5_freeze.csv');
        'Stage 2A', fullfile(cfg.resultsRoot, 'audit', ...
            'stage2a_after_figure5_freeze.csv');
        'Stage 2B-Cerebellum', fullfile(cfg.resultsRoot, 'audit', ...
            'stage2b_cerebellum_after_figure5_freeze.csv');
        'Canonical Stage 2B-Kao artifacts', fullfile(auditRoot, ...
            'canonical_stage2b_kao_artifact_manifest_before.csv');
        'Canonical Stage 2B-Kao code', fullfile(auditRoot, ...
            'canonical_stage2b_kao_code_manifest_before.csv')};
    frozenRows = cell(size(frozenSources, 1), 1);
    for index = 1:size(frozenSources, 1)
        [matched, count] = verify_manifest(cfg.projectRoot, ...
            frozenSources{index, 2});
        frozenRows{index} = table(string(frozenSources{index, 1}), count, ...
            matched, 'VariableNames', {'Scope','Files','AllHashesMatch'});
    end
    frozenVerification = vertcat(frozenRows{:});
    assert(all(frozenVerification.AllHashesMatch));
    writetable(frozenVerification, fullfile(auditRoot, ...
        'frozen_stage_verification.csv'));
    summary = build_summary(complete, reproduction, frozenVerification, ...
        figureFiles);
    write_json(fullfile(outputRoot, ...
        'stage2b_kao_lambda_sensitivity_summary.json'), summary);
    validation = struct('passed', true, ...
        'networkCount', complete.networkCount, ...
        'lambdaCount', numel(complete.lambdas), ...
        'targetLambdaRows', height(complete.results.target), ...
        'timecourseRows', height(complete.results.timecourse), ...
        'movementRows', height(complete.results.movement), ...
        'maximumCareResidualRelative', max(controller.CareResidualRelative), ...
        'maximumCareClosedLoopRealEigenvalue', ...
        max(controller.MaximumCareClosedLoopRealEigenvalue), ...
        'maximumTargetJacobianRealEigenvaluePerS', ...
        max(controller.MaximumTargetJacobianRealEigenvaluePerS), ...
        'maximumFixedPointResidual', ...
        max(controller.MaximumTargetFixedPointResidual), ...
        'maximumLambda01GainDifference', ...
        max(reproduction.MaximumCanonicalGainDifference), ...
        'maximumLambda01ProspectiveDifference', ...
        max(reproduction.MaximumCanonicalProspectiveDifference), ...
        'maximumLambda01EndpointDifference', ...
        max(reproduction.MaximumCanonicalEndpointDifference), ...
        'notReachedTargetCount', ...
        sum(complete.results.target.T95Reached == false), ...
        'figureReopened', true, 'pngDimensions', ...
        [size(imageData, 2), size(imageData, 1)], ...
        'runtimeSeconds', complete.runtimeSeconds);
    write_json(fullfile(auditRoot, 'complete_validation.json'), validation);
    save(fullfile(auditRoot, 'complete_validation.mat'), 'validation');
    diagnosticFiles = collect_files({outputRoot, plotRoot}, ...
        {'diagnostic_artifact_manifest_sha256.csv'});
    diagnosticManifest = make_manifest(cfg.projectRoot, diagnosticFiles);
    writetable(diagnosticManifest, fullfile(auditRoot, ...
        'diagnostic_artifact_manifest_sha256.csv'));
    diagnosticFiles{end + 1, 1} = fullfile(auditRoot, ...
        'diagnostic_artifact_manifest_sha256.csv');
    newArtifact = make_manifest(cfg.projectRoot, diagnosticFiles);
    finalArtifact = merge_manifests(beforeArtifact, newArtifact);
    writetable(finalArtifact, canonicalArtifactPath);
    codeFiles = {
        fullfile(cfg.projectRoot, 'analysis', 'stage_2b_shared', ...
            'analyze_stage2b_kao_lambda_sensitivity.m');
        fullfile(cfg.projectRoot, 'analysis', 'stage_2b_shared', ...
            'finalize_stage2b_kao_lambda_sensitivity.m');
        fullfile(cfg.projectRoot, 'figures', 'stage_2b_shared', ...
            'create_stage2b_kao_lambda_sensitivity_figure.m');
        fullfile(cfg.projectRoot, 'workflows', 'diagnostics', ...
            'stage_2b_kao', 'run_stage_2b_kao_lambda_sensitivity.m')};
    finalCode = merge_manifests(beforeCode, ...
        make_manifest(cfg.projectRoot, codeFiles));
    writetable(finalCode, canonicalCodePath);
    [artifactMatched, artifactCount] = verify_manifest(cfg.projectRoot, ...
        canonicalArtifactPath);
    [codeMatched, codeCount] = verify_manifest(cfg.projectRoot, ...
        canonicalCodePath);
    assert(artifactMatched && codeMatched);
    report = struct('summary', summary, 'validation', validation, ...
        'figureFiles', figureFiles, 'artifactManifestFiles', artifactCount, ...
        'codeManifestFiles', codeCount, ...
        'frozenVerification', frozenVerification);
end

function output = build_summary(complete, reproduction, frozen, figureFiles)
    ensemble = complete.results.ensemble;
    lambdas = complete.lambdas;
    rows = repmat(struct(), numel(lambdas), 1);
    metrics = {'GainSpectralNorm','GainFrobeniusNorm', ...
        'TargetMedianT95Ms','TargetMedianRawEffort', ...
        'TargetMedianFeedbackRmsNorm','TargetMedianPeakFeedbackNorm', ...
        'TargetMedianEndpoint100Mm','TargetMedianEndpoint200Mm'};
    fields = {'gainSpectralNorm','gainFrobeniusNorm','t95Ms','rawEffort', ...
        'feedbackRmsNorm','peakFeedbackNorm','endpoint100Mm','endpoint200Mm'};
    for lambdaIndex = 1:numel(lambdas)
        rows(lambdaIndex).lambda = lambdas(lambdaIndex);
        for metricIndex = 1:numel(metrics)
            current = ensemble(ensemble.Lambda == lambdas(lambdaIndex) & ...
                ensemble.Metric == string(metrics{metricIndex}), :);
            rows(lambdaIndex).(fields{metricIndex}) = struct( ...
                'median', current.Median, 'bootstrapSE', current.BootstrapSE, ...
                'minimum', current.Minimum, 'maximum', current.Maximum);
        end
        selected = complete.results.network.Lambda == lambdas(lambdaIndex);
        rows(lambdaIndex).notReachedTargets = sum( ...
            complete.results.network.NotReachedTargetCount(selected));
    end
    output = struct('status', 'PASS', ...
        'interpretation', ['Diagnostic sensitivity sweep only; canonical ' ...
        'lambda=0.1 remains unchanged and primary.'], ...
        'networkCount', complete.networkCount, ...
        'targetCountPerNetwork', 8, ...
        'bootstrapResamples', complete.cfg.ensemble.bootstrapSamples, ...
        'lambdaSummaries', rows, ...
        'lambda01Reproduction', struct( ...
        'maximumGainDifference', ...
        max(reproduction.MaximumCanonicalGainDifference), ...
        'maximumProspectiveDifference', ...
        max(reproduction.MaximumCanonicalProspectiveDifference), ...
        'maximumEndpointDifference', ...
        max(reproduction.MaximumCanonicalEndpointDifference)), ...
        'allFrozenHashesMatch', all(frozen.AllHashesMatch), ...
        'figurePng', figureFiles.png, 'figureFig', figureFiles.fig);
end

function [matched, count] = verify_manifest(projectRoot, manifestPath)
    manifest = readtable(manifestPath, TextType='string');
    if ismember('SHA256', manifest.Properties.VariableNames)
        expectedHashes = manifest.SHA256;
    else
        assert(ismember('Sha256', manifest.Properties.VariableNames));
        expectedHashes = manifest.Sha256;
    end
    matched = true;
    count = height(manifest);
    for row = 1:height(manifest)
        path = fullfile(projectRoot, strrep(char(manifest.Path(row)), '/', ...
            filesep));
        if ~isfile(path) || ...
                string(sha256_file(path)) ~= string(expectedHashes(row))
            matched = false;
            return
        end
    end
end

function files = collect_files(roots, exclusions)
    files = cell(0, 1);
    for rootIndex = 1:numel(roots)
        if ~isfolder(roots{rootIndex}), continue; end
        listing = dir(fullfile(roots{rootIndex}, '**', '*'));
        listing = listing(~[listing.isdir]);
        for index = 1:numel(listing)
            if ismember(listing(index).name, exclusions), continue; end
            files{end + 1, 1} = fullfile(listing(index).folder, ...
                listing(index).name); %#ok<AGROW>
        end
    end
end

function output = make_manifest(projectRoot, files)
    paths = strings(numel(files), 1);
    bytes = zeros(numel(files), 1);
    hashes = strings(numel(files), 1);
    prefixLength = strlength(string(projectRoot)) + 2;
    for index = 1:numel(files)
        info = dir(files{index});
        relative = extractAfter(string(files{index}), prefixLength - 1);
        paths(index) = replace(relative, '\', '/');
        bytes(index) = info.bytes;
        hashes(index) = string(sha256_file(files{index}));
    end
    output = sortrows(table(paths, bytes, hashes, 'VariableNames', ...
        {'Path','Bytes','SHA256'}), 'Path');
end

function output = merge_manifests(original, added)
    output = [original; added];
    [~, indices] = unique(output.Path, 'last');
    output = sortrows(output(indices, :), 'Path');
end

function write_json(path, value)
    text = jsonencode(value, PrettyPrint=true);
    file = fopen(path, 'w');
    assert(file >= 0);
    cleanup = onCleanup(@() fclose(file));
    fprintf(file, '%s\n', text);
end
