function complete = run_stage2b_kao_gate3_ensemble(cfg, options)
    arguments
        cfg
        options.NullDraws (1, 1) double = cfg.analysis.randomSubspaceDraws
        options.NetworkCount (1, 1) double = cfg.ensemble.count
        options.RunDenseMovement (1, 1) logical = true
        options.RunCloud (1, 1) logical = true
    end
    accepted = readtable(fullfile(cfg.projectRoot, 'results', 'stage_1', ...
        'current', 'audit', 'accepted_ensemble_audit.csv'));
    assert(height(accepted) >= options.NetworkCount);
    controller = table(); targetValidation = table(); errorTimecourse = table();
    thresholds = table(); movement = table(); inputDimension = table();
    inputTimecourse = table(); effort = table(); corticalDimensionality = table();
    alignment = table(); sourceAlignment = table(); alignmentNull = table();
    sourceAlignmentNull = table(); local = table(); finiteTime = table();
    cloud = table(); amplification = table(); amplificationTargets = table();
    representative = struct();
    networkManifest = table();
    perNetworkRoot = fullfile(cfg.workResultsRoot, 'per_network');
    if ~exist(perNetworkRoot, 'dir')
        mkdir(perNetworkRoot);
    end
    startTime = tic;
    for network = 1:options.NetworkCount
        stage1Path = fullfile(cfg.ensemble.stage1Root, ...
            sprintf('network_%02d.mat', network));
        stage2aPath = fullfile(cfg.ensemble.stage2aRoot, ...
            sprintf('network_%02d_stage2a.mat', network));
        saved = load(stage1Path, 'model', 'networkRow');
        stage2aSaved = load(stage2aPath, 'networkResult');
        assert(saved.networkRow.Pass && ...
            saved.networkRow.AcceptedMember == network);
        stage1Hash = string(sha256_file(stage1Path));
        stage2aHash = string(sha256_file(stage2aPath));
        resultPath = fullfile(perNetworkRoot, sprintf( ...
            'network_%02d_gate3_result.mat', network));
        useCached = false;
        if isfile(resultPath)
            cached = load(resultPath, 'current', 'currentRepresentative', ...
                'cacheMetadata');
            useCached = cached.cacheMetadata.NullDraws == options.NullDraws && ...
                cached.cacheMetadata.RunDenseMovement == ...
                options.RunDenseMovement && cached.cacheMetadata.RunCloud == ...
                options.RunCloud && cached.cacheMetadata.Stage1Sha256 == ...
                stage1Hash && cached.cacheMetadata.Stage2aSha256 == stage2aHash;
        end
        if useCached
            current = cached.current;
            currentRepresentative = cached.currentRepresentative;
        else
            [current, currentRepresentative] = ...
                analyze_stage2b_kao_gate3_network(cfg, saved.model, network, ...
                stage2aSaved, NullDraws=options.NullDraws, ...
                RunDenseMovement=options.RunDenseMovement, ...
                RunCloud=options.RunCloud);
            cacheMetadata = struct('NullDraws', options.NullDraws, ...
                'RunDenseMovement', options.RunDenseMovement, ...
                'RunCloud', options.RunCloud, 'Stage1Sha256', stage1Hash, ...
                'Stage2aSha256', stage2aHash);
            save(resultPath, 'current', 'currentRepresentative', ...
                'cacheMetadata', '-v7.3');
        end
        targetValidation = [targetValidation; current.targetValidation]; %#ok<AGROW>
        errorTimecourse = [errorTimecourse; current.errorTimecourse]; %#ok<AGROW>
        thresholds = [thresholds; current.thresholds]; %#ok<AGROW>
        movement = [movement; current.movement]; %#ok<AGROW>
        inputDimension = [inputDimension; current.inputDimension]; %#ok<AGROW>
        inputTimecourse = [inputTimecourse; current.inputTimecourse]; %#ok<AGROW>
        effort = [effort; current.effort]; %#ok<AGROW>
        corticalDimensionality = [corticalDimensionality; ...
            current.corticalDimensionality]; %#ok<AGROW>
        alignment = [alignment; current.alignment]; %#ok<AGROW>
        sourceAlignment = [sourceAlignment; current.sourceAlignment]; %#ok<AGROW>
        alignmentNull = [alignmentNull; current.alignmentNull]; %#ok<AGROW>
        sourceAlignmentNull = [sourceAlignmentNull; ...
            current.sourceAlignmentNull]; %#ok<AGROW>
        local = [local; current.local]; %#ok<AGROW>
        finiteTime = [finiteTime; current.finiteTime]; %#ok<AGROW>
        cloud = [cloud; current.cloud]; %#ok<AGROW>
        amplification = [amplification; current.amplification]; %#ok<AGROW>
        amplificationTargets = [amplificationTargets; ...
            current.amplificationTargets]; %#ok<AGROW>
        controllerSaved = derive_stage2b_kao_controller(saved.model, cfg);
        controllerPath = fullfile(cfg.workEnsembleRoot, ...
            sprintf('network_%02d_stage2b_kao_controller.mat', network));
        recurrentSeed = double(saved.networkRow.RecurrentSeed);
        calibrationSeed = double(saved.networkRow.CalibrationSeed);
        save(controllerPath, 'network', 'recurrentSeed', 'calibrationSeed', ...
            'controllerSaved', '-v7.3');
        reloaded = load(controllerPath, 'controllerSaved');
        maximumGainReloadDifference = max(abs(controllerSaved.K - ...
            reloaded.controllerSaved.K), [], 'all');
        current.controller.MaximumGainReloadDifference = ...
            maximumGainReloadDifference;
        controller = [controller; current.controller]; %#ok<AGROW>
        networkManifest = [networkManifest; table(network, recurrentSeed, ...
            calibrationSeed, stage1Hash, stage2aHash, ...
            string(sha256_file(controllerPath)), ...
            'VariableNames', {'Network','RecurrentSeed','CalibrationSeed', ...
            'Stage1Sha256','Stage2aSha256','ControllerSha256'})]; %#ok<AGROW>
        if network == cfg.ensemble.representativeIndex
            representative = currentRepresentative;
        end
        fprintf(['Gate 3 network %02d/%02d: CARE %.3e; max fixed %.3e; ' ...
            'alignment %.4f/null %.4f; p %.4g.\n'], network, ...
            options.NetworkCount, current.controller.CareResidualRelative, ...
            max(current.targetValidation.FixedPointResidualNorm), ...
            current.alignment.ObservedAlignment, current.alignment.NullMedian, ...
            current.alignment.FiniteCorrectedLowerTailP);
    end
    alignment.BhAdjustedLowerTailP = bh_adjust( ...
        alignment.FiniteCorrectedLowerTailP);
    alignment.BhSignificant05 = alignment.BhAdjustedLowerTailP <= 0.05;
    prStatistics = cortical_pr_statistics(cfg, corticalDimensionality);
    results = struct('controller', controller, ...
        'targetValidation', targetValidation, 'errorTimecourse', errorTimecourse, ...
        'thresholds', thresholds, 'movement', movement, ...
        'inputDimension', inputDimension, 'inputTimecourse', inputTimecourse, ...
        'effort', effort, 'corticalDimensionality', corticalDimensionality, ...
        'prStatistics', prStatistics, 'alignment', alignment, ...
        'sourceAlignment', sourceAlignment, 'alignmentNull', alignmentNull, ...
        'sourceAlignmentNull', sourceAlignmentNull, 'local', local, ...
        'finiteTime', finiteTime, 'cloud', cloud, ...
        'amplification', amplification, ...
        'amplificationTargets', amplificationTargets, ...
        'networkManifest', networkManifest);
    if options.NetworkCount == cfg.ensemble.count && options.RunDenseMovement
        ensemble = summarize_stage2b_kao_gate3(cfg, results);
    else
        ensemble = struct();
    end
    complete = struct('cfg', cfg, 'results', results, ...
        'ensemble', ensemble, 'representative', representative, ...
        'runtimeSeconds', toc(startTime), 'nullDraws', options.NullDraws, ...
        'networkCount', options.NetworkCount);
end

function output = cortical_pr_statistics(cfg, values)
    epochs = ["Preparation"; "Movement"];
    rows = cell(2, 11);
    rawP = zeros(2, 1);
    for index = 1:2
        epoch = epochs(index);
        stage2a = values.ParticipationRatio(values.Epoch == epoch & ...
            values.Controller == "Stage 2A");
        kao = values.ParticipationRatio(values.Epoch == epoch & ...
            values.Controller == "Stage 2B-Kao");
        assert(numel(stage2a) == cfg.ensemble.count && numel(kao) == ...
            cfg.ensemble.count);
        test = paired_wilcoxon_exact(stage2a, kao);
        summaryA = bootstrap_network_median(stage2a, ...
            cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + 10000 + index);
        summaryK = bootstrap_network_median(kao, ...
            cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + 10100 + index);
        rawP(index) = test.p;
        rows(index, :) = {epoch, summaryA.median, summaryA.standardError, ...
            summaryK.median, summaryK.standardError, test.medianDifference, ...
            test.wPlus, test.nNonzero, test.p, NaN, false};
    end
    adjusted = bh_adjust(rawP);
    for index = 1:2
        rows{index, 10} = adjusted(index);
        rows{index, 11} = adjusted(index) <= 0.05;
    end
    output = cell2table(rows, 'VariableNames', {'Epoch', ...
        'Stage2aMedian','Stage2aBootstrapSE','Stage2bKaoMedian', ...
        'Stage2bKaoBootstrapSE','MedianPairedDifference','WilcoxonWPlus', ...
        'NonzeroPairs','RawP','BhAdjustedP','BhSignificant05'});
end
