function ensemble = summarize_stage2b_kao_gate3(cfg, results)
    ensemble.errorTimecourse = summarize_target_medians(cfg, ...
        results.errorTimecourse, {'Controller','PreparationTimeS'}, ...
        {'StateErrorFraction','ProspectiveErrorFraction'}, 1000);
    ensemble.movement = summarize_target_medians(cfg, results.movement, ...
        {'Controller','PreparationDurationS'}, {'StateErrorFraction', ...
        'ProspectiveErrorFraction','EndpointErrorM','HandTrajectoryNRMSE', ...
        'TorqueNRMSE'}, 2000);
    ensemble.inputTimecourse = summarize_network_values(cfg, ...
        results.inputTimecourse, {'PreparationTimeS'}, ...
        {'TargetMedianFeedbackNorm'}, 3000);
    ensemble.local = summarize_target_medians(cfg, results.local, ...
        {'Controller'}, {'SpectralAbscissaPerS', ...
        'WorstInstantaneousProspectiveRatePerS', ...
        'WorstInstantaneousEuclideanRatePerS'}, 4000);
    ensemble.finiteTime = summarize_target_medians(cfg, results.finiteTime, ...
        {'Controller','TimeS'}, {'WorstQ95Gain','WorstEuclideanGain'}, 5000);
    ensemble.amplification = summarize_network_values(cfg, ...
        results.amplification, {'TimeFromModelMovementOnsetS'}, ...
        {'NormalizedAmplification'}, 6000);
    ensemble.inputDimension = summarize_network_values(cfg, ...
        results.inputDimension, {}, {'K95','ParticipationRatio'}, 7000);
    effortNetwork = groupsummary(results.effort, 'Network', 'median', ...
        'LambdaWeightedFeedbackEffort');
    effortNetwork.Properties.VariableNames{end} = ...
        'LambdaWeightedFeedbackEffort';
    ensemble.effort = summarize_network_values(cfg, effortNetwork, {}, ...
        {'LambdaWeightedFeedbackEffort'}, 8000);
    ensemble.alignment = scalar_alignment_summary(cfg, results.alignment);
    ensemble.movement100vs200 = movement_comparison(results.movement);
end

function output = summarize_target_medians(cfg, input, groupVariables, ...
        metricVariables, seedOffset)
    groupVariables = string(groupVariables);
    metricVariables = string(metricVariables);
    withinVariables = ["Network", groupVariables];
    columns = cell(1, numel(withinVariables));
    for index = 1:numel(withinVariables)
        columns{index} = input.(withinVariables(index));
    end
    [groups, values{1:numel(withinVariables)}] = ...
        findgroups(columns{:});
    within = table();
    for index = 1:numel(withinVariables)
        within.(withinVariables(index)) = values{index};
    end
    for metric = 1:numel(metricVariables)
        within.(metricVariables(metric)) = splitapply(@median, ...
            input.(metricVariables(metric)), groups);
    end
    output = summarize_network_values(cfg, within, cellstr(groupVariables), ...
        cellstr(metricVariables), seedOffset);
end

function output = summarize_network_values(cfg, input, groupVariables, ...
        metricVariables, seedOffset)
    groupVariables = string(groupVariables);
    metricVariables = string(metricVariables);
    if isempty(groupVariables)
        groupIndex = ones(height(input), 1);
        groupValues = {};
        nGroups = 1;
    else
        columns = cell(1, numel(groupVariables));
        for index = 1:numel(groupVariables)
            columns{index} = input.(groupVariables(index));
        end
        [groupIndex, groupValues{1:numel(groupVariables)}] = ...
            findgroups(columns{:});
        nGroups = max(groupIndex);
    end
    rows = cell(nGroups * numel(metricVariables), ...
        numel(groupVariables) + 9);
    row = 0;
    for group = 1:nGroups
        groupRows = groupIndex == group;
        for metric = 1:numel(metricVariables)
            row = row + 1;
            values = input.(metricVariables(metric))(groupRows);
            assert(numel(values) == cfg.ensemble.count);
            summary = bootstrap_network_median(values, ...
                cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + ...
                seedOffset + row);
            for variable = 1:numel(groupVariables)
                current = groupValues{variable};
                rows{row, variable} = current(group);
            end
            start = numel(groupVariables);
            rows(row, start + (1:9)) = {metricVariables(metric), ...
                summary.median, summary.standardError, summary.lower95, ...
                summary.upper95, summary.minimum, summary.maximum, ...
                cfg.ensemble.count, cfg.ensemble.bootstrapSamples};
        end
    end
    names = [groupVariables, "Metric", "Median", "BootstrapSE", ...
        "BootstrapLower95", "BootstrapUpper95", "Minimum", "Maximum", ...
        "Networks", "BootstrapSamples"];
    output = cell2table(rows, 'VariableNames', cellstr(names));
end

function output = scalar_alignment_summary(cfg, alignment)
    metrics = {'ObservedAlignment','NullMedian'};
    rows = cell(numel(metrics), 9);
    for index = 1:numel(metrics)
        values = alignment.(metrics{index});
        summary = bootstrap_network_median(values, ...
            cfg.ensemble.bootstrapSamples, cfg.ensemble.bootstrapSeed + 9000 + index);
        rows(index, :) = {string(metrics{index}), summary.median, ...
            summary.standardError, summary.lower95, summary.upper95, ...
            summary.minimum, summary.maximum, cfg.ensemble.count, ...
            cfg.ensemble.bootstrapSamples};
    end
    output = cell2table(rows, 'VariableNames', {'Metric','Median', ...
        'BootstrapSE','BootstrapLower95','BootstrapUpper95','Minimum', ...
        'Maximum','Networks','BootstrapSamples'});
end

function output = movement_comparison(movement)
    rows = movement.Controller == "Stage 2B-Kao" & ...
        ismember(movement.PreparationDurationS, [0.1, 0.2]);
    data = movement(rows, :);
    [groups, network, duration] = findgroups(data.Network, ...
        data.PreparationDurationS);
    endpoint = splitapply(@median, data.EndpointErrorM, groups);
    hand = splitapply(@median, data.HandTrajectoryNRMSE, groups);
    torque = splitapply(@median, data.TorqueNRMSE, groups);
    wideEndpoint = unstack(table(network, duration, endpoint), ...
        'endpoint', 'duration');
    wideHand = unstack(table(network, duration, hand), 'hand', 'duration');
    wideTorque = unstack(table(network, duration, torque), 'torque', 'duration');
    output = table(wideEndpoint.network, wideEndpoint.x0_1, ...
        wideEndpoint.x0_2, wideEndpoint.x0_2 - wideEndpoint.x0_1, ...
        wideHand.x0_1, wideHand.x0_2, wideHand.x0_2 - wideHand.x0_1, ...
        wideTorque.x0_1, wideTorque.x0_2, wideTorque.x0_2 - wideTorque.x0_1, ...
        'VariableNames', {'Network','Endpoint100ms','Endpoint200ms', ...
        'Endpoint200Minus100','Hand100ms','Hand200ms','Hand200Minus100', ...
        'Torque100ms','Torque200ms','Torque200Minus100'});
end
