function audit = validate_stage2b_kao_gate3_complete(complete, inventory, cfg)
%VALIDATE_STAGE2B_KAO_GATE3_COMPLETE Enforce the finalized Gate-3 contract.

results = complete.results;
assert(complete.networkCount == cfg.ensemble.count, ...
    'Gate 3 must contain exactly 10 independent networks.');
assert(height(results.controller) == cfg.ensemble.count, ...
    'Controller table must contain one row per network.');
assert(height(results.targetValidation) == cfg.ensemble.count * 8 * 2, ...
    'Target validation must contain both controllers for all 80 cases.');
assert(all(results.controller.CareResidualRelative < ...
    cfg.validation.careResidualTolerance), ...
    'At least one CARE solution failed the residual tolerance.');
assert(all(results.controller.MaximumCareClosedLoopRealEigenvalue < 0), ...
    'At least one LQR closed loop is unstable.');
assert(all(results.targetValidation.FixedPointResidualNorm < ...
    cfg.validation.fixedPointTolerance), ...
    'At least one controller fixed-point identity failed.');
assert(all(results.targetValidation.JacobianDirectionalRelativeError < ...
    cfg.validation.jacobianDirectionalTolerance), ...
    'At least one analytical controller Jacobian failed finite differences.');
assert(all(results.targetValidation.SpectralAbscissaPerS < 0), ...
    'At least one target-specific Jacobian is unstable.');
assert(height(results.alignment) == cfg.ensemble.count, ...
    'Alignment table must contain one row per network.');
assert(height(results.alignmentNull) == cfg.ensemble.count * ...
    cfg.analysis.randomSubspaceDraws, ...
    'The project null table must retain 10,000 independent draws per network.');
assert(height(results.sourceAlignmentNull) == cfg.ensemble.count * ...
    cfg.analysis.randomSubspaceDraws, ...
    'The source-provenance null must retain 10,000 draws per network.');
drawCounts = groupsummary(results.alignmentNull, 'Network');
assert(all(drawCounts.GroupCount == cfg.analysis.randomSubspaceDraws), ...
    'Network-specific project null distributions cannot be pooled.');
assert(all(results.alignment.FiniteCorrectedLowerTailP >= ...
    1 / (cfg.analysis.randomSubspaceDraws + 1)), ...
    'Finite-corrected null p-values are invalid.');
assert(all(results.alignment.BhAdjustedLowerTailP >= ...
    results.alignment.FiniteCorrectedLowerTailP), ...
    'BH-adjusted alignment p-values cannot be smaller than raw p-values.');
assert(height(results.corticalDimensionality) == cfg.ensemble.count * 4, ...
    'Cortical PR table must contain two controllers and two epochs per network.');
assert(height(results.prStatistics) == 2, ...
    'Exactly two paired cortical-PR tests are required.');
assert(all(results.prStatistics.BhAdjustedP >= results.prStatistics.RawP), ...
    'BH-adjusted PR p-values cannot be smaller than raw p-values.');
assert(height(results.movement) == cfg.ensemble.count * 8 * 2 * ...
    numel(cfg.analysis.densePreparationDurationsS), ...
    'Dense Figure-5 movement diagnostic is incomplete.');
assert(all(ismember([0; .1; .2; .5], ...
    unique(results.movement.PreparationDurationS))), ...
    'Dense Figure-5 diagnostic is missing required preparation durations.');
assert(height(inventory) == 9, 'Exactly nine PNG/FIG pairs are required.');

expectedPng = inventory.Basename + ".png";
expectedFig = inventory.Basename + ".fig";
actualPng = string({dir(fullfile(cfg.workPlotsPngRoot, '*.png')).name});
actualFig = string({dir(fullfile(cfg.workPlotsFigRoot, '*.fig')).name});
assert(isequal(sort(actualPng(:)), sort(expectedPng(:))), ...
    'Work PNG folder contains missing or extra canonical figures.');
assert(isequal(sort(actualFig(:)), sort(expectedFig(:))), ...
    'Work FIG folder contains missing or extra canonical figures.');
assert(~any(startsWith(actualPng, '10_')) && ...
    ~any(startsWith(actualFig, '10_')), 'Canonical Figure 10 must be deleted.');

for figureIndex = 1:9
    imageInfo = imfinfo(inventory.PNG(figureIndex));
    assert(imageInfo.Width >= 1200 && imageInfo.Height >= 700, ...
        'Canonical PNG resolution is unexpectedly small.');
    reopened = openfig(inventory.FIG(figureIndex), 'invisible');
    assert(isgraphics(reopened), 'Canonical FIG could not be reopened.');
    close(reopened);
end

audit = struct();
audit.Status = 'PASS';
audit.NetworkCount = complete.networkCount;
audit.TargetValidationCount = height(results.targetValidation);
audit.ProjectNullDrawCount = height(results.alignmentNull);
audit.SourceNullDrawCount = height(results.sourceAlignmentNull);
audit.FigureCount = height(inventory);
audit.Figure10Deleted = true;
audit.AllFigFilesReopened = true;
audit.MaximumCareResidual = max(results.controller.CareResidualRelative);
audit.MaximumControlledRealPart = max( ...
    results.targetValidation.SpectralAbscissaPerS);
audit.MaximumJacobianError = max( ...
    results.targetValidation.JacobianDirectionalRelativeError);
end
