function validation = validate_stage2b_kao_gate3_components(cfg)
    stage1Path = fullfile(cfg.ensemble.stage1Root, 'network_01.mat');
    stage2aPath = fullfile(cfg.ensemble.stage2aRoot, ...
        'network_01_stage2a.mat');
    saved = load(stage1Path, 'model', 'networkRow');
    stage2aSaved = load(stage2aPath, 'networkResult');
    assert(saved.networkRow.Pass && saved.networkRow.AcceptedMember == 1);
    [result, representative] = analyze_stage2b_kao_gate3_network(cfg, ...
        saved.model, 1, stage2aSaved, NullDraws=25, ...
        RunDenseMovement=false, RunCloud=false);
    assert(result.controller.CareResidualRelative < ...
        cfg.validation.careResidualTolerance);
    assert(max(result.targetValidation.FixedPointResidualNorm) < ...
        cfg.validation.fixedPointTolerance);
    assert(max(result.targetValidation.JacobianDirectionalRelativeError) < ...
        cfg.validation.jacobianDirectionalTolerance);
    assert(all(result.targetValidation.SpectralAbscissaPerS < 0));
    assert(height(result.alignmentNull) == 25);
    assert(result.alignment.K >= 1 && result.alignment.K <= saved.model.n);
    assert(size(representative.geometry.prepMatrix, 2) == 240);
    assert(size(representative.geometry.moveMatrix, 2) == 240);
    test = paired_wilcoxon_exact((1:10).', (2:11).');
    adjusted = bh_adjust([0.01; 0.04]);
    assert(test.p > 0 && test.p <= 1);
    assert(all(adjusted >= [0.01; 0.04]));
    validation = struct('passed', true, ...
        'careResidualRelative', result.controller.CareResidualRelative, ...
        'maximumFixedPointResidual', ...
        max(result.targetValidation.FixedPointResidualNorm), ...
        'maximumJacobianDirectionalRelativeError', ...
        max(result.targetValidation.JacobianDirectionalRelativeError), ...
        'projectK95', result.alignment.K, ...
        'projectObservedAlignment', result.alignment.ObservedAlignment, ...
        'projectNullMedian25DrawSmoke', result.alignment.NullMedian, ...
        'preparationObservations', size(representative.geometry.prepMatrix, 2), ...
        'movementObservations', size(representative.geometry.moveMatrix, 2));
end
