function files = create_stage1_active_set_figures(cfg, diagnostic, results, ...
        representative)
    % Stage-1-only extraction; preserved figures are not regenerated by reset.
    files.stage1Representative = representative_figure(cfg, diagnostic, ...
        representative.movement);
    files.stage1Quantitative = stage1_quantitative_figure(cfg, diagnostic, results);
end

function files = representative_figure(cfg, diagnostic, representative)
    handle = figure('Visible', 'off', 'Color', 'w', ...
        'Position', [50, 50, 1700, 1000]);
    layout = tiledlayout(handle, 2, 2, 'TileSpacing', 'compact', ...
        'Padding', 'compact');
    inactivePercent = 100 * (1 - squeeze(mean( ...
        representative.activeRaster, 1)));
    ax = nexttile(layout);
    imagesc(ax, 1:8, 1:200, inactivePercent);
    colormap(ax, white_to_color([0.35, 0.16, 0.62]));
    colorScale = colorbar(ax, 'eastoutside');
    colorScale.Label.String = 'Movement time inactive (%)';
    xlabel(ax, 'Target'); ylabel(ax, 'Ordered neuron');
    xticks(ax, 1:8); xticklabels(ax, compose('T%d', 1:8));
    title(ax, 'A  Shared ON/OFF participation');
    text(ax, 1.15, 193, 'Zero = active throughout', ...
        'Color', [0.25, 0.25, 0.25], 'FontSize', cfg.plot.fontSize - 1);
    apply_plot_style(ax, cfg);
    ax = nexttile(layout);
    imagesc(ax, 1:8, 1:200, representative.meanRatesNormalized);
    colormap(ax, parula(256));
    colorScale = colorbar(ax, 'eastoutside');
    colorScale.Label.String = 'Normalized mean movement firing rate';
    xlabel(ax, 'Target'); ylabel(ax, 'Same ordered neurons');
    xticks(ax, 1:8); xticklabels(ax, compose('T%d', 1:8));
    title(ax, 'B  Target-specific continuous amplitudes');
    apply_plot_style(ax, cfg);
    ax = nexttile(layout, 3, [1, 2]);
    target = 2;
    targetRaster = squeeze(representative.activeRaster(:, :, target)).';
    image(ax, 1000 * representative.timesS, 1:200, 1 + targetRaster);
    colormap(ax, [1, 1, 1; 0.08, 0.08, 0.08]);
    clim(ax, [1, 2]); hold(ax, 'on');
    switchingRows = find(any(diff(targetRaster, 1, 2) ~= 0, 2));
    for row = switchingRows.'
        yline(ax, row, '-', 'Color', [0.85, 0.15, 0.12], ...
            'LineWidth', 1.2);
    end
    xlabel(ax, 'Movement time (ms)'); ylabel(ax, 'Same ordered neurons');
    title(ax, sprintf(['Inset  N1/T2 binary activity; red line marks %d ' ...
        'switching neuron'], numel(switchingRows)));
    apply_plot_style(ax, cfg);
    sgtitle(handle, ['Gate 2 — network 1: shared active population, ' ...
        'target-specific firing amplitudes']);
    files = save_bundle(handle, ...
        'stage1_representative_active_set_raster_and_rate_heatmap', ...
        diagnostic.stage1FigRoot, diagnostic.stage1PngRoot, cfg.plot.resolution);
end

function files = stage1_quantitative_figure(cfg, diagnostic, results)
    handle = figure('Visible', 'off', 'Color', 'w', ...
        'Position', [50, 50, 1650, 760]);
    layout = tiledlayout(handle, 1, 2, 'TileSpacing', 'compact', ...
        'Padding', 'compact');
    layout.OuterPosition = [0, 0.08, 1, 0.86];
    switching = network_target_matrix(results.stage1Target, ...
        'SwitchingFraction') * 100;
    endpointMm = network_target_matrix(results.frozenRegimeTarget, ...
        'EndpointErrorM') * 1000;
    ax = nexttile(layout);
    imagesc(ax, 1:8, 1:10, switching);
    colormap(ax, white_to_color([0.10, 0.42, 0.72]));
    clim(ax, [0, 1.5]);
    colorScale = colorbar(ax, 'eastoutside');
    colorScale.Label.String = 'Neurons switching at least once (%)';
    colorScale.Ticks = [0, 0.5, 1, 1.5];
    annotate_nonzero_cells(ax, switching, @(value) sprintf('%.1f', value), 0.5);
    configure_heatmap_axes(ax, 'A  Threshold crossings', cfg);
    ax = nexttile(layout);
    endpointColor = log10(1 + endpointMm);
    imagesc(ax, 1:8, 1:10, endpointColor);
    colormap(ax, white_to_color([0.78, 0.12, 0.12]));
    maximumMm = max(endpointMm, [], 'all');
    clim(ax, [0, log10(1 + maximumMm)]);
    colorScale = colorbar(ax, 'eastoutside');
    rawTicks = [0, 1, 10, 100, 400];
    rawTicks = rawTicks(rawTicks <= max(400, maximumMm));
    colorScale.Ticks = log10(1 + rawTicks);
    colorScale.TickLabels = compose('%g', rawTicks);
    colorScale.Label.String = 'Endpoint mismatch (mm; log color mapping)';
    annotate_nonzero_cells(ax, endpointMm, @endpoint_label, 1.5);
    configure_heatmap_axes(ax, 'B  GO-active-set-frozen mismatch', cfg);
    annotation(handle, 'textbox', [0.12, 0.012, 0.76, 0.05], ...
        'String', ['72/80 movements exact under frozen active set   |   ' ...
        '8/80 show threshold crossings   |   target-union Jaccard ' ...
        '= 1 for 280/280 target pairs'], 'HorizontalAlignment', ...
        'center', 'EdgeColor', 'none', 'FontWeight', 'bold', ...
        'FontSize', cfg.plot.fontSize);
    sgtitle(handle, ['Gate 2 — all networks and targets: sparse switching ' ...
        'can produce material nonlinear movement errors']);
    files = save_bundle(handle, ...
        'stage1_switching_overlap_and_frozen_regime_test', ...
        diagnostic.stage1FigRoot, diagnostic.stage1PngRoot, cfg.plot.resolution);
end

function output = save_bundle(handle, name, figRoot, pngRoot, resolution)
    if ~isfolder(figRoot), mkdir(figRoot); end
    if ~isfolder(pngRoot), mkdir(pngRoot); end
    output.fig = fullfile(figRoot, [name, '.fig']);
    output.png = fullfile(pngRoot, [name, '.png']);
    savefig(handle, output.fig);
    exportgraphics(handle, output.png, 'Resolution', resolution, ...
        'BackgroundColor', 'white');
    close(handle);
end

function matrix = network_target_matrix(input, variable)
    matrix = nan(10, 8);
    for row = 1:height(input)
        matrix(input.Network(row), input.Target(row)) = input.(variable)(row);
    end
    assert(all(isfinite(matrix), 'all'));
end

function configure_heatmap_axes(ax, titleText, cfg)
    xlabel(ax, 'Target'); ylabel(ax, 'Network');
    xticks(ax, 1:8); xticklabels(ax, compose('T%d', 1:8));
    yticks(ax, 1:10); yticklabels(ax, compose('N%d', 1:10));
    title(ax, titleText); axis(ax, 'tight'); apply_plot_style(ax, cfg);
end

function annotate_nonzero_cells(ax, matrix, formatter, threshold)
    for network = 1:size(matrix, 1)
        for target = 1:size(matrix, 2)
            value = matrix(network, target);
            if value > 0
                if value >= threshold
                    color = [1, 1, 1];
                else
                    color = [0.12, 0.12, 0.12];
                end
                text(ax, target, network, formatter(value), ...
                    'HorizontalAlignment', 'center', 'Color', color, ...
                    'FontWeight', 'bold', 'FontSize', 9);
            end
        end
    end
end

function label = endpoint_label(value)
    if value >= 100
        label = sprintf('%.0f', value);
    elseif value >= 10
        label = sprintf('%.1f', value);
    elseif value >= 1
        label = sprintf('%.2f', value);
    elseif value >= 0.1
        label = sprintf('%.2f', value);
    else
        label = sprintf('%.3f', value);
    end
end

function map = white_to_color(color)
    weights = linspace(0, 1, 256).';
    map = (1 - weights) .* ones(256, 3) + weights .* color;
end

function apply_plot_style(ax, cfg)
    set(ax, 'FontSize', cfg.plot.fontSize, 'TickDir', 'out', ...
        'LineWidth', cfg.plot.axisLineWidth, 'XColor', [0, 0, 0], ...
        'YColor', [0, 0, 0]);
    grid(ax, 'off'); box(ax, 'off');
end
