function report = audit_stage1_gate1_failure(projectRoot)
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    cfg = stage_1_gate1_config(projectRoot);
    roots = ["config/stage_2b_kao_config.m", ...
        "config/stage_2b_cerebellum_config.m", "src/stage_2a", ...
        "src/stage_2b_kao", "src/stage_2b_cerebellum", ...
        "analysis/stage_2a", "analysis/stage_2b_shared", ...
        "figures/stage_2a", "figures/stage_2b_shared", ...
        "results/stage_2a", "results/stage_2b_kao", ...
        "results/stage_2b_cerebellum", "plots/stage_2a", ...
        "plots/stage_2b_kao", "plots/stage_2b_cerebellum"];
    before = readtable(fullfile(cfg.gate1.auditRoot, ...
        'stage2_frozen_hashes_before.csv'), 'TextType', 'string');
    after = hash_tree(projectRoot, roots);
    writetable(after, fullfile(cfg.gate1.auditRoot, ...
        'stage2_frozen_hashes_after_failed_run.csv'));
    pinned = verify_pinned_reference(cfg);
    unchanged = isequal(before, after);
    report = struct('status', 'STOPPED_AT_TARGET_TORQUE_ENDPOINT_GATE', ...
        'stage2ArtifactsUnchanged', unchanged, ...
        'pinnedManifestEntries', pinned.manifestEntries, ...
        'pinnedManifestAllMatched', pinned.allMatched, ...
        'sourceHead', pinned.sourceHead, 'stage2FileCount', height(after), ...
        'ensembleGenerated', false, 'stage2AStarted', false);
    fid = fopen(fullfile(cfg.gate1.auditRoot, ...
        'gate1_failed_run_audit.json'), 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(report, PrettyPrint=true));
    clear cleanup;
    assert(unchanged, 'Frozen Stage-2 artifacts changed.');
    fprintf(['Post-failure audit PASS: Stage 2 %d files unchanged; ' ...
        'pinned %d/%d hashes matched; HEAD %s.\n'], height(after), ...
        pinned.hashMatches, pinned.manifestEntries, pinned.sourceHead);
end
