function diagnosis = classify_target_torque_diagnostic(tableData, gateThresholdM)
    native = tableData(tableData.Benchmark == "Pinned native Kao", :);
    original = tableData(tableData.Benchmark == "MATLAB original geometry", :);
    project = tableData(tableData.Benchmark == "MATLAB new geometry", :);
    nativeFailures = native.Target(~native.ProjectEndpointGatePass).';
    originalFailures = original.Target(~original.ProjectEndpointGatePass).';
    projectFailures = project.Target(~project.ProjectEndpointGatePass).';
    nativeMedianObjective = median(native.SourceTotalObjective);
    originalMedianObjective = median(original.SourceTotalObjective);
    objectiveRatio = originalMedianObjective / max(nativeMedianObjective, realmin);
    originalMaterialDisagreement = ~isempty(originalFailures) ...
        || objectiveRatio > 2 ...
        || max(original.EndpointErrorM) > 2 * max(native.EndpointErrorM);
    if originalMaterialDisagreement
        classification = "source-translation/implementation discrepancy";
    elseif ~isempty(projectFailures)
        classification = "new-direction-specific optimizer/arm-geometry difficulty";
    elseif ~isempty(nativeFailures)
        classification = "project endpoint gate stricter than source procedure";
    else
        classification = "no endpoint-gate failure reproduced";
    end
    diagnosis = struct('classification', char(classification), ...
        'projectEndpointThresholdM', gateThresholdM, ...
        'thresholdOrigin', ['Project-defined in config/stage_1_gate1_config.m; ' ...
        'absent from pinned construct/reaches.ml, biomechanics_arm.ml, and STAR Methods.'], ...
        'nativeFailingTargets', nativeFailures, ...
        'originalGeometryFailingTargets', originalFailures, ...
        'newGeometryFailingTargets', projectFailures, ...
        'nativeMaximumEndpointErrorM', max(native.EndpointErrorM), ...
        'originalMaximumEndpointErrorM', max(original.EndpointErrorM), ...
        'newMaximumEndpointErrorM', max(project.EndpointErrorM), ...
        'nativeMedianSourceObjective', nativeMedianObjective, ...
        'originalMedianSourceObjective', originalMedianObjective, ...
        'originalToNativeMedianObjectiveRatio', objectiveRatio, ...
        'sourceHasTerminalEndpointCriterion', false);
end
