function [networkRow, targetRows, rollout, hand] = ...
        evaluate_stage1_gate1_candidate(cfg, model, calibration, recurrent, ...
        target, targetTorques, attempt, recurrentSeed, calibrationSeed, ...
        acceptedMember)
    rollout = simulate_published_cortex(model, model.xstar, true);
    [~, hand] = simulate_published_arm(model, rollout.torque);
    desiredAngles = mod(cfg.gate1.targetAnglesDeg(:), 360);
    desiredEndpoint = target.initialHand([1, 3]) + target.endpointDisplacement;
    endpoint = squeeze(hand(end, [1, 3], :)).';
    displacement = endpoint - target.initialHand([1, 3]);
    actualAngles = mod(atan2d(displacement(:, 2), displacement(:, 1)), 360);
    angleError = mod(actualAngles - desiredAngles + 180, 360) - 180;
    actualRadius = vecnorm(displacement, 2, 2);
    radiusError = actualRadius - cfg.gate1.radiusM;
    endpointError = vecnorm(endpoint - desiredEndpoint, 2, 2);
    count = numel(desiredAngles);
    handTrajectoryRmseM = zeros(count, 1);
    torqueRmse = zeros(count, 1);
    targetPass = false(count, 1);
    for targetId = 1:count
        handDifference = hand(:, [1, 3], targetId) ...
            - target.hands(:, [1, 3], targetId);
        handTrajectoryRmseM(targetId) = sqrt(mean(handDifference.^2, 'all'));
        torqueDifference = rollout.torque(:, :, targetId) ...
            - targetTorques(:, :, targetId);
        torqueRmse(targetId) = sqrt(mean(torqueDifference.^2, 'all'));
        targetPass(targetId) = abs(angleError(targetId)) ...
            <= cfg.gate1.validation.maxAngleErrorDeg ...
            && abs(radiusError(targetId)) ...
            <= cfg.gate1.validation.maxRadiusErrorM ...
            && endpointError(targetId) ...
            <= cfg.gate1.validation.maxEndpointErrorM;
    end
    weightedDifference = rollout.torque - targetTorques;
    weightedDifference(:, 2, :) = cfg.gate1.weightedTorqueScale(2) ...
        * weightedDifference(:, 2, :);
    weightedTorqueCost = model.samplingDt / model.nMovements ...
        * sum(weightedDifference.^2, 'all');
    architecturePass = isequal(size(model.W), [cfg.gate1.n, cfg.gate1.n]) ...
        && nnz(model.W(:, 1:cfg.gate1.nE) < 0) == 0 ...
        && nnz(model.W(:, (cfg.gate1.nE + 1):end) > 0) == 0 ...
        && nnz(diag(model.W)) == 0;
    finiteDynamicsPass = all(isfinite([model.W(:); model.xstar(:); ...
        model.C(:); rollout.rates(:); rollout.torque(:); hand(:)]));
    recurrentStabilityPass = recurrent.savedSpectralAbscissa ...
        <= cfg.gate1.socStopSpectralAbscissa + 1e-12;
    sourceMovementCostPass = calibration.finalMoveCost ...
        <= cfg.gate1.calibrationMoveCostStop;
    weightedTorquePass = weightedTorqueCost ...
        <= cfg.gate1.validation.maxWeightedTorqueCost;
    pass = all(targetPass) && architecturePass && finiteDynamicsPass ...
        && recurrentStabilityPass && sourceMovementCostPass && weightedTorquePass;
    failures = strings(0, 1);
    failedAngles = find(abs(angleError) > cfg.gate1.validation.maxAngleErrorDeg);
    failedRadii = find(abs(radiusError) > cfg.gate1.validation.maxRadiusErrorM);
    failedEndpoints = find(endpointError > cfg.gate1.validation.maxEndpointErrorM);
    if ~isempty(failedAngles)
        failures(end + 1) = "angle targets " + join(string(failedAngles), ",");
    end
    if ~isempty(failedRadii)
        failures(end + 1) = "radius targets " + join(string(failedRadii), ",");
    end
    if ~isempty(failedEndpoints)
        failures(end + 1) = "endpoint targets " + join(string(failedEndpoints), ",");
    end
    if ~sourceMovementCostPass
        failures(end + 1) = "source movement cost";
    end
    if ~weightedTorquePass
        failures(end + 1) = "weighted torque cost";
    end
    if ~architecturePass
        failures(end + 1) = "recurrent architecture";
    end
    if ~recurrentStabilityPass
        failures(end + 1) = "recurrent stability";
    end
    if ~finiteDynamicsPass
        failures(end + 1) = "nonfinite dynamics";
    end
    if isempty(failures)
        failureReason = "";
    else
        failureReason = join(failures, "; ");
    end
    networkRow = table(attempt, recurrentSeed, calibrationSeed, ...
        acceptedMember, pass, failureReason, max(abs(angleError)), ...
        max(abs(radiusError)), max(endpointError), weightedTorqueCost, ...
        calibration.finalMoveCost, calibration.iterations, ...
        string(calibration.stopReason), calibration.finalGradientNorm, ...
        calibration.readoutNullResidual, recurrent.iterations, ...
        recurrent.savedSpectralAbscissa, architecturePass, ...
        recurrentStabilityPass, finiteDynamicsPass, sourceMovementCostPass, ...
        weightedTorquePass, ...
        'VariableNames', {'Attempt','RecurrentSeed','CalibrationSeed', ...
        'AcceptedMember','Pass','FailureReason','MaxAngleErrorDeg', ...
        'MaxRadiusErrorM','MaxEndpointErrorM','WeightedTorqueCost', ...
        'SourceMovementCost','CalibrationIterations','CalibrationStopReason', ...
        'FinalGradientNorm','ReadoutNullResidual','RecurrentIterations', ...
        'SpectralAbscissaW','ArchitecturePass','RecurrentStabilityPass', ...
        'FiniteDynamicsPass','SourceMovementCostPass','WeightedTorquePass'});
    attemptColumn = repmat(attempt, count, 1);
    acceptedMemberColumn = repmat(acceptedMember, count, 1);
    recurrentSeedColumn = repmat(recurrentSeed, count, 1);
    calibrationSeedColumn = repmat(calibrationSeed, count, 1);
    targetId = (1:count).';
    targetRows = table(attemptColumn, acceptedMemberColumn, ...
        recurrentSeedColumn, calibrationSeedColumn, targetId, desiredAngles, ...
        actualAngles, angleError, cfg.gate1.radiusM * ones(count, 1), ...
        actualRadius, radiusError, endpointError, handTrajectoryRmseM, ...
        torqueRmse, targetPass, ...
        'VariableNames', {'Attempt','AcceptedMember','RecurrentSeed', ...
        'CalibrationSeed','Target','DesiredAngleDeg','ActualAngleDeg', ...
        'AngularErrorDeg','DesiredRadiusM','ActualRadiusM','RadiusErrorM', ...
        'EndpointErrorM','HandTrajectoryRmseM','TorqueRmse','Pass'});
end
