function summary = finalize_stage1_gate1_ensemble_failure(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src', 'published_generator'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    cfg = stage_1_gate1_config(projectRoot);
    targetBundle = load(fullfile(cfg.gate1.targetRoot, ...
        'stage1_gate1_targets.mat'), 'target', 'targetTorques', 'summary');
    models = cell(cfg.gate1.networkCount, 1);
    calibrationDiagnostics = cell(cfg.gate1.networkCount, 1);
    recurrentDiagnostics = cell(cfg.gate1.networkCount, 1);
    for member = 1:cfg.gate1.networkCount
        saved = load(fullfile(cfg.gate1.ensembleRoot, ...
            sprintf('network_%02d.mat', member)));
        models{member} = saved.model;
        calibrationDiagnostics{member} = saved.calibration;
        recurrentDiagnostics{member} = saved.recurrent;
    end
    [audit, targetAudit] = audit_stage1_gate1_ensemble(cfg, models, ...
        calibrationDiagnostics, recurrentDiagnostics, targetBundle.target, ...
        targetBundle.targetTorques);
    writetable(audit, fullfile(cfg.gate1.auditRoot, 'network_audit.csv'));
    writetable(targetAudit, fullfile(cfg.gate1.auditRoot, ...
        'network_target_audit.csv'));
    network = (1:cfg.gate1.networkCount).';
    calibrationSeed = cfg.gate1.calibrationSeeds(:);
    calibrationIterations = zeros(cfg.gate1.networkCount, 1);
    calibrationStopReason = strings(cfg.gate1.networkCount, 1);
    finalLoss = zeros(cfg.gate1.networkCount, 1);
    finalMoveCost = zeros(cfg.gate1.networkCount, 1);
    finalRegularization = zeros(cfg.gate1.networkCount, 1);
    finalRelativeChange = zeros(cfg.gate1.networkCount, 1);
    finalGradientNorm = zeros(cfg.gate1.networkCount, 1);
    readoutNullResidual = zeros(cfg.gate1.networkCount, 1);
    recurrentSeed = strings(cfg.gate1.networkCount, 1);
    recurrentIterations = nan(cfg.gate1.networkCount, 1);
    savedSpectralAbscissa = zeros(cfg.gate1.networkCount, 1);
    architecturePass = false(cfg.gate1.networkCount, 1);
    for member = 1:cfg.gate1.networkCount
        calibration = calibrationDiagnostics{member};
        recurrent = recurrentDiagnostics{member};
        model = models{member};
        calibrationIterations(member) = calibration.iterations;
        calibrationStopReason(member) = string(calibration.stopReason);
        finalLoss(member) = calibration.finalLoss;
        finalMoveCost(member) = calibration.finalMoveCost;
        finalRegularization(member) = calibration.finalRegularization;
        finalRelativeChange(member) = calibration.finalRelativeChange;
        finalGradientNorm(member) = calibration.finalGradientNorm;
        readoutNullResidual(member) = calibration.readoutNullResidual;
        if member == cfg.gate1.pinnedMember
            recurrentSeed(member) = "official released realization";
        else
            recurrentSeed(member) = string(cfg.gate1.generatedNetworkSeeds(member - 1));
            recurrentIterations(member) = recurrent.iterations;
        end
        savedSpectralAbscissa(member) = recurrent.savedSpectralAbscissa;
        architecturePass(member) = isequal(size(model.W), [cfg.gate1.n, cfg.gate1.n]) ...
            && nnz(model.W(:, 1:cfg.gate1.nE) < 0) == 0 ...
            && nnz(model.W(:, (cfg.gate1.nE + 1):end) > 0) == 0 ...
            && nnz(diag(model.W)) == 0 ...
            && all(isfinite([model.W(:); model.xstar(:); model.C(:)]));
    end
    calibrationAudit = table(network, calibrationSeed, ...
        calibrationIterations, calibrationStopReason, finalLoss, ...
        finalMoveCost, finalRegularization, finalRelativeChange, ...
        finalGradientNorm, readoutNullResidual);
    recurrentAudit = table(network, recurrentSeed, recurrentIterations, ...
        savedSpectralAbscissa, architecturePass);
    writetable(calibrationAudit, fullfile(cfg.gate1.auditRoot, ...
        'calibration_audit.csv'));
    writetable(recurrentAudit, fullfile(cfg.gate1.auditRoot, ...
        'recurrent_substrate_audit.csv'));
    stage2Roots = ["config/stage_2b_kao_config.m", ...
        "config/stage_2b_cerebellum_config.m", "src/stage_2a", ...
        "src/stage_2b_kao", "src/stage_2b_cerebellum", ...
        "analysis/stage_2a", "analysis/stage_2b_shared", ...
        "figures/stage_2a", "figures/stage_2b_shared", ...
        "results/stage_2a", "results/stage_2b_kao", ...
        "results/stage_2b_cerebellum", "plots/stage_2a", ...
        "plots/stage_2b_kao", "plots/stage_2b_cerebellum"];
    stage2Before = readtable(fullfile(cfg.gate1.auditRoot, ...
        'stage2_frozen_hashes_before.csv'), TextType='string');
    stage2After = hash_tree(projectRoot, stage2Roots);
    writetable(stage2After, fullfile(cfg.gate1.auditRoot, ...
        'stage2_frozen_hashes_after_failed_ensemble.csv'));
    stage2Unchanged = isequal(stage2Before, stage2After);
    pinned = verify_pinned_reference(cfg);
    failedRows = targetAudit(~targetAudit.Pass, :);
    failedNetworks = unique(failedRows.Network).';
    summary = struct('status', 'STOPPED_AT_ENSEMBLE_VALIDATION', ...
        'scope', cfg.gate1.status, 'sourceCommit', cfg.gate1.sourceCommit, ...
        'targetRadiusM', cfg.gate1.radiusM, ...
        'targetAnglesDeg', cfg.gate1.targetAnglesDeg, ...
        'targetLayerPassed', targetBundle.summary.allTargetsPassed, ...
        'networkCountConstructed', height(audit), ...
        'formalNetworksPassed', sum(audit.pass), ...
        'formalNetworksFailed', sum(~audit.pass), ...
        'failedNetworks', failedNetworks, ...
        'failedTargetRows', height(failedRows), ...
        'maximumAngleErrorDeg', max(audit.maxAngleErrorDeg), ...
        'maximumRadiusErrorM', max(audit.maxRadiusErrorM), ...
        'maximumEndpointErrorM', max(audit.maxEndpointErrorM), ...
        'maximumWeightedTorqueCost', max(audit.weightedTorqueCost), ...
        'allArchitectureChecksPassed', all(architecturePass), ...
        'allCalibrationMoveCostsPassed', ...
        all(finalMoveCost <= cfg.gate1.calibrationMoveCostStop), ...
        'angleThresholdDeg', cfg.gate1.validation.maxAngleErrorDeg, ...
        'radiusThresholdM', cfg.gate1.validation.maxRadiusErrorM, ...
        'endpointThresholdM', cfg.gate1.validation.maxEndpointErrorM, ...
        'weightedTorqueThreshold', cfg.gate1.validation.maxWeightedTorqueCost, ...
        'pinnedManifestEntries', pinned.manifestEntries, ...
        'pinnedManifestAllMatched', pinned.allMatched, ...
        'stage2ArtifactsUnchanged', stage2Unchanged, ...
        'canonicalPlotsRegenerated', false, ...
        'stage1CleanupPerformed', false, ...
        'stage2Executed', false, ...
        'interpretation', ['Four networks narrowly exceeded only the unchanged ' ...
        '2-degree angular gate. All other formal behavior, calibration, architecture, ' ...
        'finite-value, pinned-provenance, and frozen-Stage-2 checks passed. ' ...
        'The ensemble is not accepted because no threshold waiver or retuning is authorized.']);
    assert(pinned.allMatched, 'Pinned Kao reference verification failed.');
    assert(stage2Unchanged, 'A frozen Stage-2 artifact changed.');
    fid = fopen(fullfile(cfg.gate1.auditRoot, ...
        'gate1_failed_ensemble_audit.json'), 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(summary, PrettyPrint=true));
    clear cleanup;
    manifest = hash_tree(projectRoot, "results/stage_1/current");
    manifest(endsWith(manifest.relative_path, ...
        'failed_ensemble_artifact_manifest.csv'), :) = [];
    writetable(manifest, fullfile(cfg.gate1.auditRoot, ...
        'failed_ensemble_artifact_manifest.csv'));
end
