function report = finalize_stage1_gate1_acceptance(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    cfg = stage_1_gate1_config(projectRoot);
    acceptedAudit = readtable(fullfile(cfg.gate1.auditRoot, ...
        'accepted_ensemble_audit.csv'));
    acceptedTargetAudit = readtable(fullfile(cfg.gate1.auditRoot, ...
        'accepted_ensemble_target_audit.csv'));
    assert(height(acceptedAudit) == 10 && all(acceptedAudit.Pass) ...
        && height(acceptedTargetAudit) == 80 && all(acceptedTargetAudit.Pass), ...
        'The canonical accepted audit is not 10 networks / 80 passing targets.');
    historyRoot = fullfile(cfg.resultsRoot, 'audit_history');
    attemptedAudit = readtable(fullfile(historyRoot, ...
        'rejection_sampling_run_20260831', 'audit', ...
        'attempted_realization_audit.csv'));
    stage2Roots = ["config/stage_2b_kao_config.m", ...
        "config/stage_2b_cerebellum_config.m", "src/stage_2a", ...
        "src/stage_2b_kao", "src/stage_2b_cerebellum", ...
        "analysis/stage_2a", "analysis/stage_2b_shared", ...
        "figures/stage_2a", "figures/stage_2b_shared", ...
        "results/stage_2a", "results/stage_2b_kao", ...
        "results/stage_2b_cerebellum", "plots/stage_2a", ...
        "plots/stage_2b_kao", "plots/stage_2b_cerebellum"];
    stage2Before = readtable(fullfile(cfg.gate1.auditRoot, ...
        'stage2_frozen_hashes_before.csv'), TextType='string');
    stage2After = hash_tree(projectRoot, stage2Roots);
    stage2Unchanged = isequal(stage2Before, stage2After);
    assert(stage2Unchanged, 'A frozen Stage-2 artifact changed during Gate 1.');
    writetable(stage2After, fullfile(cfg.gate1.auditRoot, ...
        'stage2_frozen_hashes_after.csv'));
    pinned = verify_pinned_reference(cfg);
    assert(pinned.allMatched, 'Pinned Kao benchmark verification failed.');
    pngFiles = dir(fullfile(cfg.plotsPngRoot, '*.png'));
    figFiles = dir(fullfile(cfg.plotsFigRoot, '*.fig'));
    pngNames = sort(erase(string({pngFiles.name}), '.png'));
    figNames = sort(erase(string({figFiles.name}), '.fig'));
    assert(numel(pngNames) == 8 && isequal(pngNames, figNames), ...
        'Canonical figure inventory is not exactly eight matched PNG/FIG pairs.');
    for index = 1:numel(figFiles)
        handle = openfig(fullfile(figFiles(index).folder, ...
            figFiles(index).name), 'invisible');
        assert(isgraphics(handle), 'A canonical FIG failed to reopen.');
        close(handle);
    end
    codeRoots = ["config/published_generator_config.m", ...
        "config/stage_1_gate1_config.m", "src/published_generator", ...
        "analysis/published_generator", "figures/published_generator", ...
        "run_all.m", "run_stage_1.m", ...
        "workflows/stage_1/construction/run_stage_1_gate1_target_validation.m", ...
        "workflows/stage_1/construction/run_stage_1_gate1_rejection_sampling.m", ...
        "README.md", "MODEL_SPEC.md", "AGENTS.md", ...
        "THIRD_PARTY_PROVENANCE.md"];
    codeManifest = hash_tree(projectRoot, codeRoots);
    writetable(codeManifest, fullfile(cfg.gate1.auditRoot, ...
        'stage1_active_code_manifest.csv'));
    historyManifest = hash_tree(projectRoot, "results/stage_1/audit_history");
    historyManifest(endsWith(historyManifest.relative_path, ...
        'history_manifest.csv'), :) = [];
    writetable(historyManifest, fullfile(historyRoot, 'history_manifest.csv'));
    report = struct('status', 'ACCEPTED — FROZEN', ...
        'targetRadiusM', cfg.gate1.radiusM, ...
        'targetAnglesDeg', cfg.gate1.targetAnglesDeg, ...
        'attemptedCount', height(attemptedAudit), ...
        'acceptedCount', sum(attemptedAudit.Pass), ...
        'rejectedCount', sum(~attemptedAudit.Pass), ...
        'acceptanceRate', mean(attemptedAudit.Pass), ...
        'acceptedRecurrentSeeds', acceptedAudit.RecurrentSeed.', ...
        'acceptedCalibrationSeeds', acceptedAudit.CalibrationSeed.', ...
        'maximumAngleErrorDeg', max(acceptedAudit.MaxAngleErrorDeg), ...
        'maximumRadiusErrorM', max(acceptedAudit.MaxRadiusErrorM), ...
        'maximumEndpointErrorM', max(acceptedAudit.MaxEndpointErrorM), ...
        'maximumWeightedTorqueCost', max(acceptedAudit.WeightedTorqueCost), ...
        'allAcceptedTargetRowsPassed', all(acceptedTargetAudit.Pass), ...
        'figurePairCount', numel(figFiles), 'allFiguresReopened', true, ...
        'pinnedManifestEntries', pinned.manifestEntries, ...
        'pinnedManifestAllMatched', pinned.allMatched, ...
        'stage2FileCount', height(stage2After), ...
        'stage2ArtifactsUnchanged', stage2Unchanged, ...
        'historyArtifactCount', height(historyManifest), ...
        'activeCodeFileCount', height(codeManifest), ...
        'stage2Executed', false);
    fid = fopen(fullfile(cfg.gate1.auditRoot, ...
        'stage1_final_acceptance_report.json'), 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(report, PrettyPrint=true));
    clear cleanup;
    artifactRoots = ["results/stage_1/current", ...
        "plots/stage_1/png", "plots/stage_1/fig"];
    artifactManifest = hash_tree(projectRoot, artifactRoots);
    excluded = endsWith(artifactManifest.relative_path, ...
        'stage1_current_artifact_manifest.csv') ...
        | endsWith(artifactManifest.relative_path, ...
        'stage1_manifest_verification.json');
    artifactManifest(excluded, :) = [];
    manifestPath = fullfile(cfg.gate1.auditRoot, ...
        'stage1_current_artifact_manifest.csv');
    writetable(artifactManifest, manifestPath);
    allManifestEntriesMatched = verify_manifest(projectRoot, artifactManifest);
    assert(allManifestEntriesMatched, ...
        'Final Stage-1 artifact manifest failed immediate verification.');
    verification = struct('verified', true, ...
        'artifactCount', height(artifactManifest), ...
        'historyArtifactCount', height(historyManifest), ...
        'activeCodeFileCount', height(codeManifest));
    fid = fopen(fullfile(cfg.gate1.auditRoot, ...
        'stage1_manifest_verification.json'), 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(verification, PrettyPrint=true));
end

function matched = verify_manifest(projectRoot, manifest)
    matched = true;
    for row = 1:height(manifest)
        path = fullfile(projectRoot, manifest.relative_path(row));
        if ~isfile(path) || dir(path).bytes ~= manifest.bytes(row) ...
                || sha256_file(path) ~= manifest.sha256(row)
            matched = false;
            return
        end
    end
end
