function report = revalidate_stage1_accepted_ensemble(projectRoot, outputRoot)
    % One bounded 10-by-8 forward regression; never writes canonical results.
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    if nargin < 2, outputRoot = ''; end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src', 'published_generator'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    cfg = stage_1_gate1_config(projectRoot);
    require_kao_reference(cfg);
    pinned = verify_pinned_reference(cfg);
    native = load_published_generator(cfg);
    smoke = run_stage1_smoke_tests(cfg, native);
    targetBundle = load(fullfile(cfg.gate1.targetRoot, ...
        'stage1_gate1_targets.mat'), 'target', 'targetTorques', 'summary');
    assert(targetBundle.summary.allTargetsPassed);
    originalAudit = readtable(fullfile(cfg.gate1.auditRoot, ...
        'accepted_ensemble_audit.csv'), TextType='string');
    originalTargets = readtable(fullfile(cfg.gate1.auditRoot, ...
        'accepted_ensemble_target_audit.csv'), TextType='string');
    assert(height(originalAudit) == 10 && all(originalAudit.Pass));
    assert(height(originalTargets) == 80 && all(originalTargets.Pass));
    referenceFiles = {'stage1_primary_analysis.mat', ...
        'stage1_gate1_complete_results.mat'};
    revalidatedAudit = table();
    revalidatedTargets = table();
    primaryArrayDifference = 0;
    memberMetricDifference = 0;
    forwardCalls = 0;
    for member = 1:cfg.gate1.networkCount
        saved = load(fullfile(cfg.gate1.ensembleRoot, ...
            sprintf('network_%02d.mat', member)));
        model = saved.model;
        assert(model.n == 200 && model.nE == 160 && model.nI == 40);
        assert(model.dt == 2e-4 && model.samplingDt == 1e-3 ...
            && model.tau == 0.15 && model.nMovements == 8);
        assert(saved.networkRow.AcceptedMember == member);
        [networkRow, targetRows, rollout, hand] = ...
            evaluate_stage1_gate1_candidate(cfg, model, saved.calibration, ...
            saved.recurrent, targetBundle.target, targetBundle.targetTorques, ...
            double(saved.networkRow.Attempt), ...
            double(saved.networkRow.RecurrentSeed), ...
            double(saved.networkRow.CalibrationSeed), member);
        forwardCalls = forwardCalls + 1;
        assert(networkRow.Pass && all(targetRows.Pass));
        memberMetricDifference = max(memberMetricDifference, ...
            table_numeric_difference(networkRow, saved.networkRow));
        memberMetricDifference = max(memberMetricDifference, ...
            table_numeric_difference(targetRows, saved.targetRows));
        revalidatedAudit = [revalidatedAudit; networkRow]; %#ok<AGROW>
        revalidatedTargets = [revalidatedTargets; targetRows]; %#ok<AGROW>
        if member == 1
            for referenceIndex = 1:numel(referenceFiles)
                reference = load(fullfile(cfg.gate1.resultsRoot, ...
                    referenceFiles{referenceIndex}), 'baseline', 'hand');
                primaryArrayDifference = max(primaryArrayDifference, ...
                    max(abs(rollout.rates - reference.baseline.rates), [], 'all'));
                primaryArrayDifference = max(primaryArrayDifference, ...
                    max(abs(rollout.torque - reference.baseline.torque), [], 'all'));
                primaryArrayDifference = max(primaryArrayDifference, ...
                    max(abs(rollout.finalState - reference.baseline.finalState), [], 'all'));
                primaryArrayDifference = max(primaryArrayDifference, ...
                    max(abs(hand - reference.hand), [], 'all'));
            end
        end
    end
    networkDifference = table_numeric_difference(revalidatedAudit, originalAudit);
    targetDifference = table_numeric_difference(revalidatedTargets, originalTargets);
    maximumAuditDifference = max([networkDifference, targetDifference, ...
        memberMetricDifference]);
    % Existing accepted-ensemble deterministic tolerance; not a new QC gate.
    assert(maximumAuditDifference <= 1e-12);
    assert(primaryArrayDifference <= 1e-12);
    assert(forwardCalls == 10 && height(revalidatedTargets) == 80);
    pngFiles = dir(fullfile(cfg.plotsPngRoot, '*.png'));
    figFiles = dir(fullfile(cfg.plotsFigRoot, '*.fig'));
    pngNames = sort(erase(string({pngFiles.name}), '.png'));
    figNames = sort(erase(string({figFiles.name}), '.fig'));
    assert(numel(pngNames) == 8 && isequal(pngNames, figNames));
    report = struct('status', 'PASS', 'passed', true, ...
        'acceptedNetworks', height(revalidatedAudit), ...
        'acceptedTargetRows', height(revalidatedTargets), ...
        'batchedForwardCalls', forwardCalls, ...
        'maximumAuditDifference', maximumAuditDifference, ...
        'networkMetricMaximumDifference', networkDifference, ...
        'targetMetricMaximumDifference', targetDifference, ...
        'memberBundleMetricMaximumDifference', memberMetricDifference, ...
        'primaryArrayMaximumDifference', primaryArrayDifference, ...
        'primaryArrayChecks', 'rates, torque, final state and hand in both saved primary bundles', ...
        'otherMembersReference', 'saved network and target metrics; no full rate arrays in member bundles', ...
        'regressionTolerance', 1e-12, ...
        'maximumEndpointErrorM', max(revalidatedTargets.EndpointErrorM), ...
        'maximumAbsoluteAngularErrorDeg', max(abs(revalidatedTargets.AngularErrorDeg)), ...
        'maximumAbsoluteRadiusErrorM', max(abs(revalidatedTargets.RadiusErrorM)), ...
        'figurePairCount', numel(figNames), 'figureBasenamesMatch', true, ...
        'figureVerification', 'inventory here; external SHA-256 audit verifies preserved bytes', ...
        'pinnedManifestEntries', pinned.manifestEntries, ...
        'pinnedManifestAllMatched', pinned.allMatched, ...
        'pinnedSourceHeadMatched', pinned.sourceHeadMatched, ...
        'shortSegmentMaximumAbsoluteError', smoke.shortSegmentMaxAbs, ...
        'qRelativeResidual', smoke.qRelativeResidual, ...
        'canonicalOutputsWritten', false);
    if ~isempty(outputRoot)
        outputRoot = char(java.io.File(outputRoot).getCanonicalPath());
        allowed = {fullfile(projectRoot, 'results', 'stage_1', 'validation'), ...
            fullfile(projectRoot, 'artifacts', 'manifests', 'stage1_reset')};
        validOutput = false;
        for index = 1:numel(allowed)
            base = char(java.io.File(allowed{index}).getCanonicalPath());
            validOutput = validOutput || strcmpi(outputRoot, base) ...
                || startsWith(lower(outputRoot), lower([base, filesep]));
        end
        assert(validOutput, 'Validation output must stay in a designated audit directory.');
        outputs = {'forward_network_metrics.csv', 'forward_target_metrics.csv', ...
            'forward_regression.json'};
        for index = 1:numel(outputs)
            assert(~isfile(fullfile(outputRoot, outputs{index})), ...
                'Refusing to overwrite a prior validation output.');
        end
        if ~isfolder(outputRoot), mkdir(outputRoot); end
        writetable(revalidatedAudit, fullfile(outputRoot, outputs{1}));
        writetable(revalidatedTargets, fullfile(outputRoot, outputs{2}));
        fid = fopen(fullfile(outputRoot, outputs{3}), 'w');
        assert(fid >= 0);
        cleanup = onCleanup(@() fclose(fid));
        fprintf(fid, '%s', jsonencode(report, PrettyPrint=true));
    end
end

function maximumDifference = table_numeric_difference(actual, expected)
    assert(height(actual) == height(expected));
    assert(isequal(actual.Properties.VariableNames, expected.Properties.VariableNames));
    maximumDifference = 0;
    for index = 1:width(actual)
        name = actual.Properties.VariableNames{index};
        if isnumeric(actual.(name))
            reference = double(expected.(name));
            assert(all(isfinite(reference), 'all'));
            difference = max(abs(double(actual.(name)) - reference), [], 'all');
            maximumDifference = max(maximumDifference, difference);
        elseif islogical(actual.(name))
            assert(isequal(actual.(name), logical(expected.(name))));
        end
    end
end
