function report = revalidate_stage1_accepted_ensemble(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src', 'published_generator'));
    addpath(fullfile(projectRoot, 'analysis', 'published_generator'));
    cfg = stage_1_gate1_config(projectRoot);
    sampling = cfg.gate1.rejectionSampling;
    targetBundle = load(fullfile(cfg.gate1.targetRoot, ...
        'stage1_gate1_targets.mat'), 'target', 'targetTorques');
    originalAudit = readtable(fullfile(cfg.gate1.auditRoot, ...
        'accepted_ensemble_audit.csv'), TextType='string');
    revalidatedAudit = table();
    revalidatedTargetAudit = table();
    for member = 1:sampling.acceptedCount
        saved = load(fullfile(cfg.gate1.ensembleRoot, ...
            sprintf('network_%02d.mat', member)));
        attempt = double(saved.networkRow.Attempt);
        recurrentSeed = double(saved.networkRow.RecurrentSeed);
        calibrationSeed = double(saved.networkRow.CalibrationSeed);
        [networkRow, targetRows] = evaluate_stage1_gate1_candidate(cfg, ...
            saved.model, saved.calibration, saved.recurrent, ...
            targetBundle.target, targetBundle.targetTorques, attempt, ...
            recurrentSeed, calibrationSeed, member);
        revalidatedAudit = [revalidatedAudit; networkRow]; %#ok<AGROW>
        revalidatedTargetAudit = [revalidatedTargetAudit; targetRows]; %#ok<AGROW>
    end
    assert(all(revalidatedAudit.Pass) && all(revalidatedTargetAudit.Pass), ...
        'Independent accepted-ensemble QC failed.');
    metricNames = {'MaxAngleErrorDeg','MaxRadiusErrorM', ...
        'MaxEndpointErrorM','WeightedTorqueCost','SourceMovementCost', ...
        'SpectralAbscissaW'};
    maximumAuditDifference = 0;
    for metricIndex = 1:numel(metricNames)
        name = metricNames{metricIndex};
        difference = abs(revalidatedAudit.(name) - double(originalAudit.(name)));
        maximumAuditDifference = max(maximumAuditDifference, max(difference));
    end
    assert(maximumAuditDifference <= 1e-12, ...
        'Independent QC metrics do not reproduce the saved acceptance audit.');
    writetable(revalidatedAudit, fullfile(cfg.gate1.auditRoot, ...
        'accepted_ensemble_revalidation.csv'));
    writetable(revalidatedTargetAudit, fullfile(cfg.gate1.auditRoot, ...
        'accepted_ensemble_target_revalidation.csv'));
    pngFiles = dir(fullfile(cfg.plotsPngRoot, '*.png'));
    figFiles = dir(fullfile(cfg.plotsFigRoot, '*.fig'));
    pngNames = sort(erase(string({pngFiles.name}), '.png'));
    figNames = sort(erase(string({figFiles.name}), '.fig'));
    figureBasenamesMatch = numel(pngNames) == 8 ...
        && numel(figNames) == 8 && isequal(pngNames, figNames);
    assert(figureBasenamesMatch, ...
        'Canonical Stage-1 PNG/FIG inventory is not exactly eight matched pairs.');
    for index = 1:numel(figFiles)
        handle = openfig(fullfile(figFiles(index).folder, ...
            figFiles(index).name), 'invisible');
        assert(isgraphics(handle), 'A canonical Stage-1 FIG failed to reopen.');
        close(handle);
    end
    pinned = verify_pinned_reference(cfg);
    report = struct('passed', true, ...
        'acceptedNetworks', height(revalidatedAudit), ...
        'acceptedTargetRows', height(revalidatedTargetAudit), ...
        'maximumAuditDifference', maximumAuditDifference, ...
        'figurePairCount', numel(figFiles), ...
        'figureBasenamesMatch', figureBasenamesMatch, ...
        'allFiguresReopened', true, ...
        'pinnedManifestEntries', pinned.manifestEntries, ...
        'pinnedManifestAllMatched', pinned.allMatched);
    fid = fopen(fullfile(cfg.gate1.auditRoot, ...
        'accepted_ensemble_revalidation.json'), 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', jsonencode(report, PrettyPrint=true));
end
