function apply_plot_style(axesHandle, params)
    set(axesHandle, 'FontSize', params.plot.fontSize, ...
        'TickDir', params.plot.tickDirection, ...
        'XColor', params.plot.axisColor, ...
        'YColor', params.plot.axisColor, ...
        'LineWidth', params.plot.axisLineWidth);
    if isprop(axesHandle, 'ZColor')
        set(axesHandle, 'ZColor', params.plot.axisColor);
    end
    grid(axesHandle, 'off');
    box(axesHandle, 'off');
end
