function figureFiles = create_intact_diagnostic_plots( ...
        diagnostics, robustness, task, params)
    figureFiles = {};
    figureFiles = [figureFiles, plot_intact_reach_trajectories( ...
        diagnostics, task, params)];
    figureFiles = [figureFiles, plot_intact_speed_profiles( ...
        diagnostics, task, params)];
    figureFiles = [figureFiles, plot_intact_m1_pca( ...
        diagnostics, params)];
    figureFiles = [figureFiles, plot_intact_m1_movement_pca( ...
        diagnostics, params)];
    figureFiles = [figureFiles, plot_intact_m1_jpca( ...
        diagnostics, params)];
    figureFiles = [figureFiles, plot_intact_cerebellar_latents( ...
        diagnostics, task, params)];
    figureFiles = [figureFiles, plot_intact_performance_vs_delay( ...
        robustness, params)];
    figureFiles = [figureFiles, ...
        plot_intact_joint_kinematics_and_torques( ...
        diagnostics, params)];
end
