function figureFiles = plot_intact_joint_kinematics_and_torques( ...
        diagnostics, params)
    figureHandle = figure('Color', 'w', 'Visible', params.plot.visible, ...
        'Position', [100 100 1050 750]);
    layoutHandle = tiledlayout(figureHandle, 2, 2, ...
        'TileSpacing', 'compact', 'Padding', 'compact');
    timeMs = diagnostics.timeRelativeToGoMs;
    displayMask = timeMs >= -params.plot.preGoDisplayMs & ...
        timeMs <= params.task.movementDurationMs;
    jointNames = {'Shoulder', 'Elbow'};

    for jointIndex = 1:2
        axesHandle = nexttile(layoutHandle, jointIndex);
        hold(axesHandle, 'on');
        targetHandles = gobjects(params.task.numTargets, 1);
        for targetIndex = 1:params.task.numTargets
            targetHandles(targetIndex) = plot(axesHandle, ...
                timeMs(displayMask), rad2deg(squeeze( ...
                diagnostics.meanJointAngles(jointIndex, targetIndex, ...
                displayMask))), 'Color', ...
                params.plot.targetColors(targetIndex, :), ...
                'LineWidth', params.plot.lineWidth);
        end
        yline(axesHandle, rad2deg( ...
            params.plant.jointLowerLimitsRad(jointIndex)), 'k:', ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'HandleVisibility', 'off');
        yline(axesHandle, rad2deg( ...
            params.plant.jointUpperLimitsRad(jointIndex)), 'k:', ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'HandleVisibility', 'off');
        xline(axesHandle, 0, 'k:', 'Go', ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'HandleVisibility', 'off');
        ylabel(axesHandle, [jointNames{jointIndex}, ' angle (deg)']);
        xlim(axesHandle, [-params.plot.preGoDisplayMs, ...
            params.task.movementDurationMs]);
        apply_plot_style(axesHandle, params);
        if jointIndex == 1
            legendHandle = legend(axesHandle, targetHandles, ...
                target_legend_labels(params), 'Location', 'best');
            set(legendHandle, 'Box', 'off');
        end
    end

    for jointIndex = 1:2
        axesHandle = nexttile(layoutHandle, jointIndex + 2);
        hold(axesHandle, 'on');
        for targetIndex = 1:params.task.numTargets
            plot(axesHandle, timeMs(displayMask), squeeze( ...
                diagnostics.meanAppliedTorque(jointIndex, targetIndex, ...
                displayMask)), 'Color', ...
                params.plot.targetColors(targetIndex, :), ...
                'LineWidth', params.plot.lineWidth, ...
                'HandleVisibility', 'off');
        end
        yline(axesHandle, params.plant.torqueGuidelineNm, 'k:', ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'HandleVisibility', 'off');
        yline(axesHandle, -params.plant.torqueGuidelineNm, 'k:', ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'HandleVisibility', 'off');
        xline(axesHandle, 0, 'k:', 'Go', ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'HandleVisibility', 'off');
        xlabel(axesHandle, 'Time relative to go (ms)');
        ylabel(axesHandle, [jointNames{jointIndex}, ' torque (N m)']);
        xlim(axesHandle, [-params.plot.preGoDisplayMs, ...
            params.task.movementDurationMs]);
        apply_plot_style(axesHandle, params);
    end
    title(layoutHandle, 'Intact joint kinematics and applied torques');
    figureFiles = save_figure_bundle(figureHandle, fullfile( ...
        params.files.figureRoot, 'plant', ...
        'intact_joint_kinematics_and_torques'), params);
end
