function figureFiles = plot_intact_m1_pca(diagnostics, params)
    figureHandle = figure('Color', 'w', 'Visible', params.plot.visible);
    axesHandle = axes(figureHandle);
    hold(axesHandle, 'on');
    timeMs = diagnostics.pca.timeRelativeToGoMs;
    preparationIndex = timeMs < 0;
    movementIndex = timeMs >= 0 & ...
        timeMs <= params.task.movementDurationMs;
    targetHandles = gobjects(params.task.numTargets, 1);

    for targetIndex = 1:params.task.numTargets
        trajectory = diagnostics.pca.trajectories(:, :, targetIndex);
        color = params.plot.targetColors(targetIndex, :);
        plot3(axesHandle, trajectory(preparationIndex, 1), ...
            trajectory(preparationIndex, 2), ...
            trajectory(preparationIndex, 3), '--', 'Color', color, ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'HandleVisibility', 'off');
        targetHandles(targetIndex) = plot3(axesHandle, ...
            trajectory(movementIndex, 1), trajectory(movementIndex, 2), ...
            trajectory(movementIndex, 3), '-', 'Color', color, ...
            'LineWidth', params.plot.lineWidth);
        goIndex = find(timeMs >= 0, 1, 'first');
        plot3(axesHandle, trajectory(goIndex, 1), ...
            trajectory(goIndex, 2), trajectory(goIndex, 3), 'o', ...
            'Color', color, 'MarkerFaceColor', color, ...
            'HandleVisibility', 'off');
    end
    preparationHandle = plot3(axesHandle, nan, nan, nan, 'k--', ...
        'LineWidth', params.plot.referenceLineWidth);
    movementHandle = plot3(axesHandle, nan, nan, nan, 'k-', ...
        'LineWidth', params.plot.lineWidth);
    goHandle = plot3(axesHandle, nan, nan, nan, 'ko', ...
        'MarkerFaceColor', 'k');
    legendHandle = legend(axesHandle, ...
        [targetHandles; preparationHandle; movementHandle; goHandle], ...
        [target_legend_labels(params), ...
        {'Preparation', 'Movement', 'Go state'}], ...
        'Location', 'eastoutside');
    set(legendHandle, 'Box', 'off');
    xlabel(axesHandle, 'PC1');
    ylabel(axesHandle, 'PC2');
    zlabel(axesHandle, 'PC3');
    title(axesHandle, sprintf( ...
        'Intact M1 trajectories (PC1-PC3: %.1f%% variance)', ...
        sum(diagnostics.pca.explainedVariancePercent)));
    view(axesHandle, 35, 25);
    apply_plot_style(axesHandle, params);
    figureFiles = save_figure_bundle(figureHandle, fullfile( ...
        params.files.figureRoot, 'neural', 'intact_m1_pca'), params);
end
