function figureFiles = plot_intact_performance_vs_delay(robustness, params)
    figureHandle = figure('Color', 'w', 'Visible', params.plot.visible, ...
        'Position', [100 100 850 900]);
    layoutHandle = tiledlayout(figureHandle, 3, 1, ...
        'TileSpacing', 'compact', 'Padding', 'compact');

    axesHandle = nexttile(layoutHandle);
    hold(axesHandle, 'on');
    plot_metric(axesHandle, robustness.deterministic, ...
        100 * robustness.deterministic.meanEndpointErrorM, ...
        zeros(size(robustness.deterministic.stdEndpointErrorM)), ...
        [0.15 0.15 0.15], 'Deterministic', params);
    plot_metric(axesHandle, robustness.noisy, ...
        100 * robustness.noisy.meanEndpointErrorM, ...
        100 * robustness.noisy.stdEndpointErrorM, ...
        [0.10 0.35 0.75], 'Noisy', params);
    ylabel(axesHandle, 'Endpoint error (cm)');
    title(axesHandle, 'Intact performance across cue-to-go delays');
    style_legend(axesHandle);
    apply_plot_style(axesHandle, params);

    axesHandle = nexttile(layoutHandle);
    hold(axesHandle, 'on');
    plot_metric(axesHandle, robustness.deterministic, ...
        100 * robustness.deterministic.meanTrajectoryRmseM, ...
        zeros(size(robustness.deterministic.stdTrajectoryRmseM)), ...
        [0.15 0.15 0.15], 'Deterministic', params);
    plot_metric(axesHandle, robustness.noisy, ...
        100 * robustness.noisy.meanTrajectoryRmseM, ...
        100 * robustness.noisy.stdTrajectoryRmseM, ...
        [0.75 0.20 0.20], 'Noisy', params);
    ylabel(axesHandle, 'Trajectory RMSE (cm)');
    style_legend(axesHandle);
    apply_plot_style(axesHandle, params);

    axesHandle = nexttile(layoutHandle);
    hold(axesHandle, 'on');
    plot_metric(axesHandle, robustness.deterministic, ...
        100 * robustness.deterministic.meanTerminalSpeedMPerSec, ...
        zeros(size(robustness.deterministic.stdTerminalSpeedMPerSec)), ...
        [0.15 0.15 0.15], 'Deterministic', params);
    plot_metric(axesHandle, robustness.noisy, ...
        100 * robustness.noisy.meanTerminalSpeedMPerSec, ...
        100 * robustness.noisy.stdTerminalSpeedMPerSec, ...
        [0.20 0.60 0.25], 'Noisy', params);
    xlabel(axesHandle, 'Cue-to-go delay (ms)');
    ylabel(axesHandle, 'Terminal speed (cm/s)');
    style_legend(axesHandle);
    apply_plot_style(axesHandle, params);

    figureFiles = save_figure_bundle(figureHandle, fullfile( ...
        params.files.figureRoot, 'behavior', ...
        'intact_performance_vs_delay'), params);
end

function plot_metric(axesHandle, robustness, meanValue, stdValue, ...
        color, label, params)
    if robustness.includeNoise
        errorbar(axesHandle, robustness.delayValuesMs, meanValue, ...
            stdValue, 'o-', 'Color', color, 'MarkerFaceColor', color, ...
            'LineWidth', params.plot.lineWidth, 'DisplayName', label);
    else
        plot(axesHandle, robustness.delayValuesMs, meanValue, 's--', ...
            'Color', color, 'MarkerFaceColor', color, ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'DisplayName', label);
    end
end

function style_legend(axesHandle)
    legendHandle = legend(axesHandle, 'Location', 'best');
    set(legendHandle, 'Box', 'off');
end
