function figureFiles = plot_intact_speed_profiles(diagnostics, ~, params)
    figureHandle = figure('Color', 'w', 'Visible', params.plot.visible);
    axesHandle = axes(figureHandle);
    hold(axesHandle, 'on');
    timeMs = diagnostics.timeRelativeToGoMs;
    displayMask = timeMs >= -params.plot.preGoDisplayMs & ...
        timeMs <= params.task.movementDurationMs;

    for targetIndex = 1:params.task.numTargets
        color = params.plot.targetColors(targetIndex, :);
        desiredVelocity = squeeze( ...
            diagnostics.meanDesiredVelocity(:, targetIndex, :));
        desiredSpeed = sqrt(sum(desiredVelocity.^2, 1));
        plot(axesHandle, timeMs(displayMask), ...
            desiredSpeed(displayMask), '--', 'Color', color, ...
            'LineWidth', params.plot.referenceLineWidth, ...
            'HandleVisibility', 'off');
        plot(axesHandle, timeMs(displayMask), ...
            diagnostics.meanSpeed(targetIndex, displayMask), '-', ...
            'Color', color, 'LineWidth', params.plot.lineWidth, ...
            'HandleVisibility', 'off');
    end
    xline(axesHandle, 0, ':', 'Go', 'Color', 'k', ...
        'LineWidth', params.plot.referenceLineWidth, ...
        'HandleVisibility', 'off');
    desiredHandle = plot(axesHandle, nan, nan, 'k--', ...
        'LineWidth', params.plot.referenceLineWidth);
    generatedHandle = plot(axesHandle, nan, nan, 'k-', ...
        'LineWidth', params.plot.lineWidth);
    legendHandle = legend(axesHandle, ...
        [desiredHandle, generatedHandle], ...
        {'Desired', 'Generated mean'}, 'Location', 'best');
    set(legendHandle, 'Box', 'off');
    xlabel(axesHandle, 'Time relative to go (ms)');
    ylabel(axesHandle, 'Endpoint speed (m/s)');
    title(axesHandle, 'Intact V1 endpoint speed profiles');
    xlim(axesHandle, [-params.plot.preGoDisplayMs, ...
        params.task.movementDurationMs]);
    apply_plot_style(axesHandle, params);
    figureFiles = save_figure_bundle(figureHandle, fullfile( ...
        params.files.figureRoot, 'behavior', ...
        'intact_speed_profiles'), params);
end
