function figureFiles = plot_intact_m1_movement_pca(diagnostics, params)
    figureHandle = figure('Color', 'w', 'Visible', params.plot.visible);
    axesHandle = axes(figureHandle);
    hold(axesHandle, 'on');
    targetHandles = gobjects(params.task.numTargets, 1);
    for targetIndex = 1:params.task.numTargets
        trajectory = diagnostics.movementPca.trajectories( ...
            :, 1:3, targetIndex);
        color = params.plot.targetColors(targetIndex, :);
        targetHandles(targetIndex) = plot3(axesHandle, ...
            trajectory(:, 1), trajectory(:, 2), trajectory(:, 3), ...
            'Color', color, 'LineWidth', params.plot.lineWidth);
        plot3(axesHandle, trajectory(1, 1), trajectory(1, 2), ...
            trajectory(1, 3), 'o', 'Color', color, ...
            'MarkerFaceColor', color, 'HandleVisibility', 'off');
        plot3(axesHandle, trajectory(end, 1), trajectory(end, 2), ...
            trajectory(end, 3), 's', 'Color', color, ...
            'MarkerFaceColor', color, 'HandleVisibility', 'off');
    end
    legendHandle = legend(axesHandle, targetHandles, ...
        target_legend_labels(params), 'Location', 'eastoutside');
    set(legendHandle, 'Box', 'off');
    xlabel(axesHandle, 'Movement PC1');
    ylabel(axesHandle, 'Movement PC2');
    zlabel(axesHandle, 'Movement PC3');
    title(axesHandle, sprintf( ...
        'Movement-only M1 PCA (PC1-PC3: %.1f%% variance)', ...
        sum(diagnostics.movementPca.explainedVariancePercent(1:3))));
    view(axesHandle, 35, 25);
    apply_plot_style(axesHandle, params);
    figureFiles = save_figure_bundle(figureHandle, fullfile( ...
        params.files.figureRoot, 'neural', ...
        'intact_m1_movement_pca'), params);
end
