function figureFiles = plot_intact_m1_jpca(diagnostics, params)
    figureHandle = figure('Color', 'w', 'Visible', params.plot.visible);
    axesHandle = axes(figureHandle);
    hold(axesHandle, 'on');
    targetHandles = gobjects(params.task.numTargets, 1);
    for targetIndex = 1:params.task.numTargets
        trajectory = diagnostics.jpca.trajectories(:, :, targetIndex);
        color = params.plot.targetColors(targetIndex, :);
        targetHandles(targetIndex) = plot(axesHandle, ...
            trajectory(:, 1), trajectory(:, 2), 'Color', color, ...
            'LineWidth', params.plot.lineWidth);
        plot(axesHandle, trajectory(1, 1), trajectory(1, 2), 'o', ...
            'Color', color, 'MarkerFaceColor', color, ...
            'HandleVisibility', 'off');
        plot(axesHandle, trajectory(end, 1), trajectory(end, 2), 's', ...
            'Color', color, 'MarkerFaceColor', color, ...
            'HandleVisibility', 'off');
    end
    legendHandle = legend(axesHandle, targetHandles, ...
        target_legend_labels(params), 'Location', 'eastoutside');
    set(legendHandle, 'Box', 'off');
    xlabel(axesHandle, 'jPC1');
    ylabel(axesHandle, 'jPC2');
    title(axesHandle, sprintf( ...
        'Movement jPCA diagnostic (rotational R^2 %.3f, %.2f Hz)', ...
        diagnostics.jpca.rotationalFitR2, ...
        diagnostics.jpca.dominantFrequencyHz));
    axis(axesHandle, 'equal');
    apply_plot_style(axesHandle, params);
    figureFiles = save_figure_bundle(figureHandle, fullfile( ...
        params.files.figureRoot, 'neural', 'intact_m1_jpca'), params);
end
