function files = plot_v2_subspace_diagnostics( ...
        diagnostics, evaluation, params)
    figureHandle = figure('Color', 'w', 'Visible', params.plot.visible, ...
        'Position', [100 100 1600 900]);
    layout = tiledlayout(figureHandle, 2, 2, 'TileSpacing', 'compact');
    cross = diagnostics.crossProjection;
    ax1 = nexttile(layout);
    bar(ax1, [cross.preparatoryByPreparatoryPercent, ...
        cross.preparatoryByMovementPercent, ...
        cross.movementByPreparatoryPercent, ...
        cross.movementByMovementPercent]);
    set(ax1, 'XTick', 1:4, 'XTickLabel', ...
        {'Prep PCs/prep', 'Move PCs/prep', ...
        'Prep PCs/move', 'Move PCs/move'});
    xtickangle(ax1, 20);
    ylabel(ax1, 'Variance captured (%)');
    title(ax1, sprintf('Cross-projection, top %d PCs', ...
        diagnostics.dimension));
    apply_plot_style(ax1, params);

    ax2 = nexttile(layout);
    barh(ax2, [diagnostics.alignment.preparatoryByMovement, ...
        diagnostics.alignment.movementByPreparatory]);
    set(ax2, 'YTick', 1:2, ...
        'YTickLabel', {'Prep captured by move PCs', ...
        'Move captured by prep PCs'});
    xlabel(ax2, 'Alignment index');
    xlim(ax2, [0 1]);
    title(ax2, 'Elsayed-style alignment');
    apply_plot_style(ax2, params);

    ax3 = nexttile(layout);
    plot(ax3, 1:diagnostics.dimension, ...
        diagnostics.alignment.principalAnglesDeg, 'ko-', ...
        'LineWidth', params.plot.lineWidth);
    xlabel(ax3, 'Principal angle index'); ylabel(ax3, 'Angle (degrees)');
    title(ax3, 'Prep/movement principal angles');
    apply_plot_style(ax3, params);

    ax4 = nexttile(layout); hold(ax4, 'on');
    aligned = double(evaluation.task.timeMs - ...
        evaluation.task.goTimeMs(1));
    plot(ax4, aligned, diagnostics.outputPotent.timeCourseRmsHz, ...
        'k-', 'LineWidth', params.plot.lineWidth);
    xline(ax4, 0, 'k--', 'Go');
    xlabel(ax4, 'Time from go (ms)');
    ylabel(ax4, 'Potent projection RMS (Hz)');
    title(ax4, sprintf('Prep variance in Wout row space: %.3f%%', ...
        diagnostics.outputPotent.preparatoryVariancePercent));
    apply_plot_style(ax4, params);
    files = save_figure_bundle(figureHandle, fullfile( ...
        params.files.figureRoot, 'cortical', ...
        'prep_movement_subspace_diagnostics'), params);
end
