function handPosition = arm_forward_kinematics(jointAngles, plant)
    shoulder = jointAngles(1, :);
    elbow = jointAngles(2, :);
    combinedAngle = shoulder + elbow;

    handPosition = [ ...
        single(plant.L1) * cos(shoulder) + ...
            single(plant.L2) * cos(combinedAngle); ...
        single(plant.L1) * sin(shoulder) + ...
            single(plant.L2) * sin(combinedAngle)];
end
