function [totalLoss, components] = intact_model_loss( ...
        model, task, params, noise)
    numUnits = params.model.numCorticalUnits;
    numTrials = task.numTrials;
    numTimeSteps = task.numTimeSteps;
    integrationFraction = single(params.model.dtMs / params.model.tauMs);
    dynamicNoiseScale = single(sqrt(params.model.tauMs / ...
        params.model.dtMs));

    state = single(params.model.initialStateBaseline) + ...
        params.noise.sigmaInitial * noise.initial;
    jointAngles = task.initialJointAngles;
    jointVelocity = task.initialJointVelocity;

    zeroValue = sum(state(1) * 0);
    positionErrorSum = zeroValue;
    velocityErrorSum = zeroValue;
    terminalPositionErrorSum = zeroValue;
    terminalVelocityErrorSum = zeroValue;
    preGoSpeedSum = zeroValue;
    jointPenaltySum = zeroValue;
    torquePenaltySum = zeroValue;
    activitySum = zeroValue;

    for timeIndex = 1:numTimeSteps
        rates = tanh(state);
        rawTorque = model.Wout * rates;
        handPosition = arm_forward_kinematics(jointAngles, params.plant);
        handVelocity = arm_endpoint_velocity( ...
            jointAngles, jointVelocity, params.plant);

        movementMask = task.movementMask(:, timeIndex)';
        preGoMask = task.preGoMask(:, timeIndex)';
        terminalMask = task.terminalMask(:, timeIndex)';
        normalizedPositionError = (handPosition - ...
            task.desiredPosition(:, :, timeIndex)) / ...
            single(params.task.targetRadiusM);
        normalizedVelocityError = (handVelocity - ...
            task.desiredVelocity(:, :, timeIndex)) / ...
            task.desiredPeakSpeedMPerSec;
        normalizedSpeedSquared = sum( ...
            (handVelocity / task.desiredPeakSpeedMPerSec).^2, 1);

        positionErrorSum = positionErrorSum + sum( ...
            sum(normalizedPositionError.^2, 1) .* movementMask, 'all');
        velocityErrorSum = velocityErrorSum + sum( ...
            sum(normalizedVelocityError.^2, 1) .* movementMask, 'all');
        terminalPositionErrorSum = terminalPositionErrorSum + sum( ...
            sum(normalizedPositionError.^2, 1) .* terminalMask, 'all');
        terminalVelocityErrorSum = terminalVelocityErrorSum + sum( ...
            normalizedSpeedSquared .* terminalMask, 'all');
        preGoSpeedSum = preGoSpeedSum + sum( ...
            normalizedSpeedSquared .* preGoMask, 'all');
        jointPenaltySum = jointPenaltySum + ...
            sum(joint_limit_penalty(jointAngles, params.plant), 'all');
        torquePenaltySum = torquePenaltySum + ...
            sum(torque_penalty(rawTorque, params.plant), 'all');
        activitySum = activitySum + sum(rates.^2, 'all');

        if timeIndex < numTimeSteps
            cerebellarLatent = generate_cerebellar_latent(model, ...
                task.cerebellarGeneratorInput(:, :, timeIndex));
            dynamicNoise = params.noise.sigmaDynamic * ...
                dynamicNoiseScale * noise.dynamic(:, :, timeIndex);
            stateDerivative = -state + model.Wrec * rates + ...
                model.Wtarg * task.targetInput + ...
                model.Wgo * task.goSignal(:, timeIndex)' + ...
                model.Ucb * cerebellarLatent + dynamicNoise;
            state = state + integrationFraction * stateDerivative;
            [jointAngles, jointVelocity] = two_link_arm_step( ...
                jointAngles, jointVelocity, rawTorque, task.dtSeconds, ...
                params.plant);
        end
    end

    movementSampleCount = sum(task.movementMask, 'all');
    preGoSampleCount = sum(task.preGoMask, 'all');
    terminalSampleCount = sum(task.terminalMask, 'all');
    positionLoss = positionErrorSum / movementSampleCount;
    velocityLoss = velocityErrorSum / movementSampleCount;
    terminalPositionLoss = ...
        terminalPositionErrorSum / terminalSampleCount;
    terminalVelocityLoss = ...
        terminalVelocityErrorSum / terminalSampleCount;
    preGoLoss = preGoSpeedSum / preGoSampleCount;
    jointLoss = jointPenaltySum / single(2 * numTrials * numTimeSteps);
    torqueLoss = torquePenaltySum / single(2 * numTrials * numTimeSteps);
    activityLoss = activitySum / single(numUnits * numTrials * numTimeSteps);

    weightSum = sum(model.Wrec.^2, 'all') + ...
        sum(model.Wtarg.^2, 'all') + sum(model.Wgo.^2, 'all') + ...
        sum(model.WcbHidden.^2, 'all') + ...
        sum(model.bcbHidden.^2, 'all') + ...
        sum(model.WcbLatent.^2, 'all') + ...
        sum(model.bcbLatent.^2, 'all') + sum(model.Wout.^2, 'all');
    weightCount = single(numel(model.Wrec) + numel(model.Wtarg) + ...
        numel(model.Wgo) + numel(model.WcbHidden) + ...
        numel(model.bcbHidden) + numel(model.WcbLatent) + ...
        numel(model.bcbLatent) + numel(model.Wout));
    weightLoss = weightSum / weightCount;

    behavioralLoss = ...
        params.training.positionLossWeight * positionLoss + ...
        params.training.velocityLossWeight * velocityLoss + ...
        params.training.terminalPositionLossWeight * ...
            terminalPositionLoss + ...
        params.training.terminalVelocityLossWeight * ...
            terminalVelocityLoss + ...
        params.training.preGoLossWeight * preGoLoss + ...
        params.training.jointLimitLossWeight * jointLoss + ...
        params.training.torqueLossWeight * torqueLoss;
    totalLoss = behavioralLoss + ...
        params.training.activityRegularization * activityLoss + ...
        params.training.weightRegularization * weightLoss;

    components.behavioral = behavioralLoss;
    components.position = positionLoss;
    components.velocity = velocityLoss;
    components.terminalPosition = terminalPositionLoss;
    components.terminalVelocity = terminalVelocityLoss;
    components.preGo = preGoLoss;
    components.joint = jointLoss;
    components.torque = torqueLoss;
    components.activity = activityLoss;
    components.weight = weightLoss;
end

function penalty = joint_limit_penalty(jointAngles, plant)
    margin = single(plant.jointPenaltyMarginRad);
    softness = single(plant.jointPenaltySoftnessRad);
    lowerSoftLimit = single(plant.jointLowerLimitsRad) + margin;
    upperSoftLimit = single(plant.jointUpperLimitsRad) - margin;
    lowerApproach = smooth_positive( ...
        lowerSoftLimit - jointAngles, softness) / margin;
    upperApproach = smooth_positive( ...
        jointAngles - upperSoftLimit, softness) / margin;
    penalty = lowerApproach.^2 + upperApproach.^2;
end

function penalty = torque_penalty(rawTorque, plant)
    guideline = single(plant.torqueGuidelineNm);
    softness = single(plant.torquePenaltySoftnessNm);
    smoothMagnitude = sqrt(rawTorque.^2 + softness^2);
    excess = smooth_positive(smoothMagnitude - guideline, softness);
    penalty = (excess / guideline).^2;
end

function value = smooth_positive(inputValue, softness)
    value = 0.5 * (inputValue + sqrt(inputValue.^2 + softness^2));
end
