function [totalLoss, gradients, components] = intact_model_gradients( ...
        model, task, params, noise)
    [totalLoss, components] = intact_model_loss( ...
        model, task, params, noise);

    [gradients.Wrec, gradients.Wtarg, gradients.Wgo, ...
        gradients.WcbHidden, gradients.bcbHidden, ...
        gradients.WcbLatent, gradients.bcbLatent, gradients.Wout] = ...
        dlgradient(totalLoss, model.Wrec, model.Wtarg, model.Wgo, ...
        model.WcbHidden, model.bcbHidden, model.WcbLatent, ...
        model.bcbLatent, model.Wout);
end
