function gradientTask = prepare_gradient_task(task, params, useGpu)
    gradientTask.numTrials = task.numTrials;
    gradientTask.numTimeSteps = task.numTimeSteps;
    gradientTask.dtSeconds = device_array(task.dtSeconds, useGpu);
    gradientTask.desiredPeakSpeedMPerSec = ...
        device_array(task.desiredPeakSpeedMPerSec, useGpu);
    gradientTask.targetInput = ...
        dlarray(device_array(task.targetInput, useGpu));
    gradientTask.goSignal = ...
        dlarray(device_array(task.goSignal, useGpu));
    gradientTask.cerebellarGeneratorInput = dlarray(device_array( ...
        task.cerebellarGeneratorInput, useGpu));
    gradientTask.desiredPosition = ...
        dlarray(device_array(task.desiredPosition, useGpu));
    gradientTask.desiredVelocity = ...
        dlarray(device_array(task.desiredVelocity, useGpu));
    gradientTask.preGoMask = ...
        dlarray(device_array(task.preGoMask, useGpu));
    gradientTask.movementMask = ...
        dlarray(device_array(task.movementMask, useGpu));
    gradientTask.terminalMask = ...
        dlarray(device_array(task.terminalMask, useGpu));
    gradientTask.initialJointAngles = dlarray(device_array(repmat( ...
        single(params.plant.initialJointAnglesRad), 1, task.numTrials), ...
        useGpu));
    gradientTask.initialJointVelocity = dlarray(device_array(repmat( ...
        single(params.plant.initialJointVelocityRadPerSec), ...
        1, task.numTrials), useGpu));
end

function value = device_array(value, useGpu)
    value = single(value);
    if useGpu
        value = gpuArray(value);
    end
end
