function [totalLoss, components] = v2_model_loss(model, task, params, noise)
    n = params.model.numCorticalUnits;
    state = model.baselineRates;
    if noise.enabled
        state = state + params.noise.sigmaInitialHz * noise.initial;
    end
    position = state(1:2, :) * 0;
    integrationFraction = single(params.model.dtMs / params.model.tauMs);
    dynamicScale = single(sqrt(params.model.tauMs / params.model.dtMs));
    cTarget = model.WcbLatent * tanh(model.WcbHidden * ...
        task.targetInput + model.bcbHidden) + model.bcbLatent;
    zero = sum(state(1) * 0);
    names = {'preGoPosition', 'preGoVelocity', 'latePreGoVelocity', ...
        'endpointUrgency', ...
        'terminalPosition', 'terminalVelocity', 'holdPosition', ...
        'holdVelocity', 'velocityEffort', 'activity'};
    for nameIndex = 1:numel(names)
        sums.(names{nameIndex}) = zero;
    end
    velocityScale = single(params.training.velocityScaleMPerSec);
    radius = single(params.task.targetRadiusM);

    for timeIndex = 1:task.numTimeSteps
        rates = max(state, 0);
        velocity = model.Wout * rates;
        centerError = position / radius;
        targetError = (position - task.trialTargetPositions) / radius;
        speedSquared = sum((velocity / velocityScale).^2, 1);
        pre = task.preGoMask(:, timeIndex)';
        latePre = task.latePreGoMask(:, timeIndex)';
        urgency = task.endpointUrgency(:, timeIndex)';
        terminal = task.terminalMask(:, timeIndex)';
        hold = task.holdMask(:, timeIndex)';
        sums.preGoPosition = sums.preGoPosition + ...
            sum(sum(centerError.^2, 1) .* pre, 'all');
        sums.preGoVelocity = sums.preGoVelocity + ...
            sum(speedSquared .* pre, 'all');
        sums.latePreGoVelocity = sums.latePreGoVelocity + ...
            sum(speedSquared .* latePre, 'all');
        sums.endpointUrgency = sums.endpointUrgency + ...
            sum(sum(targetError.^2, 1) .* urgency, 'all');
        sums.terminalPosition = sums.terminalPosition + ...
            sum(sum(targetError.^2, 1) .* terminal, 'all');
        sums.terminalVelocity = sums.terminalVelocity + ...
            sum(speedSquared .* terminal, 'all');
        sums.holdPosition = sums.holdPosition + ...
            sum(sum(targetError.^2, 1) .* hold, 'all');
        sums.holdVelocity = sums.holdVelocity + ...
            sum(speedSquared .* hold, 'all');
        sums.velocityEffort = sums.velocityEffort + ...
            sum((velocity / velocityScale).^2, 'all');
        sums.activity = sums.activity + sum((rates / 30).^2, 'all');

        if timeIndex < task.numTimeSteps
            latent = cTarget .* task.relaxationScale(timeIndex);
            if noise.enabled
                dynamicNoise = params.noise.sigmaDynamicHz * ...
                    dynamicScale * noise.dynamic(:, :, timeIndex);
            else
                dynamicNoise = state * 0;
            end
            state = state + integrationFraction * (-state + ...
                model.Wrec * rates + model.baselineDrive + ...
                model.Wtarg * task.targetInput + ...
                model.Wgo * task.goSignal(:, timeIndex)' + ...
                model.Ucb * latent + dynamicNoise);
            position = position + task.dtSeconds * velocity;
        end
    end

    components.preGoPosition = sums.preGoPosition / ...
        max(sum(task.preGoMask, 'all'), 1);
    components.preGoVelocity = sums.preGoVelocity / ...
        max(sum(task.preGoMask, 'all'), 1);
    components.latePreGoVelocity = sums.latePreGoVelocity / ...
        max(sum(task.latePreGoMask, 'all'), 1);
    components.endpointUrgency = sums.endpointUrgency / ...
        max(sum(task.endpointUrgency, 'all'), 1);
    components.terminalPosition = sums.terminalPosition / ...
        max(sum(task.terminalMask, 'all'), 1);
    components.terminalVelocity = sums.terminalVelocity / ...
        max(sum(task.terminalMask, 'all'), 1);
    components.holdPosition = sums.holdPosition / ...
        max(sum(task.holdMask, 'all'), 1);
    components.holdVelocity = sums.holdVelocity / ...
        max(sum(task.holdMask, 'all'), 1);
    denominator = single(task.numTrials * task.numTimeSteps);
    components.velocityEffort = sums.velocityEffort / denominator;
    components.activity = sums.activity / single(n) / denominator;
    weightSum = zero;
    weightCount = 0;
    trainable = v2_trainable_fields();
    for fieldIndex = 1:numel(trainable)
        value = model.(trainable{fieldIndex});
        weightSum = weightSum + sum(value.^2, 'all');
        weightCount = weightCount + numel(value);
    end
    components.weight = weightSum / single(weightCount);
    w = params.training;
    totalLoss = w.preGoPositionLossWeight * components.preGoPosition + ...
        w.preGoVelocityLossWeight * components.preGoVelocity + ...
        w.latePreGoVelocityLossWeight * components.latePreGoVelocity + ...
        w.endpointUrgencyLossWeight * components.endpointUrgency + ...
        w.terminalPositionLossWeight * components.terminalPosition + ...
        w.terminalVelocityLossWeight * components.terminalVelocity + ...
        w.holdPositionLossWeight * components.holdPosition + ...
        w.holdVelocityLossWeight * components.holdVelocity + ...
        w.velocityEffortLossWeight * components.velocityEffort + ...
        w.activityRegularization * components.activity + ...
        w.weightRegularization * components.weight;
end
