function [loss, gradients, components] = ...
        v3_model_gradients(model, task, params, noise)
    [loss, components] = v3_model_loss(model, task, params, noise);
    [gradients.Wtarg, gradients.Wgo, gradients.WcbHidden, ...
        gradients.bcbHidden, gradients.WcbLatent, ...
        gradients.bcbLatent, gradients.Ucb, gradients.Wout] = ...
        dlgradient(loss, model.Wtarg, model.Wgo, model.WcbHidden, ...
        model.bcbHidden, model.WcbLatent, model.bcbLatent, ...
        model.Ucb, model.Wout);
end
