function summary = build_intact_numerical_summary(trainingHistory, ...
        deterministicDiagnostics, noisyDiagnostics, delayRobustness, ...
        validation, params)
    deterministic = deterministicDiagnostics.metrics;
    noisy = noisyDiagnostics.metrics;
    summary.projectVersion = params.project.version;
    summary.seeds = params.seed;
    summary.training.updatesCompleted = trainingHistory.updatesCompleted;
    summary.training.stageAUpdatesCompleted = ...
        trainingHistory.stageAUpdatesCompleted;
    summary.training.stageBUpdatesCompleted = ...
        trainingHistory.stageBUpdatesCompleted;
    summary.training.stoppedEarly = trainingHistory.stoppedEarly;
    summary.training.batchSize = trainingHistory.batchSize;
    summary.training.trialsPerTargetPerBatch = ...
        trainingHistory.trialsPerTarget;
    summary.training.stageABaseLearnRate = ...
        params.training.stageABaseLearnRate;
    summary.training.stageBBaseLearnRate = ...
        params.training.stageBBaseLearnRate;
    summary.training.learningRateMultipliers = ...
        trainingHistory.learningRateMultipliers;
    summary.training.trainableParameterFields = ...
        trainingHistory.trainableParameterFields;
    summary.training.frozenParameterFields = ...
        trainingHistory.frozenParameterFields;
    summary.training.bestValidationIteration = ...
        trainingHistory.bestValidationIteration;
    summary.training.bestValidationBehavioralLoss = ...
        trainingHistory.bestValidationBehavioralLoss;
    summary.training.bestValidationTotalLoss = ...
        trainingHistory.bestValidationTotalLoss;
    summary.training.bestValidationComponents = ...
        trainingHistory.bestValidationComponents;
    summary.training.finalTrainingComponents = ...
        trainingHistory.finalTrainingComponents;
    summary.training.elapsedSeconds = trainingHistory.elapsedSeconds;
    summary.training.executionEnvironment = ...
        trainingHistory.executionEnvironment;
    summary.behavior.deterministic = deterministic;
    summary.behavior.noisy = noisy;
    summary.behavior.delayRobustness = delayRobustness;
    summary.plant.deterministic.minimumJointAngleDeg = ...
        deterministic.minimumJointAngleDeg;
    summary.plant.deterministic.maximumJointAngleDeg = ...
        deterministic.maximumJointAngleDeg;
    summary.plant.deterministic.minimumAppliedTorqueNm = ...
        deterministic.minimumAppliedTorqueNm;
    summary.plant.deterministic.maximumAppliedTorqueNm = ...
        deterministic.maximumAppliedTorqueNm;
    summary.plant.deterministic.maximumAbsoluteTorqueNm = ...
        deterministic.maximumAbsoluteTorqueNm;
    summary.plant.deterministic.hardJointLimitContactFraction = ...
        deterministic.hardJointLimitContactFraction;
    summary.plant.deterministic.hardTorqueSaturationFraction = ...
        deterministic.hardTorqueSaturationFraction;
    summary.plant.noisy.minimumJointAngleDeg = noisy.minimumJointAngleDeg;
    summary.plant.noisy.maximumJointAngleDeg = noisy.maximumJointAngleDeg;
    summary.plant.noisy.minimumAppliedTorqueNm = ...
        noisy.minimumAppliedTorqueNm;
    summary.plant.noisy.maximumAppliedTorqueNm = ...
        noisy.maximumAppliedTorqueNm;
    summary.plant.noisy.maximumAbsoluteTorqueNm = ...
        noisy.maximumAbsoluteTorqueNm;
    summary.plant.noisy.hardJointLimitContactFraction = ...
        noisy.hardJointLimitContactFraction;
    summary.plant.noisy.hardTorqueSaturationFraction = ...
        noisy.hardTorqueSaturationFraction;
    summary.plasticity.normalizedWrecChange = ...
        trainingHistory.normalizedWrecChange;
    summary.plasticity.absoluteUcbChange = ...
        trainingHistory.absoluteUcbChange;
    summary.plasticity.ucbFixedWithinMachinePrecision = ...
        trainingHistory.ucbFixedWithinMachinePrecision;
    summary.neural.wholeTrialPcaExplainedVariancePercent = ...
        noisy.pcaExplainedVariancePercent;
    summary.neural.movementPcaExplainedVariancePercent = ...
        noisy.movementPcaExplainedVariancePercent;
    summary.neural.jpcaRotationalFitR2 = noisy.jpcaRotationalFitR2;
    summary.neural.jpcaUnconstrainedFitR2 = ...
        noisy.jpcaUnconstrainedFitR2;
    summary.neural.jpcaDominantFrequencyHz = ...
        noisy.jpcaDominantFrequencyHz;
    summary.neural.jpcaSkewFraction = noisy.jpcaSkewFraction;
    summary.cerebellar.meanDrivePreparation = ...
        noisy.meanCerebellarDrivePreparation;
    summary.cerebellar.meanDriveMovement = ...
        noisy.meanCerebellarDriveMovement;
    summary.cerebellar.latePreparationWindowMs = ...
        noisy.latePreparationWindowMs;
    summary.cerebellar.latePreparationLatentDerivativeNormByTargetPerSec = ...
        noisy.latePreparationLatentDerivativeNormByTargetPerSec;
    summary.cerebellar.latePreparationLatentChangeByTarget = ...
        noisy.latePreparationLatentChangeByTarget;
    summary.cerebellar.meanLatePreparationLatentDerivativeNormPerSec = ...
        noisy.meanLatePreparationLatentDerivativeNormPerSec;
    summary.cerebellar.meanLatePreparationLatentChange = ...
        noisy.meanLatePreparationLatentChange;
    summary.validation = validation;
end
