function evaluation = evaluate_v3_delay_range(model, params, run)
    delays = params.task.delayGridMs;
    nDelays = numel(delays);
    summary = zeros(nDelays, 8);
    rows = cell(nDelays, 1);
    for delayIndex = 1:nDelays
        delay = delays(delayIndex);
        task = build_v3_task(params, 1, delay, []);
        simulation = simulate_v3_model(model, task, params, ...
            run.seed.delayEvaluation + delayIndex - 1, false);
        metrics = compute_v3_behavioral_metrics( ...
            simulation, task, params);
        summary(delayIndex, :) = [metrics.meanEndpointErrorM, ...
            metrics.worstTargetEndpointErrorM, ...
            metrics.meanTerminalSpeedMPerSec, ...
            metrics.preGoRmsSpeedMPerSec, ...
            metrics.latePreGoRmsSpeedMPerSec, ...
            metrics.maximumPreGoSpeedMPerSec, ...
            metrics.meanHoldErrorM, metrics.meanHoldSpeedMPerSec];
        rows{delayIndex} = delay_target_table( ...
            metrics, params, delay);
    end
    evaluation.delaysMs = delays;
    evaluation.summary = array2table(summary, 'VariableNames', ...
        {'MeanEndpointErrorM', 'WorstTargetEndpointErrorM', ...
        'MeanTerminalSpeedMPerSec', 'PreGoRmsSpeedMPerSec', ...
        'LatePreGoRmsSpeedMPerSec', 'MaximumPreGoSpeedMPerSec', ...
        'MeanHoldErrorM', 'MeanHoldSpeedMPerSec'});
    evaluation.summary.DelayMs = delays';
    evaluation.summary = movevars(evaluation.summary, 'DelayMs', ...
        'Before', 1);
    evaluation.byTarget = vertcat(rows{:});
end

function output = delay_target_table(metrics, params, delay)
    output = table(repmat(delay, params.task.numTargets, 1), ...
        (1:params.task.numTargets)', params.task.targetAnglesDeg', ...
        1000 * metrics.perTrial.endpointErrorM, ...
        metrics.perTrial.terminalSpeedMPerSec, ...
        metrics.perTrial.preGoRmsSpeedMPerSec, ...
        metrics.perTrial.latePreGoRmsSpeedMPerSec, ...
        metrics.perTrial.maximumPreGoSpeedMPerSec, ...
        1000 * metrics.perTrial.holdErrorM, ...
        metrics.perTrial.holdSpeedMPerSec, ...
        'VariableNames', {'DelayMs', 'TargetIndex', 'TargetAngleDeg', ...
        'EndpointErrorMm', 'TerminalSpeedMPerSec', ...
        'PreGoRmsSpeedMPerSec', 'LatePreGoRmsSpeedMPerSec', ...
        'MaximumPreGoSpeedMPerSec', 'HoldErrorMm', ...
        'HoldSpeedMPerSec'});
end
