function evaluation = evaluate_v3_canonical(model, params, run)
    task = build_v3_task(params, 1, ...
        params.task.canonicalGoTimeMs, []);
    simulation = simulate_v3_model(model, task, params, ...
        run.seed.canonicalEvaluation, false);
    metrics = compute_v3_behavioral_metrics(simulation, task, params);
    evaluation.task = task;
    evaluation.simulation = simulation;
    evaluation.metrics = metrics;
    evaluation.byTarget = target_table(metrics, task, params);
end

function output = target_table(metrics, task, params)
    output = table((1:params.task.numTargets)', ...
        params.task.targetAnglesDeg', double(task.goTimeMs(:)), ...
        1000 * metrics.perTrial.endpointErrorM, ...
        metrics.perTrial.terminalSpeedMPerSec, ...
        metrics.perTrial.preGoRmsSpeedMPerSec, ...
        metrics.perTrial.latePreGoRmsSpeedMPerSec, ...
        metrics.perTrial.maximumPreGoSpeedMPerSec, ...
        1000 * metrics.perTrial.holdErrorM, ...
        metrics.perTrial.holdSpeedMPerSec, ...
        'VariableNames', {'TargetIndex', 'TargetAngleDeg', 'DelayMs', ...
        'EndpointErrorMm', 'TerminalSpeedMPerSec', ...
        'PreGoRmsSpeedMPerSec', 'LatePreGoRmsSpeedMPerSec', ...
        'MaximumPreGoSpeedMPerSec', 'HoldErrorMm', ...
        'HoldSpeedMPerSec'});
end
