function print_intact_summary(summary)
    deterministic = summary.behavior.deterministic;
    noisy = summary.behavior.noisy;
    fprintf('\nRetrained intact V1 numerical summary\n');
    fprintf(['Updates: %d total (%d deterministic + %d noisy), ', ...
        'best validation iteration %d\n'], ...
        summary.training.updatesCompleted, ...
        summary.training.stageAUpdatesCompleted, ...
        summary.training.stageBUpdatesCompleted, ...
        summary.training.bestValidationIteration);
    fprintf('Batch: %d trials (%d per target)\n', ...
        summary.training.batchSize, ...
        summary.training.trialsPerTargetPerBatch);
    fprintf('Best validation behavioral loss: %.8f\n', ...
        summary.training.bestValidationBehavioralLoss);
    print_behavior('Deterministic', deterministic);
    print_behavior('Noisy', noisy);
    fprintf('Normalized W_rec change: %.9f\n', ...
        summary.plasticity.normalizedWrecChange);
    fprintf('Absolute U_cb change: %.12g\n', ...
        summary.plasticity.absoluteUcbChange);
    fprintf('Shoulder angle min/max (noisy): %.3f / %.3f deg\n', ...
        noisy.minimumJointAngleDeg(1), noisy.maximumJointAngleDeg(1));
    fprintf('Elbow angle min/max (noisy): %.3f / %.3f deg\n', ...
        noisy.minimumJointAngleDeg(2), noisy.maximumJointAngleDeg(2));
    fprintf('Maximum |shoulder/elbow torque| (noisy): %.6f / %.6f N m\n', ...
        noisy.maximumAbsoluteTorqueNm(1), noisy.maximumAbsoluteTorqueNm(2));
    fprintf('Joint/torque contact fractions (noisy): %.8f / %.8f\n', ...
        noisy.hardJointLimitContactFraction, ...
        noisy.hardTorqueSaturationFraction);
    fprintf('Whole-trial PC1-PC3 variance: %.3f%%, %.3f%%, %.3f%%\n', ...
        summary.neural.wholeTrialPcaExplainedVariancePercent);
    fprintf('Movement PC1-PC3 variance: %.3f%%, %.3f%%, %.3f%%\n', ...
        summary.neural.movementPcaExplainedVariancePercent);
    fprintf(['jPCA rotational/unconstrained R^2: %.4f / %.4f; ', ...
        'dominant frequency %.3f Hz\n'], ...
        summary.neural.jpcaRotationalFitR2, ...
        summary.neural.jpcaUnconstrainedFitR2, ...
        summary.neural.jpcaDominantFrequencyHz);
    fprintf('Mean cerebellar drive, preparation/movement: %.6f / %.6f\n', ...
        summary.cerebellar.meanDrivePreparation, ...
        summary.cerebellar.meanDriveMovement);
    fprintf(['Late-preparation latent derivative norm/change: ', ...
        '%.6f per s / %.6f\n\n'], ...
        summary.cerebellar.meanLatePreparationLatentDerivativeNormPerSec, ...
        summary.cerebellar.meanLatePreparationLatentChange);
end

function print_behavior(label, metrics)
    fprintf('%s trajectory/velocity RMSE: %.6f m / %.6f m/s\n', ...
        label, metrics.endpointRmseM, metrics.velocityRmseMPerSec);
    fprintf(['%s mean/median/max-target endpoint error: ', ...
        '%.6f / %.6f / %.6f m\n'], label, ...
        metrics.meanEndpointErrorM, metrics.medianEndpointErrorM, ...
        metrics.maximumTargetAveragedEndpointErrorM);
    fprintf('%s terminal/pre-go RMS speed: %.6f / %.6f m/s\n', ...
        label, metrics.meanTerminalSpeedMPerSec, ...
        metrics.preGoRmsEndpointSpeedMPerSec);
end
