function validation = validate_intact_diagnostics( ...
        deterministicDiagnostics, noisyDiagnostics, params)
    deterministic = deterministicDiagnostics.metrics;
    noisy = noisyDiagnostics.metrics;
    validation.meanEndpointAccuracyPassed = ...
        noisy.meanEndpointErrorM <= ...
        params.validation.maxMeanEndpointErrorM;
    validation.maximumEndpointAccuracyPassed = ...
        noisy.maximumTargetAveragedEndpointErrorM <= ...
        params.validation.maxTargetAveragedEndpointErrorM;
    validation.terminalSpeedPassed = ...
        noisy.meanTerminalSpeedMPerSec <= ...
        params.validation.maxTerminalSpeedMPerSec;
    validation.deterministicPreGoMovementPassed = ...
        deterministic.preGoRmsEndpointSpeedMPerSec <= ...
        params.validation.maxDeterministicPreGoRmsSpeedMPerSec;
    validation.noisyPreGoMovementPassed = ...
        noisy.preGoRmsEndpointSpeedMPerSec <= ...
        params.validation.maxNoisyPreGoRmsSpeedMPerSec;
    validation.jointSafetyPassed = ...
        noisy.hardJointLimitContactFraction <= ...
        params.validation.maxJointContactFraction;
    validation.torqueSafetyPassed = ...
        noisy.hardTorqueSaturationFraction <= ...
        params.validation.maxTorqueSaturationFraction;
    validation.allPassed = validation.meanEndpointAccuracyPassed && ...
        validation.maximumEndpointAccuracyPassed && ...
        validation.terminalSpeedPassed && ...
        validation.deterministicPreGoMovementPassed && ...
        validation.noisyPreGoMovementPassed && ...
        validation.jointSafetyPassed && ...
        validation.torqueSafetyPassed;
    validation.thresholds = params.validation;
end
