function validation = validate_isn_diagnostics(deterministic, noisy, params)
    d = deterministic.metrics;
    n = noisy.metrics;
    validation.meanEndpointAccuracyPassed = d.meanEndpointErrorM <= ...
        params.validation.maxMeanEndpointErrorM;
    validation.maximumEndpointAccuracyPassed = ...
        d.maximumTargetAveragedEndpointErrorM <= ...
        params.validation.maxTargetAveragedEndpointErrorM;
    validation.terminalSpeedPassed = d.meanTerminalSpeedMPerSec <= ...
        params.validation.maxTerminalSpeedMPerSec;
    validation.deterministicPreGoPassed = ...
        d.preGoRmsEndpointSpeedMPerSec <= ...
        params.validation.maxDeterministicPreGoRmsSpeedMPerSec;
    validation.noisyPreGoPassed = n.preGoRmsEndpointSpeedMPerSec <= ...
        params.validation.maxNoisyPreGoRmsSpeedMPerSec;
    validation.jointSafetyPassed = n.hardJointLimitContactFraction <= ...
        params.validation.maxJointContactFraction;
    validation.torqueSafetyPassed = n.hardTorqueSaturationFraction <= ...
        params.validation.maxTorqueSaturationFraction;
    flags = struct2cell(validation);
    validation.allPassed = all(cellfun(@(value) islogical(value) && value, flags));
    validation.thresholds = params.validation;
end
