function validation = validate_v3_deterministic( ...
        canonicalMetrics, delayEvaluation, run)
    thresholds = run.acceptance;
    validation.canonical.meanEndpointError = ...
        canonicalMetrics.meanEndpointErrorM <= ...
        thresholds.maxMeanEndpointErrorM;
    validation.canonical.worstTargetEndpointError = ...
        canonicalMetrics.worstTargetEndpointErrorM <= ...
        thresholds.maxWorstTargetEndpointErrorM;
    validation.canonical.terminalSpeed = ...
        canonicalMetrics.meanTerminalSpeedMPerSec <= ...
        thresholds.maxTerminalSpeedMPerSec;
    validation.canonical.preGoStationarity = ...
        canonicalMetrics.preGoRmsSpeedMPerSec <= ...
        thresholds.maxPreGoRmsSpeedMPerSec;
    validation.canonical.holdError = ...
        canonicalMetrics.meanHoldErrorM <= ...
        thresholds.maxMeanHoldErrorM;
    validation.canonical.holdSpeed = ...
        canonicalMetrics.meanHoldSpeedMPerSec <= ...
        thresholds.maxMeanHoldSpeedMPerSec;
    validation.canonical.allFinite = canonicalMetrics.allFinite;
    summary = delayEvaluation.summary;
    validation.delayRange.meanEndpointError = ...
        all(summary.MeanEndpointErrorM <= ...
        thresholds.maxMeanEndpointErrorM);
    validation.delayRange.worstTargetEndpointError = ...
        all(summary.WorstTargetEndpointErrorM <= ...
        thresholds.maxWorstTargetEndpointErrorM);
    validation.delayRange.terminalSpeed = ...
        all(summary.MeanTerminalSpeedMPerSec <= ...
        thresholds.maxTerminalSpeedMPerSec);
    validation.delayRange.preGoStationarity = ...
        all(summary.PreGoRmsSpeedMPerSec <= ...
        thresholds.maxPreGoRmsSpeedMPerSec);
    validation.delayRange.holdError = ...
        all(summary.MeanHoldErrorM <= ...
        thresholds.maxMeanHoldErrorM);
    validation.delayRange.holdSpeed = ...
        all(summary.MeanHoldSpeedMPerSec <= ...
        thresholds.maxMeanHoldSpeedMPerSec);
    validation.allCanonical = all( ...
        cell2mat(struct2cell(validation.canonical)));
    validation.allDelayRange = all( ...
        cell2mat(struct2cell(validation.delayRange)));
    validation.passed = validation.allCanonical && ...
        validation.allDelayRange;
end
