function validation = validate_v2_intact( ...
        deterministic, noisy, deterministicDelay, noisyDelay, params)
    validation.deterministic = condition_checks( ...
        deterministic.metrics, params, false);
    validation.noisy = condition_checks(noisy.metrics, params, true);
    validation.deterministicDelay = delay_checks( ...
        deterministicDelay, params, false);
    validation.noisyDelay = delay_checks(noisyDelay, params, true);
    validation.allPassed = validation.deterministic.allPassed && ...
        validation.noisy.allPassed && ...
        validation.deterministicDelay.allPassed && ...
        validation.noisyDelay.allPassed;
end

function checks = condition_checks(metrics, params, noisy)
    checks.meanEndpointPassed = metrics.meanEndpointErrorM <= ...
        params.validation.maxMeanEndpointErrorM;
    checks.worstTargetPassed = ...
        metrics.maximumTargetAveragedEndpointErrorM <= ...
        params.validation.maxTargetAveragedEndpointErrorM;
    checks.terminalSpeedPassed = metrics.meanTerminalSpeedMPerSec <= ...
        params.validation.maxTerminalSpeedMPerSec;
    if noisy
        preGoLimit = params.validation.maxNoisyPreGoRmsSpeedMPerSec;
    else
        preGoLimit = ...
            params.validation.maxDeterministicPreGoRmsSpeedMPerSec;
    end
    checks.preGoSpeedPassed = metrics.preGoRmsSpeedMPerSec <= preGoLimit;
    checks.holdErrorPassed = metrics.meanHoldErrorM <= ...
        params.validation.maxMeanHoldErrorM;
    checks.holdSpeedPassed = metrics.meanHoldSpeedMPerSec <= ...
        params.validation.maxMeanHoldSpeedMPerSec;
    checks.allTargetsPassed = metrics.allTargetsSuccessful;
    checks.finitePassed = metrics.finite;
    checks.allPassed = all(structfun(@(value) ...
        islogical(value) && value, checks));
end

function checks = delay_checks(robustness, params, noisy)
    checks.meanEndpointPassed = all(robustness.meanEndpointErrorM <= ...
        params.validation.maxMeanEndpointErrorM);
    checks.worstTargetPassed = all( ...
        robustness.maximumTargetAveragedEndpointErrorM <= ...
        params.validation.maxTargetAveragedEndpointErrorM);
    checks.terminalSpeedPassed = all( ...
        robustness.meanTerminalSpeedMPerSec <= ...
        params.validation.maxTerminalSpeedMPerSec);
    if noisy
        preGoLimit = params.validation.maxNoisyPreGoRmsSpeedMPerSec;
    else
        preGoLimit = ...
            params.validation.maxDeterministicPreGoRmsSpeedMPerSec;
    end
    checks.preGoSpeedPassed = all( ...
        robustness.preGoRmsSpeedMPerSec <= preGoLimit);
    checks.holdErrorPassed = all(robustness.meanHoldErrorM <= ...
        params.validation.maxMeanHoldErrorM);
    checks.holdSpeedPassed = all(robustness.meanHoldSpeedMPerSec <= ...
        params.validation.maxMeanHoldSpeedMPerSec);
    checks.allPassed = all(structfun(@(value) ...
        islogical(value) && value, checks));
end
