function validation = validate_v2_stage_a(diagnostics, delay, params)
    validation.canonical = canonical_checks(diagnostics.metrics, params);
    validation.delay = delay_checks(delay, params);
    validation.allPassed = validation.canonical.allPassed && ...
        validation.delay.allPassed;
end

function checks = canonical_checks(metrics, params)
    checks.meanEndpointPassed = metrics.meanEndpointErrorM <= ...
        params.validation.maxMeanEndpointErrorM;
    checks.worstTargetPassed = ...
        metrics.maximumTargetAveragedEndpointErrorM <= ...
        params.validation.maxTargetAveragedEndpointErrorM;
    checks.terminalSpeedPassed = metrics.meanTerminalSpeedMPerSec <= ...
        params.validation.maxTerminalSpeedMPerSec;
    checks.preGoSpeedPassed = metrics.preGoRmsSpeedMPerSec <= ...
        params.validation.maxDeterministicPreGoRmsSpeedMPerSec;
    checks.holdErrorPassed = metrics.meanHoldErrorM <= ...
        params.validation.maxMeanHoldErrorM;
    checks.holdSpeedPassed = metrics.meanHoldSpeedMPerSec <= ...
        params.validation.maxMeanHoldSpeedMPerSec;
    checks.allTargetsPassed = metrics.allTargetsSuccessful;
    checks.finitePassed = metrics.finite;
    checks.allPassed = all(structfun(@(value) ...
        islogical(value) && value, checks));
end

function checks = delay_checks(delay, params)
    checks.meanEndpointPassed = all(delay.meanEndpointErrorM <= ...
        params.validation.maxMeanEndpointErrorM);
    checks.worstTargetPassed = all( ...
        delay.maximumTargetAveragedEndpointErrorM <= ...
        params.validation.maxTargetAveragedEndpointErrorM);
    checks.terminalSpeedPassed = all(delay.meanTerminalSpeedMPerSec <= ...
        params.validation.maxTerminalSpeedMPerSec);
    checks.preGoSpeedPassed = all(delay.preGoRmsSpeedMPerSec <= ...
        params.validation.maxDeterministicPreGoRmsSpeedMPerSec);
    checks.holdErrorPassed = all(delay.meanHoldErrorM <= ...
        params.validation.maxMeanHoldErrorM);
    checks.holdSpeedPassed = all(delay.meanHoldSpeedMPerSec <= ...
        params.validation.maxMeanHoldSpeedMPerSec);
    checks.allPassed = all(structfun(@(value) ...
        islogical(value) && value, checks));
end
