function report = verify_v2_execution_equivalence(projectRoot)
    if nargin < 1 || isempty(projectRoot)
        projectRoot = fileparts(fileparts(mfilename('fullpath')));
    end
    addpath(fullfile(projectRoot, 'config'));
    addpath(fullfile(projectRoot, 'src'));
    params = v2_model_params();
    params.files.isnMatrix = fullfile(projectRoot, params.files.isnMatrix);
    select_required_gpu(params.model.requiredGpuName);
    fixed = load_hennequin_isn(params, '');
    cpuModel = initialize_v2_model(params, fixed);
    gpuModel = move_v2_model(cpuModel, true);
    taskStream = RandStream('mt19937ar', 'Seed', ...
        params.seed.trainingTask + 2900);
    noiseStream = RandStream('mt19937ar', 'Seed', ...
        params.seed.trainingNoise + 2900);
    task = sample_balanced_v2_task(params, ...
        params.training.trialsPerTarget, taskStream);
    deviceTask = prepare_v2_gradient_task(task, true);
    noise = sample_v2_noise(task, params, true, noiseStream, true);

    [legacyLoss, legacyGradients, legacyComponents] = dlfeval( ...
        @v2_model_gradients, gpuModel, deviceTask, params, noise);
    [packedCore, parameterVector, layout, staticModel] = ...
        create_v2_gradient_engine(gpuModel, params, false);
    [packedLoss, packedGradient, packedComponents] = dlfeval( ...
        packedCore, parameterVector, deviceTask, noise);
    legacyGradient = pack_v2_trainables(legacyGradients);
    reconstructedModel = unpack_v2_trainables(staticModel, ...
        parameterVector, layout);

    legacySimulation = simulate_v2_model(extract_v2_model(gpuModel), ...
        task, params, params.seed.noisyEvaluation + 2900, true);
    packedSimulation = simulate_v2_model( ...
        extract_v2_model(reconstructedModel), task, params, ...
        params.seed.noisyEvaluation + 2900, true);

    report.tolerances.absolute = 1e-6;
    report.tolerances.relative = 1e-6;
    report.lossAbsoluteDifference = scalar_difference(legacyLoss, packedLoss);
    componentNames = fieldnames(legacyComponents);
    report.componentNames = componentNames;
    report.componentAbsoluteDifferences = zeros(numel(componentNames), 1);
    for componentIndex = 1:numel(componentNames)
        name = componentNames{componentIndex};
        report.componentAbsoluteDifferences(componentIndex) = ...
            scalar_difference(legacyComponents.(name), ...
            packedComponents.(name));
    end
    report.maximumComponentAbsoluteDifference = ...
        max(report.componentAbsoluteDifferences);
    report.gradientMaximumAbsoluteDifference = maximum_difference( ...
        legacyGradient, packedGradient);
    report.gradientFieldNames = layout.names;
    report.gradientFieldMaximumAbsoluteDifferences = zeros( ...
        numel(layout.names), 1);
    for fieldIndex = 1:numel(layout.names)
        indices = layout.indices{fieldIndex};
        report.gradientFieldMaximumAbsoluteDifferences(fieldIndex) = ...
            maximum_difference(legacyGradient(indices), ...
            packedGradient(indices));
    end
    report.gradientRelativeDifference = relative_difference( ...
        legacyGradient, packedGradient);
    legacyNorm = vector_norm(legacyGradient);
    packedNorm = vector_norm(packedGradient);
    report.legacyGradientNorm = legacyNorm;
    report.packedGradientNorm = packedNorm;
    report.gradientNormAbsoluteDifference = abs(legacyNorm - packedNorm);
    report.rateMaximumAbsoluteDifference = maximum_difference( ...
        legacySimulation.rates, packedSimulation.rates);
    report.velocityMaximumAbsoluteDifference = maximum_difference( ...
        legacySimulation.velocity, packedSimulation.velocity);
    report.positionMaximumAbsoluteDifference = maximum_difference( ...
        legacySimulation.position, packedSimulation.position);
    report.parameterMaximumAbsoluteDifference = maximum_difference( ...
        pack_v2_trainables(gpuModel), ...
        pack_v2_trainables(reconstructedModel));
    absoluteValues = [report.lossAbsoluteDifference; ...
        report.maximumComponentAbsoluteDifference; ...
        report.gradientMaximumAbsoluteDifference; ...
        max(report.gradientFieldMaximumAbsoluteDifferences); ...
        report.gradientNormAbsoluteDifference; ...
        report.rateMaximumAbsoluteDifference; ...
        report.velocityMaximumAbsoluteDifference; ...
        report.positionMaximumAbsoluteDifference; ...
        report.parameterMaximumAbsoluteDifference];
    report.passed = all(absoluteValues <= report.tolerances.absolute) && ...
        report.gradientRelativeDifference <= report.tolerances.relative;
    fprintf(['Equivalence: loss %.3g, components %.3g, gradient %.3g ', ...
        '(relative %.3g), norm %.3g, rates %.3g, velocity %.3g, ', ...
        'position %.3g, parameters %.3g; passed %d.\n'], ...
        report.lossAbsoluteDifference, ...
        report.maximumComponentAbsoluteDifference, ...
        report.gradientMaximumAbsoluteDifference, ...
        report.gradientRelativeDifference, ...
        report.gradientNormAbsoluteDifference, ...
        report.rateMaximumAbsoluteDifference, ...
        report.velocityMaximumAbsoluteDifference, ...
        report.positionMaximumAbsoluteDifference, ...
        report.parameterMaximumAbsoluteDifference, report.passed);
    if ~report.passed
        error('V2Model:ExecutionEquivalence', ...
            'Packed execution failed numerical-equivalence tolerances.');
    end
end

function difference = scalar_difference(first, second)
    difference = abs(double(gather(extractdata(first - second))));
end

function difference = maximum_difference(first, second)
    first = underlying(first);
    second = underlying(second);
    difference = double(gather(max(abs(first - second), [], 'all')));
end

function difference = relative_difference(first, second)
    first = underlying(first);
    second = underlying(second);
    numerator = double(gather(sqrt(sum((first - second).^2, 'all'))));
    denominator = max(1, double(gather(sqrt(sum(first.^2, 'all')))));
    difference = numerator / denominator;
end

function value = vector_norm(input)
    input = underlying(input);
    value = double(gather(sqrt(sum(input.^2, 'all'))));
end

function output = underlying(input)
    output = input;
    if isa(output, 'dlarray')
        output = extractdata(output);
    end
end
