function tablePath = write_v2_pre_go_diagnostic_table(leakage, tablePath)
    [delayMs, targetAngleDeg] = ndgrid( ...
        leakage.delayMs, leakage.targetAnglesDeg);
    output = table(delayMs(:), targetAngleDeg(:), ...
        leakage.fullRmsSpeedMPerSec(:), ...
        leakage.final150RmsSpeedMPerSec(:), ...
        leakage.final100RmsSpeedMPerSec(:), ...
        leakage.maximumPreGoSpeedMPerSec(:), ...
        'VariableNames', {'delay_ms', 'target_angle_deg', ...
        'full_prep_rms_speed_m_per_s', ...
        'final_150ms_rms_speed_m_per_s', ...
        'final_100ms_rms_speed_m_per_s', ...
        'maximum_pre_go_speed_m_per_s'});
    writetable(output, tablePath);
end
